### ISSUE TITLE
scaffolding the layout / navigation

### ISSUE THREAD

**Issue by helenvarley** [upstage-org/mobilise#101]
Hello everyone, I'm scaffolding the layout / navigation of our new UpStage based on these wireframes. Do you think these menu items are okay? If I missed anything or something suppose to change just tell me about it. Thank you :smile: 

**For a guest (the Foyer):**
<img src="https://user-images.githubusercontent.com/29925961/103146664-61abcd80-477f-11eb-953a-f0edf616b7cf.png" width="250"/> <img src="https://user-images.githubusercontent.com/29925961/103146669-738d7080-477f-11eb-9157-9f94ef70926e.png" width="250"/> <img src="https://user-images.githubusercontent.com/29925961/103146681-a172b500-477f-11eb-9e84-55c5e5e72ae9.png" width="250"/> 
**For a logged in user (the Dashboard):**
<img src="https://user-images.githubusercontent.com/29925961/103146719-e8f94100-477f-11eb-963d-feb462210609.png" width="250"/> <img src="https://user-images.githubusercontent.com/29925961/103146721-f0204f00-477f-11eb-9010-4cbffdcac580.png" width="250"/> <img src="https://user-images.githubusercontent.com/29925961/103146724-f6aec680-477f-11eb-9daa-ab2acfd5b7dd.png" width="250"/> <img src="https://user-images.githubusercontent.com/29925961/103146731-ff9f9800-477f-11eb-8aab-1e99f175fff8.png" width="250"/> 
**Click on the right UpStage logo will navigate back to the Foyer:**
<img src="https://user-images.githubusercontent.com/29925961/103146715-d54dda80-477f-11eb-89cb-db482dd01125.png" width="250"/>

_Originally posted by @nguyenhongphat0 in https://github.com/upstage-org/mobilise/issues/64#issuecomment-751326932_

**Comment by helenvarley** [comment]
http://159.89.19.111/V2.0/ui/

**Comment by helenvarley** [comment]
great work, @nguyenhongphat0 :)
some comments from me:

- as there is a login button top right, i think we don't need the blue dashboard area on the home page (this is just the login to get to the dashboard)
- the links area is maybe also not necessary, since there is the "more" dropdown at the top ... ?
- i don't think we need the "stages" link at the top; the public will be able to reach any publicly accessible stages via the "what's on" list, and players will be able to access the full list of stages once they have logged in. 
- the UpStage logo at top left should link to www.upstage.org.nz

**Comment by nguyenhongphat0** [comment]
Thanks @helenvarley I'll take care of these. What's about the dashboard section? Here is an account to access it: testplayer/12345678

Since the Stage Detail is too narrow, I break it into 2 columns:
![image](https://user-images.githubusercontent.com/29925961/103173389-4333f800-488d-11eb-8c19-29ecae8d89cf.png)
![image](https://user-images.githubusercontent.com/29925961/103173398-58108b80-488d-11eb-94c1-f27163a2cee5.png)
is this okay?

**Comment by nguyenhongphat0** [comment]
The next thing I'm about to do is mocking this wireframes: https://github.com/upstage-org/mobilise/issues/64#issuecomment-740554084. But I wonder which button should lead me to this "Workshop Overlay"? Is there should be a Manage button in Stage Detail, like this: 
![image](https://user-images.githubusercontent.com/29925961/103173496-f4d32900-488d-11eb-952f-fb3a658cc3fc.png)?

**Comment by helenvarley** [comment]
actually i need to look at this, because i think it is mixing up some things together. there is information needed for the list of all stages, and then there is the information needed for one specific stage.
i have to do something else now & have a different meeting in half an hour, so i will need to come back to it a bit later, sorry!

**Comment by helenvarley** [comment]
i will check with @vickis & @petyrv, but i think we would not want the thumbnails on the stage list in the ddashboard (http://159.89.19.111/V2.0/ui/dashboard/my-stages) - this list can potentially get very long. it might be ok for the thumbnails just for "my stages", but even still, that could easily be more than 10 stages for some of us; & many more for "all stages" - when we have had festivals there are lots of stages.

**Comment by helenvarley** [comment]
thinking about it more, while sleeping, there are actually three different "details" that we need for the stages:

1. information for the guest/audience/not logged-in person that is displayed in the Foyer
2. information in the stage list that is displayed in the Dashboard (visible to logged-in players)
3. information for one specific stage

in fact there are already issues for 2 and 3, so let's continue that discussion there: #26 is the stage list, and #18 is the specific stage information, or stage edit screen.

this issue can then continue just for the first one, which is the information displayed in the Foyer, publicly visible to everyone. this is where the thumbnails & a nice display is important :) the information is:

- list of live and soon-to-be-live stages (beginning with the first one to happen, with future shows following chronologically)
- title of show, thumbnail image, brief description and "more" link (optional? where does the "more" link go? now all shows have their own website)
- live link at show-time

**Comment by elisadcg** [comment]
wireframe foyer 

![wireframe-foyer](https://user-images.githubusercontent.com/7611913/103770936-1c14bd80-5027-11eb-88f9-0d3a385725a4.png)
