### ISSUE TITLE
The Demo Stage

### ISSUE THREAD

**Issue by nguyenhongphat0** [upstage-org/mobilise#108]
Here are the to do list after receiving feedbacks:

- [x] Prompt a login for player to enter their password. This is dismissable so that guess can view the stage without an account.
- [x] Allow change their chat nickname. Default nickname is firstname (if logged in), username (if there is no firstname) and "Guess" (for not logged in) audience
- [x] Avatar/Prop opacity tool. Press Del key to remove them permantly
- [x] Put new assets to the demo stage
- [x] Audio tool
- [x] Fix mobile collapsed issue
- [x] Multiframe avatar
- [x] Chat text bubbles on player's avatar

**Comment by helenvarley** [comment]
it's Guest (not guess) :)
opacity tool isn't essential for the demo, but is also good if it's there

how far away from having avatar speech are we? or if not speech, then the text in speech bubbles on stage by the avatar (as well as in chat)? i realise that this also requires a fundamental thing of being able to associate the avatar with the player, which i think at the moment doesn't work, as anyone can move any avatar on the stage. but if it's achieveable, it would be nice to have it for the demo - to make an avatar "speak" if not actually audibly, then at least in a visible cartoon bubble on the stage.

**Comment by helenvarley** [comment]
would also be great to play an audio file, but again, if this isn't achievable in the time frame it's not difficult for people to imagine :)

**Comment by helenvarley** [comment]
the easing (bounce of the movement) is great, but it would also be good to have this as an option, not the default.

**Comment by helenvarley** [comment]
will it be possible to show a prop attached to an avatar? this is what we are calling a costume prop, & elisa just put up wireframes for that today (#64). in the demo stage, the example would be to put the mask onto an avatar. the idea is that when the prop is attached to the avatar as a costume, that it would then move and scale with the avatar.

**Comment by vickis** [comment]
great progress! :)

**Comment by helenvarley** [comment]
we absollutely need to be able to remove avatars & props from the stage :)

**Comment by helenvarley** [comment]
if possible - the ability to select an avatar & speak as that avatar with speech bubble, text in chat as well

**Comment by nguyenhongphat0** [comment]
The remove avatars will be available as soon as my IP can address the MQTT broker :+1: 
Meanwhile I'm fixing the collapse issue on mobile, have a look:

**Comment by nguyenhongphat0** [comment]
![Screenshot_20210109-132500_Chrome.jpg](https://user-images.githubusercontent.com/29925961/104084994-b9b5fa00-527e-11eb-8724-3529b4cf4a5e.jpg)

**Comment by nguyenhongphat0** [comment]
> we absollutely need to be able to remove avatars & props from the stage :)

Now you can remove avatar/prop by choose them and press Delete/Backspace key. Give it a try: http://159.89.19.111/V4.0/ui/live

**Comment by helenvarley** [comment]
damn, i guess my IP has changed again!!

**Comment by helenvarley** [comment]
yay, it works! :+1:
