### ISSUE TITLE
on-stage tool palette 

### ISSUE THREAD

**Issue by helenvarley** [upstage-org/mobilise#118]
now that we have a demo audience view of the demo stage, i realise that the left-hand tool palette (listing avatar, props, backdrop etc) needs to be moveable - otherwise this area of the stage is difficult to use.

can it be like a dock that slides out when you put your mouse right over to the edge of the stage? or in some other way minimiseable? we need to be able to access it quickly, but we also need to be able to operate avatars that would be underneath it.

**Comment by nguyenhongphat0** [comment]
The dock sound great! I'll prepare it before the demo
