### ISSUE TITLE
Basic Draw Tool

### ISSUE THREAD

**Issue by paul-rohrlach** [upstage-org/mobilise#124]
Players should be able to "draw" on the stage much like how annotations work in other systems.

A player should be able to select a drawing tool, then click-and-hold on the stage and be able to create a freeform drawing.

Once the player releases their mouse button, the drawing is "finished" and should become a distinct object on the stage that behaves like an avatar or prop.

**Comment by nguyenhongphat0** [comment]
Hello @everyone, the drawing tool is now live at http://159.89.19.111/V4.0/ui/live, go draw something on it and give me feedback if you want on another issue. Thank you
Ps: there's something about the Undo that'll need some more work, if you can't use it, please be patient 😅

**Comment by helenvarley** [comment]
great work! :D i can see that three is some issue with undo, & also we probably don't need erase, undo and clear - or at least, we need to be clear about what each one does. for example, undo removes the last drawn line, whereas erase removes everything ... and clear?
it's very cool to be able to draw & save, then make it appear later! need to be able to then do things with that drawing e.g. take it off the stage ...
one feature that we have in the UpStage v3 drawing tool is a palette of the last selected colours, i think about 8 or 10 colours are displayed. this is very useful, as often when you're doing a drawing you want to use a palette of several colours & come back to the same one. (probably this needs a separate issue).

**Comment by nguyenhongphat0** [comment]
You can think of the Eraser tool as a white brush, it will remove the part of drawing that you rub it with your mouse. The undo tool will revert the last operation, no matter if it is brush or erase. And Clear will remove all part of the drawing, to the blank start. I created those tools based on issue #48

**Comment by vickis** [comment]
yes that makes sense,  and thanks! :)

**Comment by vickis** [comment]
The drawing tool is superb! I had a little difficulty with the erase clear but my network is a little flakey this evening 
clear worked well
and i managed to save the drawing as an entire object 
this is fantastic! :D
