### ISSUE TITLE
Streaming: Front End features

### ISSUE THREAD

**Issue by gloriajw** [upstage-org/mobilise#125]
The front end should be able to display a stream in any shape "container" (outer frame). For example: showing a dog video in a "frame" on stage that is shaped like a dog. 
This container should be able to be moved around the screen, similar to how we move avatars. There can be more than one streaming container on a stage. 
No other features/attributes of an avatar are expected on this streaming container at this moment.

**Comment by nguyenhongphat0** [comment]
Hello Gloria, do you have any working example for this feature somewhere on the internet? From what I understand, you want to play some kind of "transparent background video", right?

**Comment by helenvarley** [comment]
it looks like they do it in https://spatial.chat/ (scroll down for images)
& many years ago it was done in a platform call Wirefire that has a lot of similarities to UpStage http://entropy8zuper.org/wirefire/ - there are screenshots here: https://www.flickr.com/photos/entropy8/sets/72157594472981804/ - the webcams could be moved around the screen with the video showing in the circle.  (wirefire used flash so probably not relevant at all now! but just to see another example)

**Comment by gloriajw** [comment]
Hi Phat. I am not sure if the background has to be transparent to fit inside of an oddly-shaped frame. 
Maybe the proper terminology is to play a video inside a canvas, and be able to move and pick odd shapes for that canvas: https://stackoverflow.com/questions/4429440/html5-display-video-inside-canvas

**Comment by nguyenhongphat0** [comment]
Thank you everyone! So which source of stream are we going to use? From what I see from the wireframes, they are url (video url I guess). Are we going to support webcam?
<img width="1140" alt="Screenshot 2021-01-22 at 22 36 23" src="https://user-images.githubusercontent.com/29925961/105511394-6a51de00-5d02-11eb-9c72-06880f09029b.png">
I'll implement the streaming after I finish the drawing tool

**Comment by helenvarley** [comment]
if we can support webcams in the same way as WebRTC, like how it works in jitsi, this would be great as it is very simple. BUT would this mean that we then have to bear the cost of the streaming data via UpStage servers?

**Comment by gloriajw** [comment]
I think digital ocean will throttle us if we stream too much, so right now we don't need to worry about costs. But in the field, we do need to warn people about streaming and "capping" their I/O so they get cut off instead of charged for excess.

@nguyenhongphat0 I think we should be stream-source-agnostic: don't worry about the source of the stream, allow as many sources as technically possible. This means the connection "initialization" may require that the client send you info about the bitrate, format, etc. This is OK.

**Comment by vickis** [comment]
agree - would be great for users to choose their own stream
and then connect in to the shape available on stage (being the 'canvas' or
shape)

great work
:)
