### ISSUE TITLE
speech bubble

### ISSUE THREAD

**Issue by helenvarley** [upstage-org/mobilise#131]
avatar speech bubbles need to appear on top of all other avatars, & probably best to have the default as a white background (as in the old UpStage) - the coloured backgrounds can blend into backgrounds and become more difficult to read.

the speech bubbles also shouldn't ease in & out, as the wiggle makes it more difficult to read; can fade out

& the text needs to wrap, so if someone writes a long bit of text, it doesn't stay as one long line that is not easy to read or even all visible. in the old UpStage, the speech bubbles were sized to the width of the avatar - not sure if this will be possible when the avatar sizes are adjustable? there would need to be a minimum size so that if avatar very small, text still readable.

**Comment by vickis** [comment]
think the request should be that the speech bubble is above the avatar on
the screen (not on top as in layers)
 (or below if the avatar is at the top, to the side if the avatar is near
chat or the lefthand side

if the avatar began small and is resized then the text might resize but i
think best if it is the default text size of the browser (eg if the viewer
has text increased due to reading difficulty...

vicki :)

**Comment by helenvarley** [comment]
yes, that's right - had to go back to look at some screengrabs but indeed in UpStage v3, the speech bubbles would also be behind another avatar, if your av was behind it. this is how we want it.

& agree there should be a default minimum text & bubble size, so even if your av is really tiny, the speech bubble is still readable. probably the speech bubble should NOT resize with the avatar - this could be disturbing.

**Comment by nguyenhongphat0** [comment]
Hi guys, I made some changes:

- Avatar speech bubbles appear on top of all other avatars
- White background and black text on bubbles
- Wrap text if the line is too long. The max width of the bubble is based on the width of the avatar, but no smaller than 100px

<img width="1313" alt="Screenshot 2021-02-07 at 16 36 02" src="https://user-images.githubusercontent.com/29925961/107142570-93a97580-6962-11eb-9f13-0a74e1215b7e.png">

Pls let me know if I missed something, thank you!

**Comment by nguyenhongphat0** [comment]
`the speech bubbles also shouldn't ease in & out, as the wiggle makes it more difficult to read; can fade out`
Don't really understand what you mean, Helen 🤔

**Comment by vickis** [comment]
i am guessing this refers to if the avatar moves while the speech bubble is
on screen,
it can fade after a few seconds :)

**Comment by nguyenhongphat0** [comment]
Oh I saw it. When the avatar move the bubble has some glitch that made it disappear and re-appear, fixed.

**Comment by vickis** [comment]
No thanks you! doing great work @Hồng Phát :D

**Comment by helenvarley** [comment]
great work, phat! :) we will test it out & give some more feedback :)
