### ISSUE TITLE
player audience counter on foyer

### ISSUE THREAD

**Issue by vickis** [upstage-org/mobilise#14]
As anyone - audience or logged in player - i want to be able to see how many players and audience are on a particular stage in the stages list. I expect to be able to easily see which stage might be currently active, from the numbers of audience and players there. I expect this information to be recorded someone and accessible after the fact as documentation.

**Comment by helenvarley** [comment]
ah - i just made a comment on #29 asking to have the player/audience counter on the stages list https://app1.upstage.org.nz/V4.0/ui/backstage/stages - not names, just numbers.
