### ISSUE TITLE
text tool 

### ISSUE THREAD

**Issue by helenvarley** [upstage-org/mobilise#149]
i thought there was an issue for this but can't find it, so starting a new one ...
the ability to write text directly onto the stage is really great :) some comments:
- can it be possible to edit the text, when it is created & on the stage? 
- can it be possible to save a text item, in the same way as we can save a drawing, so it can be taken off and put back on to the stage, or created beforehand and then placed on the stage immediately during a performance?
- can there be a way to type live, e.g. the audience is also seeing your new text box when you are tying the text? (perhaps similar to being able to edit the text once it's on the stage?)

**Comment by vickis** [comment]
this is excellent :)
great work team!
agree about the text being seen as written (as a device, especially with
the typewriter text sound :)

**Comment by nguyenhongphat0** [comment]
For now after save a writing I convert it to an image (like a drawing) so that it can work like a normal avatar. Guess I'll have to do some hack to make the text rendered inside avatar, so that we can edit it later, or live writing 👍 

Thanks for separating this issue, it's easier than having all in one big issue!

**Comment by vickis** [comment]
totally understand that
Hồng Phát :)

**Comment by helenvarley** [comment]
> For now after save a writing I convert it to an image (like a drawing) so that it can work like a normal avatar. Guess I'll have to do some hack to make the text rendered inside avatar, so that we can edit it later, or live writing +1
> 
great - but also, this should not be your highest priority; it's a fantastic tool already :) i just always want MORE fantastic ;)

**Comment by helenvarley** [comment]
with the font size, is there a reason for it to be limited to 100? & if not, instead of a dropdown to select the size, could it be a field where we could input any number?

**Comment by vickis** [comment]
agree! :)

**Comment by nguyenhongphat0** [comment]
Well I got inspired from these office software. In Microsoft Word they use the dropdown for font size 😅 A number input would be great!

**Comment by vickis** [comment]
true they do use a dropdown but selecting the field allows you to adjust
the number
best of both ways!! :D
