### ISSUE TITLE
opacity / frame animation / move speed slider

### ISSUE THREAD

**Issue by helenvarley** [upstage-org/mobilise#150]
currently a media object on the stage has a slider which is by default opacity, and can be changed to frame animation or move speed.
if you change the slider on one object, it changes it for all objects on the stage, for that player. it does not change it for other players.
it would be better if it only changed for the object that you had changed it on, and all other objects stayed as default or to whatever you had already changed their slider to.

**Comment by helenvarley** [comment]
@nguyenhongphat0 this is quite important for the first release, as it's very confusing for other players if the opacity slider of the avatar they are holding is changed by somebody else. it means that everyone has to change the slider all the time.

**Comment by vickis** [comment]
Agree no player should have access to the tools of an avatar held by
another - by default only you control your own avatar

**Comment by riadsalameh** [comment]
Currently the opacity is for avatar, props, stream, drawing and text. Will it eventually be included for the backdrop as well?

**Comment by helenvarley** [comment]
good idea riad - also for animation speed, if it's possible to have multiframe backdrops. 
obviously it won't work to have it in the same position on the left, as this would not always be accessible, so need to think about where to put it. maybe it should be a tool in the backdrop bar? as if you had to select the backdrop then this might get confusing with selecting the media on top of it.

**Comment by vickis** [comment]
interesting idea  :)
if the backdrop is clickable (eg can operate sliders) doesn't that create
the possibility of difficulty in selecting avs or props?
a player could use a prop to create a layer and be able to cover the stage
frame which enables manipulating opacity/transparency

**Comment by helenvarley** [comment]
that could be a workaround. but couldn't we also have some tools by the backdrop icon in the backdrop bar? we will need tools in the audio bar, for volume etc of a selected track, so it could be something similar for backdrops? (in the future ... )

**Comment by nguyenhongphat0** [comment]
Yes we can put anything inside the audio bar and backdrop bar (like a slider, a button or a dropdown,...)

**Comment by nguyenhongphat0** [comment]
But let's have another issue for it 😅 I rolled the new code on app1, please close this issue after you check it, thank you!

https://user-images.githubusercontent.com/29925961/114207806-fcbf6080-9986-11eb-8ca3-eb68cc5a10fc.mov

**Comment by helenvarley** [comment]
ok, will do ... soon ... :)

**Comment by helenvarley** [comment]
just tested the different opacity sliders - great, this is working for me now :)
