### ISSUE TITLE
live action

### ISSUE THREAD

**Issue by helenvarley** [upstage-org/mobilise#160]
We want an option to show or not show the actions that we are doing - for example, if we are drawing, we want the option to either show that drawing as it is being made, so that everyone sees the drawing as it is being drawn; or, to draw first and then show / publish. 
the same also with text - that we can choose whether to see the text appearing letter by letter as it's typed, or whether it appears as a block of text.
also with avatars - we might want the audience to see the avatar shrink or grow, or simply appear that size.

not quite sure what to call this, but "live action" will do for now :)

**Comment by paul-rohrlach** [comment]
@helenvarley given that we have 2 weeks until we're putting a feature freeze in place.  We need to start thinking very seriously about prioritizing feature requests.

In relation to our other open issues, how important is this short term?

**Comment by vickis** [comment]
This ius pretty important for drawing
it should act like the whiteboard/ drawing function in conferencing apps
where you see the line as it is drawn

with the ability to save etc then we can have the drawing appear/fade in
etc
but what is engaging mostly is the act of cresting the marks imho

**Comment by helenvarley** [comment]
yes, for drawing it's really important. it is also important for fading in & out, and resizing of avatars & props. 
does it already work for moving? i actually haven't observed, but if vicki moves her avatar to another position, i will see it moving there, not just jumping, won't i? need to check ...
this has been in the wireframes, we had some early conversations with elisa & petyr about a "publish" button, or a way to switch between the action being shown as it's being done, or published once it's been done without being seen.
it is a little bit complicated to get my head around, but once we have a version of it we should be able to refine how it can work

**Comment by elisadcg** [comment]
Ok let just wireframe the idea, for the day it will be implemented.
Actually we don"t have the possibilité to show the change done.
![Screenshot_20210303_091638](https://user-images.githubusercontent.com/7611913/109780599-72f1da00-7c07-11eb-93fc-35e9526083bc.png)

I suggest around the avatar, just the bulb icon. When pressed, the change are publish and when not pressed, then the avatar will appear after the action.
![Uploading issue160-live-action.png…]()

**Comment by helenvarley** [comment]
great! :) would it be that the light bulb icon is lit up, e.g. yellow, to indicate that what you are doing is being seen in real time, and black when it's not?

**Comment by elisadcg** [comment]
black is when it's not ! i imagine more green if yes ? but yellow it's good also !

**Comment by helenvarley** [comment]
actually green is probably a good idea, as the little sign to show that you are holding an avatar is a yellow pin, and it could be confusing if the lightbulb is also yellow

**Comment by nguyenhongphat0** [comment]
Hi @elisadcg , @helenvarley , I'm working on the light bulb, and I was wondering why we don't add the lightbulb to the context menu? Having thee button at the top make the avatar more clunky, specially when it has small size 🤔 

<img width="522" alt="Screenshot 2021-03-22 at 13 57 59" src="https://user-images.githubusercontent.com/29925961/111951770-ae047080-8b16-11eb-91db-9cfa96ae57e6.png">

**Comment by elisadcg** [comment]
Light Bubble : the idea is to get quickly access to the options "show the change at the audience" / "don't show the change at the audience".
Do you think add this option only available in the context menu is good idea ? 
We want the move of avatar had this option available too.

Furthemore, we have a second pb : the context menu  is difficult to open it.
What do the icon on the left of the light bubble ?

**Comment by helenvarley** [comment]
can it be in both places?
i agree about the context menu being difficult to open - an icon might be easier (as an alternative) ?

**Comment by nguyenhongphat0** [comment]
Yes, both places is how I'm working on it right now 👍

**Comment by nguyenhongphat0** [comment]
> The rectangle icon is for fadin & out "the animation"

Hello @elisadcg , can you describe more about this fadin & out "the animation" 🤔

**Comment by elisadcg** [comment]
fade in & out animation is like transition between two steps. The change is smooth, not brutal.

**Comment by nguyenhongphat0** [comment]
Right 🤔  But what should happen exactly when you click that button 😅 
<img width="489" alt="Screenshot 2021-03-31 at 20 47 42" src="https://user-images.githubusercontent.com/29925961/113154611-61314000-9262-11eb-8f28-d1a751ae1ade.png">

**Comment by elisadcg** [comment]
Nice! Waiting to test when it's release :)

**Comment by helenvarley** [comment]
this is also the same or connected to #63

**Comment by nguyenhongphat0** [comment]
Can we move these 3 buttons to the right of the avatar @elisadcg , @helenvarley @vickis ? The top of the avatar is collapsed with many things now: marker, rotate control, and chat bubble 🥶 

<img width="311" alt="Screenshot 2021-04-22 at 13 18 58" src="https://user-images.githubusercontent.com/29925961/115665406-7a16a800-a36d-11eb-9a58-c9a7bb4b4ed1.png">

**Comment by elisadcg** [comment]
i think yes, artist prefer not an heavy control

**Comment by helenvarley** [comment]
yes good idea :)
