### ISSUE TITLE
Stage should show all objects in relation to each other regardless of the screen size

### ISSUE THREAD

**Issue by vickis** [upstage-org/mobilise#162]
The objects on stage (avatars, streams drawing etc are usually placed in relation to other objects or to the stage area (eg an avatar speaking to audience by being close to the chat window

things should have the same relative layout 
this is not currently the case (see the difference between vicki's screen and eva's shared screen in jitsi

<img width="1280" alt="Screen Shot 2021-03-03 at 9 02 27 AM" src="https://user-images.githubusercontent.com/4249450/109777716-e415a980-7c68-11eb-9ef2-47dc0aa3f70e.png">

<img width="1280" alt="Screen Shot 2021-03-03 at 8 41 11 AM" src="https://user-images.githubusercontent.com/4249450/109778145-5b4b3d80-7c69-11eb-80ba-0f67a3f2a122.png">
<img width="1280" alt="Screen Shot 2021-03-03 at 8 41 15 AM" src="https://user-images.githubusercontent.com/4249450/109778171-61d9b500-7c69-11eb-9e51-990151af6723.png">
![Uploading Screen Shot 2021-03-03 at 8.56.44 AM.png…]()

helen's screen 
https://pasteboard.co/JQNn3Pg.png

**Comment by vickis** [comment]
<img width="1280" alt="Screen Shot 2021-03-03 at 8 56 44 AM" src="https://user-images.githubusercontent.com/4249450/109778477-b9782080-7c69-11eb-9201-ceebe0c20998.png">
<img width="1280" alt="Screen Shot 2021-03-03 at 8 56 50 AM" src="https://user-images.githubusercontent.com/4249450/109778574-dc0a3980-7c69-11eb-9a9a-3187ce5af42c.png">

**Comment by nguyenhongphat0** [comment]
This is one big important issue 👍 Thank you for the detailed screenshots

**Comment by nguyenhongphat0** [comment]
If we want the stage look the same on all devices, we must force a "base resolution" so that all devices must scale to that.

Or a "based ratio", like 16/9 or 4/3 would also works. Which would be the best based for UpStage?

**Comment by helenvarley** [comment]
can we test it with a base ratio of 16/9, as elisa has suggested on slack?
how do other environments do it, such as mozilla hubs or gather.town? everything is proportionate there ...

**Comment by nguyenhongphat0** [comment]
I just take a look at Mozilla Hubs (which is amazing, I never heard about it before 😲): they crop the view port to fit current screen ratio. Like this:

On wider screen (16x9):
<img width="1340" alt="Screenshot 2021-03-03 at 18 30 46" src="https://user-images.githubusercontent.com/29925961/109799399-955b1600-7c4e-11eb-8d41-6eadba68e809.png">

On narrower screen (4x3) the ducks are missing:
<img width="1013" alt="Screenshot 2021-03-03 at 18 31 12" src="https://user-images.githubusercontent.com/29925961/109799444-a572f580-7c4e-11eb-8720-8c00b3ff4d6e.png">

**Comment by helenvarley** [comment]
also: i just tried using ctrl+ to make the chat text bigger, & it also made the avatars increase in size AND move in position on the backdrop; the backdrop did NOT change size. so having a tool to adjust font size is important - #51

**Comment by helenvarley** [comment]
@nguyenhongphat0 - i see, that's interesting - in mozilla hubs, you can move around, so they are not trying to have the same view for everyone. in UpStage the audience can't move around, we want everyone to see or not see the ducks. we can live with a bit of difference around the edges i think, this would be similar to having a bad seat at the theatre that meant you couldn't see the edge of the stage ... but in general we want it to be that everyone is seeing the same thing, in the same proportions.

**Comment by nguyenhongphat0** [comment]
The same for gather.town:

<img width="954" alt="Screenshot 2021-03-03 at 18 35 55" src="https://user-images.githubusercontent.com/29925961/109800329-993b6800-7c4f-11eb-8fb6-a0d10a53193b.png">

<img width="1317" alt="Screenshot 2021-03-03 at 18 36 26" src="https://user-images.githubusercontent.com/29925961/109800118-64c7ac00-7c4f-11eb-8b22-81135e25c977.png">

I don't think we should crop the view like them, because they are games with a character at the center, and the character can move around. I think UpStage's stage should scale based on a defined ratio, like a video on YouTube, so that you can see all objects on any screen-size.

**Comment by helenvarley** [comment]
agree; we have a frame that we are working within, so it is a different concept. but these platforms keep the ratio of where everyone is, if your avatar is moving and someone else is moving, & if you zoom in/increase the size it keeps the same ratio/proportions. maybe it's built in a way that isn't compatible with what we need for UpStage ...
