### ISSUE TITLE
context menu position

### ISSUE THREAD

**Issue by helenvarley** [upstage-org/mobilise#163]
the context menu that appears when you right-click on an avatar, prop, drawing, text or stream needs to always be visible and accessible. currently if the object is near to the chat, a lot of the menu can be inaccessible. 

it should also be possible to make it smaller, which would help as well, e.g.:
- "set as avatar"
- "change nickname"
- the slider options could just be "opacity" "animation" and "move"

and, since there are icons for each menu option as well as text, could there be an option to have the context menu simply as icons? once you are an experienced player, you only need the icons, you know what they mean. i'm thinking of the context menu on the Tap, which was only icons and i think a hover label.
![tap_context_menu](https://user-images.githubusercontent.com/3437324/109784913-d978f700-7c0b-11eb-9c42-a9ef503f0271.png)
this is not a very good image, the Tap doesn't exist any more & i've just taken this out of one of the manuals that i found. i also remember that this context menu in the Tap was a little bit tricky as it was very small and some of the icons were very similar, but generally it was good for having a lot of tools in a small amount of space.

![menu_size](https://user-images.githubusercontent.com/3437324/109783865-bdc12100-7c0a-11eb-86e2-dbe454c0de4d.png)
![menu_under_chat](https://user-images.githubusercontent.com/3437324/109783881-bf8ae480-7c0a-11eb-8832-588445820128.png)

**Comment by vickis** [comment]
agree :)
is there a way to detect where the avatar is and if close to chat etc then
the context menu opens to the (screen) left rather than the right of the
avatar

**Comment by helenvarley** [comment]
must be possible - as if you hide the chat, & move your av over to the right edge of the browser window, which would be under the chat, the context menu then pops over to the left so you can still see it. so this just needs to be set to happen at the edge of the chat, when the chat is exposed. 
(it would also be fine if that still happened even when the chat is hidden or minimised, if it isn't possible to make it know whether the chat is there or not.)
