### ISSUE TITLE
animation broken?

### ISSUE THREAD

**Issue by helenvarley** [upstage-org/mobilise#167]
i was testing the position of the context menu, & it seems that the animation feature is broken - when i click on the play button to animate an avatar, it doesn't play - it disappears ...

**Comment by nguyenhongphat0** [comment]
Sorry @helenvarley , the relative position did changed a lot of things. Please visit the stage again after a hard reload (Ctrl+F5) and let me know if the issue is still happen

**Comment by helenvarley** [comment]
we are used to things breaking when something else is fixed! it's working again now, thank you :)
