### ISSUE TITLE
Streaming experimentation

### ISSUE THREAD

**Issue by gloriajw** [upstage-org/mobilise#169]
Experimenting with nginx streaming config.

**Comment by helenvarley** [comment]
how is it going with the streams? :)

**Comment by gloriajw** [comment]
Good question. I haven't dug in yet, sorry for the delay. I will have a real answer this weekend.

**Comment by helenvarley** [comment]
the artists are keen to know when they can start playing with it :)
(so we will also need to think about a streaming server, at least just for the mobilise/demobilise project period, but perhaps also that we can make available for a small fee to others who don't have access to their own?)

**Comment by gloriajw** [comment]
I do have code saved from the beginning of my experimentation with a custom streaming server. I also ping Martin a while ago, and discovered he did this already, and I have a pointer to his notes, code, etc. I just need to execute. The delay is on me, sorry.
