### ISSUE TITLE
moving one object caused another to also move

### ISSUE THREAD

**Issue by helenvarley** [upstage-org/mobilise#187]
i have a prop and an avatar on the stage. they were overlapping, and every time i tried to adjust the slider of the avatar, i just ended up moving the prop. so i had to move the avatar away from the prop in order to adjust the slider. i moved the avatar towards the chat window, and at the same time the prop jumped up to the top left corner of the stage and out of sight.

**Comment by helenvarley** [comment]
it also happens when i double-click on the avatar to hold & speak as it - the prop flew off & away out the top left-hand corner. 
this is on https://app1.upstage.org.nz/V4.0/ui/live - is it the same as the other stages?

**Comment by nguyenhongphat0** [comment]
Hi Helen, I just rolled the fix on app1, please go there and take a fresh reload (Ctrl+F5). Let me know if you still facing the issue

**Comment by nguyenhongphat0** [comment]
This was the `attach prop to avatar` feature that I prepared for the demo stage. It used to work fine until the relative position impact and cause crazy behaviour to this. We will have a proper way to attach the prop to avatar in the future (maybe next release)

**Comment by helenvarley** [comment]
checked & it's fixed :+1: 
the attach prop feature is definitely a "nice to have" rather than a "must have" ! :)
