### ISSUE TITLE
on one stage and one avatar, slider doesn't work for move or animation speed

### ISSUE THREAD

**Issue by helenvarley** [upstage-org/mobilise#191]
using the gargoyle avatar on https://app1.upstage.org.nz/V4.0/ui/live/first_stage, the slider only works for opacity. if i change it to either animation or move speed, the slider is in the middle and i can't move it - dragging it up or down moves the whole avatar.

it's odd but it seems to be only this avatar - there are 2 other avs on that stage & the slider works as expected on those, also on avatars on other stages. the gargoyle avatar doesn't appear on any other stages so i can't tell if it's something with that avatar or only with that avatar on that stage.
![Screenshot at 2021-03-22 14-14-58](https://user-images.githubusercontent.com/3437324/111995317-13f1f780-8b19-11eb-9620-64b566ebf0d8.png)

**Comment by nguyenhongphat0** [comment]
It's because the edge of rotated avatar cover the slider @helenvarley , this bug is hilarious 🤣 And sorry about this, I'll fix it 👌 
<img width="319" alt="Screenshot 2021-03-22 at 21 45 10" src="https://user-images.githubusercontent.com/29925961/112008238-e2e4e780-8b57-11eb-81d1-024159ee6d3e.png">

**Comment by nguyenhongphat0** [comment]
<img width="319" alt="Screenshot 2021-03-22 at 21 48 54" src="https://user-images.githubusercontent.com/29925961/112008841-70283c00-8b58-11eb-9ff4-c846038ffc2c.png">

**Comment by helenvarley** [comment]
ah - i didn't even realise the avatar was rotated!

**Comment by nguyenhongphat0** [comment]
The fixed is rolled on app1, @helenvarley . Can you please check if you're still facing the issue, and close it if it has been fixed 👍

**Comment by helenvarley** [comment]
yay! fixed :)
