### ISSUE TITLE
player approval and management

### ISSUE THREAD

**Issue by helenvarley** [upstage-org/mobilise#199]
https://app1.upstage.org.nz/V4.0/ui/dashboard/admin/approval
i guess there are going to be more options for player management, as menu items where the "registration approval" button is, here are some thoughts about what we need to do on this page:

- change email address or password of a player (individual players should be able to do this themselves, but admins also need to do it sometimes
- delete players
- sort the list - alphabetically by username or email address; chronologically by date registered and last log0in date
- sort the list accorting to role/status (e.g. to find all those with admin rights)
- change player role/status

**Comment by nguyenhongphat0** [comment]
I'm working on this!

**Comment by helenvarley** [comment]
this is great! :+1: 

i am just wondering if there can be an option also to select one player and be able to do all the things for that player on one screen? for example if a player has lost their password and needs to update their email address, so they ask me to do it. could admins see a player's profile in the same way that we can see our own profile, with all the information for that person on one screen?

the way it is laid out now will be really great for situations where we need to do things like delete a group of users after a workshop or things like that.

**Comment by nguyenhongphat0** [comment]
Hi @helenvarley , now we are able to update someone else profile as well, checkout the Profile Management inside Admin menu 🎉 

<img width="1403" alt="Screenshot 2021-04-01 at 23 30 37" src="https://user-images.githubusercontent.com/29925961/113325188-4635fd00-9342-11eb-83fe-7633907a0043.png">

**Comment by vickis** [comment]
Great work! :)

**Comment by nguyenhongphat0** [comment]
Now we're able to do all the thing with other players's account from this menu. Can we close this issue now 🍀

**Comment by nguyenhongphat0** [comment]
Phone number is not a mandatory field Helen. And I can remove the Ok to sms toggle if you want to

**Comment by helenvarley** [comment]
even if it's not a mandatory field, we should only ask for the data that we actually need. 
we need to make a privacy policy, which states what data we collect, why, how we store it and for how long, and what we do with it. best practice for data security is to only collect the data that we absolutely definitely need.
at the moment i don't think there is a reason for us to collect people's phone numbers - this isn't needed for them to use UpStage, & we can contact them via email. 
@vickis do you have any thoughts on this? @paul-rohrlach @gloriajw is there any technical need for phone numbers?

**Comment by vickis** [comment]
agree can remove that field
if a group are working and rehearsing together they will exchange other
means of communication themselves (we do not want to be responsible for
lots of other people's data )

**Comment by nguyenhongphat0** [comment]
Okay I removed the Phone and Ok to sms field 🙌 

<img width="1124" alt="Screenshot 2021-04-04 at 15 13 12" src="https://user-images.githubusercontent.com/29925961/113502720-490a3b00-9558-11eb-8b26-0c0c71ae5ca1.png">
