### ISSUE TITLE
"Clear" function

### ISSUE THREAD

**Issue by helenvarley** [upstage-org/mobilise#20]
as a user when i select the clear button, one click clears the last line drawn (like edit undo) and holding down the button clears everything that has been drawn so far on that stage 

(is it possible to "hold down" a button in a GUI? would it work as a double click? or would it be better to have 2 buttons - one that is clear last line & the other clear entire drawing layer?)

**Comment by nguyenhongphat0** [comment]
We have 2 separated buttons for that, one is Undo the previous line, the other is Clear the entire drawing 🎉
