### ISSUE TITLE
horizontal scroll or layout change needed on "my stages"

### ISSUE THREAD

**Issue by helenvarley** [upstage-org/mobilise#206]
on https://app1.upstage.org.nz/V4.0/ui/dashboard/my-stages i cannot access all the stages, because they are listed in two horizontal lines and there is no scroll bar.

better than a scroll bar would be to have the layout so that they don't run off to the right of the page but tile down. 

also maybe good to have a text only list option?

**Comment by nguyenhongphat0** [comment]
Can we reuse the stage table in Dashboard for this page?

It's look like this page is somewhat the Dashboard, but with a filter of stage owner 🤔

**Comment by helenvarley** [comment]
yes - maybe we can combine, & just have the dashboard with a filter for stage owner :+1:

**Comment by elisadcg** [comment]
i don't recommand an horizontal slide, but a thumbnail view responsive
![issue-206-dashboard01](https://user-images.githubusercontent.com/7611913/113122952-6a93bb80-9214-11eb-8d1a-f7fcde8d9f85.png)

**Comment by nguyenhongphat0** [comment]
So are we going to merge this page with the Dashboard
Or separated with different view (table/thumbnail) 🤔

**Comment by helenvarley** [comment]
i think we can merge them :+1:

**Comment by nguyenhongphat0** [comment]
Okay I'm working on this

**Comment by helenvarley** [comment]
looks great! :)
