### ISSUE TITLE
creating a multiframe avatar

### ISSUE THREAD

**Issue by helenvarley** [upstage-org/mobilise#208]
at the moment it seems that the only way to create a multiframe avatar is to upload each frame of the avatar one by one, and then to combine them in a new avatar. the good thing about this process is that we can make multiframe avs from existing avs, which i can imagine could be quite useful in many situations.
the disadvantage is that it's a bit tedious to have to upload each one as a separate avatar; previously we could select multiframe as an option when creating a new av, and then add each frame in the same step as creating the single avatar.
another disadvantage is that we then have all of the frames of the multiframe avatar showing up as single avatars as well; this might be sometimes useful, but mostly not. it means there are a lot more avatars displaying in the lists of media, which makes it more difficult to find the one you want and takes up unnecessary space.

can we have the multiframe option as part of creating a single avatar, as well as keeping the option to create a multiframe av from previously uploaded separate avs?

**Comment by helenvarley** [comment]
and to add to that, the multiframe av that i created (dave multiframe) appears on the stage as a single frame av. also the multiframe helen av only shows as a single frame. i checked both of them in the media section & they appear to be multiframe.

**Comment by nguyenhongphat0** [comment]
> can we have the multiframe option as part of creating a single avatar, as well as keeping the option to create a multiframe av from previously uploaded separate avs?

This sound very great, thank you @helenvarley . I will do an upgrade on this page 🙌

**Comment by nguyenhongphat0** [comment]
> and to add to that, the multiframe av that i created (dave multiframe) appears on the stage as a single frame av. also the multiframe helen av only shows as a single frame. i checked both of them in the media section & they appear to be multiframe.

When you assign media to a stage, I made a `clone` of it instead of `reference` it to the stage, @helenvarley. So if you made change to the avatar after you assign it to stage, you have to save the stage's media again (you don't have to remove and add the avatar again, just save) to apply new change to that avatar on that stage

<img width="995" alt="Screenshot 2021-03-30 at 23 34 03" src="https://user-images.githubusercontent.com/29925961/113024435-ef4cee00-91b0-11eb-96fa-dd13c9a8cb64.png">

**Comment by helenvarley** [comment]
ok, that worked for the dave avatar, but the helen avatar is still not multiframe, and now all the other media (props, audio & backdrops) are not on the stage (but one backdrop is still showing ... )

**Comment by helenvarley** [comment]
and now after i went back and reassigned the props, backdrops & audio to the stage ... everything is there but dave is now not a multiframe av anymore, just a single frame ... 
so i went back and put the multiframe dave back on ... & went back to the stage to find everything apart from the avatars is not there anymore :(

**Comment by elisadcg** [comment]
When i upload a media and hit the Save button. I have an indication Media uploaded successfully. But when i hit the +New button, i get my previous avatar already on the dialog (name, type and thumbnail). I think is better to have a clean dialog. Ready for new media uploaded.

**Comment by elisadcg** [comment]
We probably should be able to put a sprite sheet like this
![perso-sprite01](https://user-images.githubusercontent.com/7611913/113132415-b51a3580-921e-11eb-8e8a-5374a18cb276.png)
and when we manage this media, and put multiframe, is it possible to make it animated ?

**Comment by nguyenhongphat0** [comment]
> ![](https://user-images.githubusercontent.com/7611913/113132415-b51a3580-921e-11eb-8e8a-5374a18cb276.png)

Hi @elisadcg , are you describing the ability to `crop` one big image into a multi frames avatar 🤔 ?

**Comment by elisadcg** [comment]
Yes, i can make a screencast from other software who manage that if could help ?

**Comment by nguyenhongphat0** [comment]
Well technically this is possible to have in UpStage, but it would require lot's of effort to work on it. I suggest this is a `nice to have` feature

**Comment by helenvarley** [comment]
i wanted to make a multiframe backdrop, & i can't work out how to do it at all. i thought i would try with another multiframe avatar, but it seems very un-intuitive. i really think this should be an option in the upload process, like it used to be - that we could select the multiframe option and then add the individual images at upload.
right now i have no idea how to do it ...

**Comment by helenvarley** [comment]
i am trying to fix a multiframe av, where the two frames seem to be slightly differently sized, so it doesn't function as i want it on the stage.
in the media edit interface, the preview doesn't allow me to play the animation, so i can't see if i've fixed it or not.
in the multi-frame selection part, it only shows icons, not names of the different frames, so it's really difficult for me to see what i need to change
in the media list, i can see that the two frames of the avatar are different sizes, and in the media edit interface i can see also that the two frames are a bit different, but it's pretty hard to work out which one needs to be changed.
i deleted the multiframe av from the server, but i guess the original frames are stlil there, so i am going to delete them as well and try reuploading everything ...
![Screenshot at 2021-06-21 10-59-47](https://user-images.githubusercontent.com/3437324/122736208-10891c00-d280-11eb-90a5-36e1e4583f7e.png)
![Screenshot at 2021-06-21 10-59-00](https://user-images.githubusercontent.com/3437324/122736215-12eb7600-d280-11eb-9677-cbfff2ee1d13.png)

**Comment by helenvarley** [comment]
we really need to improve how we can create multiframe avatars. i just created julius on dev-app, & he has 10 frames. so i had to upload each frame individually, & then compile them. it should be possible to select all 10 image files to upload in one go.
this could either be how it was in the old UpStage, with a dropdown menu to select the number of frames & then an browse & upload field for each frame; or, it could be that we can select multiple files to upload in one go.

**Comment by vickis** [comment]
Selecting a range of numbered files works well
Eg julesMFA1, jukesMFA2.. etc would be great :)

**Comment by nguyenhongphat0** [comment]
Yes you can now. Take a look:

https://user-images.githubusercontent.com/29925961/131215292-d2b54c6f-528f-4624-9f7e-ac12724822b1.mp4

**Comment by vickis** [comment]
Super great thanks Phat :) !!

**Comment by helenvarley** [comment]
great! i haven't tried it yet as i don't have a multiframe av to upload right now, but for sure we'll try it soon.
