### ISSUE TITLE
stage background colour

### ISSUE THREAD

**Issue by helenvarley** [upstage-org/mobilise#209]
we need to be able to set the background colour of the stage - the colour that we see when there is no backdrop, and at the edges of the backdrop. 
will this be part of the stage management interface, e.g. under general information, or layout?

**Comment by elisadcg** [comment]
in the issue #259 helen said : "actually it would be really cool if you could change the stage background colour on stage in real time as well ... ?"
That's mean a new tool for Live ? or the immediate impact on Live of this edit ?

**Comment by helenvarley** [comment]
i would want to do it directly on the stage

**Comment by elisadcg** [comment]
Is a right click on the empty part of the stage by the player could open a right menu to choose the color ?

**Comment by helenvarley** [comment]
yes, but ... sometimes it could be hard to find the empty part of the stage; it could be covered by other media, especially if the trame of that media has ended up being longer than the media ...

**Comment by elisadcg** [comment]
Then a suggest a parameter button on the toolbox.

**Comment by helenvarley** [comment]
what is a parameter button? 
could it be that the space currently taken up by the "clear" button (to remove the backdrop) could be divided into 2 (or even more, if we think of other useful tools) so that there is a button to remove the backdrop and a button to open a colour picker to set the background colour?

**Comment by elisadcg** [comment]
![issue209](https://user-images.githubusercontent.com/7611913/115517907-f33bcf80-a287-11eb-8fcf-b95469bf42a1.png)

**Comment by helenvarley** [comment]
how do we change frames of the multiframe backdrop - right click on the icon for a menu?

**Comment by elisadcg** [comment]
yes or right click or another button after clear button. Right clic means non intuitive, hiding option.

**Comment by helenvarley** [comment]
i think this is fine - people are going to need to read the manual or have some training in order to know that a multiframe backdrop is possible, & how to make it, so then they will also learn about the right-click :)

**Comment by nguyenhongphat0** [comment]
Pull request #291 will give you the ability to set  "the colour that we see when there is no backdrop, and at the edges of the backdrop" 🙌
