### ISSUE TITLE
media doesn't remain on stage if you reload

### ISSUE THREAD

**Issue by helenvarley** [upstage-org/mobilise#210]
i put a backdrop, two avatars and two props on the stage and started an audio track. then i reloaded the stage, and only one avatar was there and the music was playing. the backdrop was still there.
i tried it again and this time the other avatar was there, and no music. the backdrop was still there.
it should be that we can set media on the stage to be there when anyone enters.

**Comment by nguyenhongphat0** [comment]
Hi @helenvarley, this is how mqtt (or at least our mqtt) broker works. After you subscribe to a topic, you only receive one last message from that topic. Currently we have separated topics for `backdrop`, `object` and `audio`, so you will only receive the last backdrop change, last avatar/prop/drawing on the stage, and last audio played.

I don't know if there are tricks to make the mqtt broker return more message, but this is a double-edged dagger. If we flood the user with all the message ever existed at a time, the browser won't be able to handle it.

**Comment by nguyenhongphat0** [comment]
If you want an audience to see all things on the stage when they come in, I'm suggesting using Scene. I'm thinking about saving a `snapshot` of the stage when you hit the `Save Stage` button (we already have that button, it's just not working right now 😆). Loading a scene will load all the object that existed on the stage at that snapshot moment, and we don't have to overflow user with too much message

**Comment by helenvarley** [comment]
you're right, scene would solve this. i will be patient until the scene feature is implemented! :)

**Comment by helenvarley** [comment]
BUT - what happens if you need to reload during a performance - for example you have a break in your internet connection, or for any other reason you have to reload at some point during the performance. on re-entering the stage, what would you see: the first scene? or the most recently selected scene?
there can also be performances that are totally improvised and don't use scenes at all ... 
there needs to be some more thought about it as it is quite important for the performances. maybe @paul-rohrlach or @gloriajw  has some ideas ... ??

**Comment by nguyenhongphat0** [comment]
Actually Paul already came up with a solution called `event archive`, it's still need some testing but from what I saw it's will work 🎉 So exciting to announce this 🤩 

https://user-images.githubusercontent.com/29925961/115192730-68d35e80-a115-11eb-8cbe-b948d43ccdfc.mov

**Comment by vickis** [comment]
YAY!!
super devs woop woop :D

**Comment by helenvarley** [comment]
great! looking forward to testing it :)

**Comment by nguyenhongphat0** [comment]
I guess we made it: https://dev-app1.upstage.org.nz/V4.0/ui/live/demo
