### ISSUE TITLE
scaling of images on stage

### ISSUE THREAD

**Issue by helenvarley** [upstage-org/mobilise#211]
when i scale an image, i expect the 4 corner handles to work in the same way - that when i drag a corner to the centre, the image scales down. this works as expected if i use the top left or bottom right corner.
using the top right or bottom left corner, the image scales but the frame doesn't go with it - it only goes in one direction, i.e. narrower or shorter, so that it does not any more fit to the image.
this means that it can be difficult to know where the image is going to end up, and perhaps more annoying, it means the frame is bigger than the avatar and therefore possible to accidentally click on when you want another object, or in front of another object so that you can't select it.

https://user-images.githubusercontent.com/3437324/113132244-7d12f280-921e-11eb-81ed-0335d276759a.mp4

**Comment by nguyenhongphat0** [comment]
You are right, this behaviour is strange. I'm using a third party library for this feature, and I'm thinking about replacing it. At the moment we're using `vue3-draggable-resizable`, in the future I'm heading to https://github.com/daybrush/moveable. But the migration may not make it to R1-2021 😞

**Comment by helenvarley** [comment]
yes - we can cope with it as it is for now, but it would be good to get it fixed before the final release as it's something a lot of people will find strange.

**Comment by nguyenhongphat0** [comment]
The migration to `moveable` is completed 🎉 And we can rotate the avatar in any degree now: https://dev-app1.upstage.org.nz/V4.0/ui/live/demo
