### ISSUE TITLE
media upload limit

### ISSUE THREAD

**Issue by helenvarley** [upstage-org/mobilise#218]
We have decided that there should be a limit of 1MB for all media uploads. This needs to be included in the documentation (along with other recommendations for media, e.g. backdrop dimensions, best formats etc).

There should also be a way to over-ride this - e.g. admins are able to upload larger files - as there can be situations where a larger size is necessary (in the past this has most often been audio files).

**Comment by paul-rohrlach** [comment]
This needs to be prioritized.

**Comment by nguyenhongphat0** [comment]
I'm working on this!

**Comment by helenvarley** [comment]
just a thought: is this limit also going to apply to video? 1MB is not at all much for video ... do we need a separate upload limit for video?

**Comment by nguyenhongphat0** [comment]
Having separate upload limit is confusing. I can exclude video from the upload limit, so that you can upload as much as nginx allows (at the moment it allow up to 300Mb)

**Comment by nguyenhongphat0** [comment]
> can we have a tip added beside the "choose a file" button in the media upload interface, that says "Maximum file size: 1MB"

Yes we can 😅

**Comment by helenvarley** [comment]
> Having separate upload limit is confusing. I can exclude video from the upload limit, so that you can upload as much as nginx allows (at the moment it allow up to 300Mb)

ok; we can see how we go with this, particularly monitoring our own storage limits ... we might need some extra info in the documentation, e.g. encouraging people to remove video once performance is finished; and also, as much as possible - once streaming is implemented - to store video elsewhere like vimeo & stream it to the performance.

**Comment by paul-rohrlach** [comment]
Disagree here.  We need to impose a limit on all uploads (Because NGINX *does* have a limit).

**Comment by nguyenhongphat0** [comment]
You're right, Paul! Unlimit upload size actually have a limit and will cause an error.  Having another limit for the videos is okay. But how should we overide this limit?
Can I just multiple the limit of image by `x`, or should I made another column inside upstage_user, call it `video_upload_limit` and do the same with `upload_limit` 🤔

**Comment by paul-rohrlach** [comment]
I would just put a hard limit on videos that matches whatever the NGINX limit is.  The "override limit" permission will allow other media types to go up to the same limit as the NGINX limit.

We're not going to let the application modify the NGINX configuration, so there's no such thing as "unlimited".

**Comment by nguyenhongphat0** [comment]
Okay I got this 👍. Thanks Paul!

**Comment by helenvarley** [comment]
> Disagree here. We need to impose a limit on all uploads (Because NGINX _does_ have a limit). We could have multiple limits and inform the user only if they exceed it. For example:
> 
>     * User selects large image => Error: Images must be no bigger than X
> 
>     * User selects large video => Error: Videos must be no bigger than Y

does this mean that the user doesn't know the limit until they exceed this? this could be very frustrating. the limit should be visible before you select your file to upload.

**Comment by paul-rohrlach** [comment]
It's not like the limit is going to change often.  They'll see the limit if they happen to hit it, then they'll know what it is going forward.

We could have the limits posted in a box of some kind off to the side that says:
```
Upload Limits
Images: X
Sounds: Y
Videos: Z
```

I guess that's something for the UX team to look at (@elisadcg)

**Comment by helenvarley** [comment]
but is it a problem to have it in the interface? a tip saying what the upload limit is? i know in other situations such as a text field where there is a character limit but it doesn't say so, it's just irritating when you unexpectedly hit it. & i can imagine that players might not upload video so often, so it would be easy to forget what it is ...
if it's not difficult to do so, then we should state the limit :)

**Comment by paul-rohrlach** [comment]
It's not a _problem_.  It's a question as to whether it fits with the UX philosophy we're going for.  Which isn't my call to make 😄

**Comment by paul-rohrlach** [comment]
I'll also note here.  That however we choose to convey the limits, they too need to be easily configurable seeing as someone running their own servers can set whatever limit they like.

**Comment by helenvarley** [comment]
agree ... :+1:

**Comment by elisadcg** [comment]
I recommend all specification present in this modal window. Not to let the user try and see that it's not working. A simple sentence in grey would be good.
![Uploading Screenshot_20210407_092208.png…]()

**Comment by helenvarley** [comment]
i agree with elisa. i also agree with paul, that it needs to be easily configurable for those who set up their own UpStage instance and choose a different file size limit.
is it possible that somewhere in the configuration there is a field where an administrator can choose the upload limit, and this is connected to what is displayed on the Upload Media screen?

**Comment by paul-rohrlach** [comment]
Yes and no.  We can allow an app admin to change the number displayed there.  But a sys admin needs to change the limit in NGINX for it to actually work.

**Comment by helenvarley** [comment]
is this something that the person who installs an UpStage instance can do? for example, if a university installs UpStage on their own network, & want to allow their students to upload bigger files, can their tech person adjust the limit?

**Comment by nguyenhongphat0** [comment]
Yes Helen, admin can adjust individual upload limit inside Admin section.
And their tech person can change the `nginx config` to increase maximum upload limit for videos

<img width="1400" alt="Screenshot 2021-04-08 at 13 06 01" src="https://user-images.githubusercontent.com/29925961/113976342-2f743680-986b-11eb-89be-259dc1da434e.png">

**Comment by vickis** [comment]
great :)

**Comment by paul-rohrlach** [comment]
Are we happy with this now?  Can it be closed?

**Comment by vickis** [comment]
yes :)

**Comment by helenvarley** [comment]
we need a bit more information in the interface - could it say "1Mb" at the low end and "300MB" at the upper end?

i think this is fine for now, but i'm wondering if it wouldn't be better to have a dropdown with a few options rather than a slider - since you don't know what you are adjusting the amount to. we might often want to allow people to have an upload limit of something like 2 or 5 MB, if they are uploading some sound files; but it's very difficult to get something between 1 and 30 MB. 
the 300MB upper limit is likely to be only used for video, & it might be that we want to allow a player to have a 300MB limit only for video files, and a 1MB limit for everything else.

but this all needs further thinking & experimenting, it is not urgent for now :)
