### ISSUE TITLE
avatars should only be held by one player at a time

### ISSUE THREAD

**Issue by helenvarley** [upstage-org/mobilise#219]
We decided that avatars should only be "held" by one player at a time. This means that:
- when you drag an avatar onto the stage, the default is that you are "holding" it.
- "holding" an avatar allows you to manipulate (move, animate, rotate, fade in & out, etc) and speak as this avatar (speech bubble, text2speech voice, chat text with avatar name).
- no other player can manipulate or speak as the avatar that you are holding
- there needs to be a way to "release" the avatar - to leave it on the stage but be no longer holding it (different from deleting it which removes the avatar from the stage)
- the turning icon above the avatar indicates that you are holding it; ideally the frame for scaling would only show when you needed it, rather than all the time, as this would be a bit disturbing visually for the players - need to work out how to do this.

one question - how can we know which avatars on the stage are held by other players? there needs to be some way to indicate that an avatar is held by another player (maybe a version of the rotating icon?)

**Comment by vickis** [comment]
perhaps the icon could be yellow to indicate you are holding it (and all
others are another colour ... blue?/grey?)

this will show when there are multiples of one avatar on stage which one is
actually yours ;)

**Comment by helenvarley** [comment]
i'm wondering if it would also be useful to reinstate the Mirror feature - that somewhere (maybe top left corner?) it can show the image and name of the avatar when you are holding one? otherwise it's not so easy to know the name - you have to do the right click and go to change the name, but i think even there it doesn't show the name; so you don't know until you actual say something ...

**Comment by paul-rohrlach** [comment]
I like the idea of having your currently selected avatar have a coloured icon and avatars selected by other players having a different icon.

I think perhaps we could raise a separate issue to have the name of the avatar (and perhaps other details) appear as a tooltip when hovering over the icon above an avatar?

**Comment by helenvarley** [comment]
https://github.com/upstage-org/mobilise/issues/225

**Comment by vickis** [comment]
Cool thanks hen - maybe it’s not as tricky as I thought to do this ;)

**Comment by nguyenhongphat0** [comment]
I rolled the latest code on app1. Now an avatar can only be controlled by 1 person at a time 👍

**Comment by helenvarley** [comment]
great! i will try to check this out ... altho i guess i'll need to be on there at the same time as someone else to test it :rofl:

**Comment by paul-rohrlach** [comment]
Any update on this @helenvarley

**Comment by vickis** [comment]
it appears to be working as requested
also so is the tooltip! eg who is holding the av and the name

fyi the name appears as grey text when you go to change it :)

**Comment by helenvarley** [comment]
yes this appears to be working as it should be now :)  i have not yet had the opportunity to test it with others on the same stage, i don't know if anyone else has. but we will soon find out if there are any issues when multiple players are on the stage ... for now it is fixed.
