### ISSUE TITLE
Objects on Stage behind or in front of other objects 

### ISSUE THREAD

**Issue by elisadcg** [upstage-org/mobilise#221]
Actually it seem that objects text can't be behind props or avatar.
Avatar can't be behind props.
Props can't be behind text.
Props can't be behind avatar.
And whathever if you put prop, avatar or text first or last.

**Comment by nguyenhongphat0** [comment]
My bad. Fixing... 😅

**Comment by elisadcg** [comment]
Good it works now ! Many thanks
