### ISSUE TITLE
tooltip for avatar details

### ISSUE THREAD

**Issue by helenvarley** [upstage-org/mobilise#225]
It would be nice to have a tooltip when you hover your mouse over the "holding" icon above an avatar, that would show information including:
- name of avatar
- name of player holding the avatar
- something else?

Note: what happens when the avatar is at the top of the screen? does the holding icon show below the avatar?

**Comment by paul-rohrlach** [comment]
This will need a little design tweaking first - But I imagine it's fairly straightforward to implement.

**Comment by vickis** [comment]
I would see this as a great ‘nice to have’
- good documentation and training will help with tool use
Generally you will be working in groups and be able to communicate about
things like who has which av
But useful to check
:)

**Comment by paul-rohrlach** [comment]
I believe this has been done.

**Comment by helenvarley** [comment]
yes it has been done, altho i find it difficult to read as it is revolving. might be better just static. but this is not urgent.

**Comment by elisadcg** [comment]
I confirm, it's very difficult to read
![tooltipavatar](https://user-images.githubusercontent.com/7611913/114678277-620aad00-9d0b-11eb-8450-87c4e02fbf62.gif)
I suggest non animated this tooltip

**Comment by nguyenhongphat0** [comment]
Should we non animated the icon as well 😅

**Comment by vickis** [comment]
if the  tool tip is attached to the icon then not animating both is best
for readability :)
