### ISSUE TITLE
Terms of Service

### ISSUE THREAD

**Issue by paul-rohrlach** [upstage-org/mobilise#230]
Provide a "Terms of Service" document that is accessible via a URL.

**Comment by paul-rohrlach** [comment]
Relates to #6

**Comment by helenvarley** [comment]
great - i've made a note of this on OpenProject too - in the forums i've made a section for our sustainability plan & included a link back to this issue.

**Comment by nguyenhongphat0** [comment]
Can we open an popup when click on `Terms of Service` instead of open an url, Paul?

**Comment by paul-rohrlach** [comment]
Yeah, we can.  But the content needs to be easily configurable.

**Comment by paul-rohrlach** [comment]
Sounds reasonable

**Comment by paul-rohrlach** [comment]
@nguyenhongphat0 are you done with implementation here?

**Comment by nguyenhongphat0** [comment]
There is a checkbox in the Register form and a link on Login form on app1 already. But there is no Terms of Service inside the modal

**Comment by nguyenhongphat0** [comment]
<img width="1399" alt="Screenshot 2021-04-07 at 23 43 46" src="https://user-images.githubusercontent.com/29925961/113903362-19c72880-97fb-11eb-8d21-aa6dd4b72559.png">

**Comment by paul-rohrlach** [comment]
Can we perhaps have the implementation changed such that it's capable of pulling a markdown file from a URL rather than referencing a file inside the repo?

The reason being, that we'd like to host the ToS on the website and be able to update it independently of the code as well as use it elsewhere too.

**Comment by nguyenhongphat0** [comment]
If we already have the terms as a webpage , I suggest using <iframe> to show it inside the modal. Else if it's a raw markdown file, as long as we can fetch it using API request, it's can be display like inside the repository

**Comment by paul-rohrlach** [comment]
Yeah, the reason I think we should keep it as a Markdown file is that we can theme it independently of where it's being loaded.  This means that it will never look out of place.  If we use an iframe, it needs its own CSS, etc. and means that it may not always look like it fits in properly.

**Comment by nguyenhongphat0** [comment]
Right! And another issue with <iframe> is the entire header/footer of the webpage also display inside the Term of Service popup 🤣

**Comment by nguyenhongphat0** [comment]
Hi @paul-rohrlach , this is the last open issue on R1-2021 milestone. Let me know what I should do to get this issue closed, thank you 🙏

**Comment by paul-rohrlach** [comment]
🥳 !!!

So yeah, I think we should change the ToS pop-up to load a markdown file from a URL and then that's this issue done (except for actually writing the ToS).

**Comment by helenvarley** [comment]
Lorem Ipsilum ...? :laughing:

**Comment by paul-rohrlach** [comment]
For now, yes.  But we do actually need to write this at some point 😆

**Comment by nguyenhongphat0** [comment]
>  I think we should change the ToS pop-up to load a markdown file from a URL

We already have this 😅 The popup currently load the markdown from https://raw.githubusercontent.com/upstage-org/documentation/master/README.md. Let me know if I should change the URL to something else

<img width="798" alt="Screenshot 2021-04-11 at 23 43 01" src="https://user-images.githubusercontent.com/29925961/114313175-a89bb400-9b1f-11eb-895c-f91f25bd6ea7.png">

**Comment by paul-rohrlach** [comment]
Oh damn!  I totally missed that.

Okay, so.  Revised notes:

This URL should be configurable by admins

**Comment by nguyenhongphat0** [comment]
Admin can now change this URL inside `System Configurations` 🎉 

<img width="1318" alt="Screenshot 2021-04-12 at 18 43 13" src="https://user-images.githubusercontent.com/29925961/114389244-f9161e80-9bbe-11eb-9a86-22d62abab8fb.png">

**Comment by helenvarley** [comment]
OK so now i'm getting confused with "terms of service" and "privacy policy" - the privacy policy (https://github.com/upstage-org/mobilise/wiki/Privacy-Policy) is what i sent to our EU project officer for feedback, 6 weeks ago. i've just emailed her again to ask if she has any feedback.
but the privacy policy isn't the same as the ToS, is it? we need both? or we can combine the two into one document??

**Comment by paul-rohrlach** [comment]
We're supposed to have both.  But we can make it the same document.
