### ISSUE TITLE
on stage media slider not working

### ISSUE THREAD

**Issue by helenvarley** [upstage-org/mobilise#234]
the slider (for opacity, animation & move speed) disappears before i can adjust it.
it appears when i select the avatar or prop; it is visible when i hover the cursor over it, and the cursor becomes a finger.
as soon as i click to hold and drag the handle, the slider and frame disappear as if i have clicked away from the avatar or prop.

**Comment by nguyenhongphat0** [comment]
Sorry about this, there was many impact after #219 . I fixed the drawing/text not appears issue as well

**Comment by helenvarley** [comment]
great, seems to be fixed now so i will close this bug. thanks!
