### ISSUE TITLE
"abandoned" avatar ...

### ISSUE THREAD

**Issue by helenvarley** [upstage-org/mobilise#235]
i placed an avatar on the stage, and by default i was holding it. i refreshed the stage, the avatar was still there on the stage, but i am unable to hold it. however, when i hover over the holding icon, it says the avatar is held by me. but i can't do anything with it, i can't release it or delete it from the stage.
previously we had an on-stage button that we called "clear", which removed all un-held avatars from the stage. this would be good to have, but i don't know if it would solve this problem as UpStage still thinks this avatar is held.
i took put avatar on stage, and this is also showing as being held by me. it should not be possible for one player to hold more than one avatar at a time.
i reloaded the stage a second time to see if i could end up holding three avatars, but this time the avatars have not appeared on the stage at all, only a prop which was the last thing i put onto the stage.

**Comment by elisadcg** [comment]
I notice too that when you unhold an avatar, each next you touch, is becoming your holding avatar.

**Comment by helenvarley** [comment]
it shouldn't work like that - you should double-click the avatar, or hold it from the context menu. 
is it too easy to accidentally double-click?

**Comment by elisadcg** [comment]
![handle-dehandle-avatar](https://user-images.githubusercontent.com/7611913/113871997-bf56a980-97b3-11eb-8325-efa5bcdfad26.gif)
i am just clicking not double cliking

**Comment by helenvarley** [comment]
definitely not how it should be! it should be a double-click, that was how it was just before ...

**Comment by nguyenhongphat0** [comment]
Jeez, I thought the double click would make you feel "clumsy", so I auto set as your avatar at the moment you drag it.  #237 will take the double click back for you 😅

**Comment by paul-rohrlach** [comment]
Just to be clear
> i placed an avatar on the stage, and by default i was holding it.

This was agreed upon during the last meeting.

**Comment by helenvarley** [comment]
yes, when you place an avatar on the stage you should be holding it by default, and no-one else can hold it until you release it.
you should be able to hold a different av that is already on the stage, as long as no other player is already holding it, by double-clicking on it. this seems to be working again now :)
BUT the problem that i opened this issue about is still there: if i'm holding an avatar and refresh the stage, when i come back on the stage the avatar that i was holding tells me that i am holding it, but i am not, and i can't. we need a solution for this ...
when you leave the stage for any reason - refreshing it, internet disruption, whatever - the avatar you were holding (if you were holding one) should remain on the stage but be "released", so that either you can hold it again when you come back in, or someone else can hold it (e.g. if your internet connection goes down in the middle of a show, another player can take your avatar)

**Comment by nguyenhongphat0** [comment]
> if i'm holding an avatar and refresh the stage, when i come back on the stage the avatar that i was holding tells me that i am holding it, but i am not

Yes, because it was another Helen 😆
We can solve this by merging multiple session of one user into one, as a draw back, if you join a stage in multiple browser/tab, the counter only show 1, and your sessions can steal each other avatar (like it used to be before)

**Comment by helenvarley** [comment]
would it be better to make it impossible to join the same stage from another browser tab (or another browser)? a player should be logged in to a stage only once.

what could be useful is that if you try to join the same stage from another tab or browser, you enter as audience - would this be possible? that way you can see how things are appearing for audience if you want to test it ...

**Comment by helenvarley** [comment]
i've attached the bug label to this issue & the R1 milestone, as what needs to be fixed is:
- if a player is holding an avatar and leaves the stage for any reason, the avatar needs to be released. this way, another player can do something with it, or when the player returns, they can hold it again. at the moment, if a player is holding an avatar then leaves the stage, the avatar is still on the stage but no-one can hold it, remove it or do anything with it.

**Comment by nguyenhongphat0** [comment]
Hello everyone, I just rolled the fix on app1, let me know if we can close this issue 🚀

**Comment by helenvarley** [comment]
nope! i just refreshed a stage, and the avatar i was holding before refreshing is now showing as being held by someone else, so i can't hold it or remove it :(

**Comment by helenvarley** [comment]
actually this is a bit inconsistent. now i find that, if i have more than one avatar on the stage, when i reload only the last one that i was holding is still there, and i am still holding it.
but the "release this avatar" action on the context menu doesn't appear to work - the revolving icon stays red, i am still holding it despite clicking on "release this avatar"
& when i refreshed the stage, i am still holding the avatar i had tried to release ... :thinking:

**Comment by nguyenhongphat0** [comment]
You should do a fresh reload (Ctrl+F5) before test it, Helen

> nope! i just refreshed a stage, and the avatar i was holding before refreshing is now showing as being held by someone else, so i can't hold it or remove it :(

This look like the result of the old code

**Comment by helenvarley** [comment]
i was doing a refreshed reload ... now when i reload, i am still holding the av that is on stage. but none of the other media is there. this is another problem ... i think we already have an issue for that ...

**Comment by nguyenhongphat0** [comment]
I thought we already have that issue: https://github.com/upstage-org/mobilise/issues/210

**Comment by helenvarley** [comment]
yes, that's it :)
