### ISSUE TITLE
scene transitions or "curtain"

### ISSUE THREAD

**Issue by helenvarley** [upstage-org/mobilise#244]
this is a feature request: to have a "curtain" that can be used for scene transitions, in conjunction with the Scene tool but also if you need to make a change spontaneously.
We could start with two options, to see how it can function:
- fade through black
- cross dissolve

if you are using it in conjunction with Scenes, to change to a pre-set setting for a new Scene, then it would function as a "transition" and could be selected in the Scene toolbar.

If you are using it separately to Scenes it would function as a "curtain", the same as drawing a curtain across the stage of a physical theatre: the audience cannot see through it, but the players behind the curtain can be preparing a scene.

**Comment by elisadcg** [comment]
i recommand that this option is available in the Stage Management page under the submenu Scene and the option for wich transition and if yes or not.

**Comment by vickis** [comment]
agree - an interesting nice to have ;)

**Comment by helenvarley** [comment]
yes i think it's fine that for the scenes, the transition can be set beforehand & the same option for all scenes in a performance (we can get fancier later if necessary)

for the "curtain" it would be good to have it as something we can do on the stage, at any time. maybe it needs to be separated from scene transition?

**Comment by elisadcg** [comment]
If curtain has to be available at any time we can add it on the toolbox.
Or as it's cover all the stage, add it as a backdrop. But this backdrop have to be always on top of all ?

**Comment by helenvarley** [comment]
it can't function just like a backdrop that is on top, because the players still need to be able to see the stage. it's a curtain for the audience.

**Comment by vickis** [comment]
The ‘curtain’ would need to differentiate players from audience
Players still see all tools and actions audience see
1. nothing (a colour field perhaps)
2.image of an actual curtain
3. An image that relates to the performance (eg in the moments before the
action begins

The curtain acts as a veil for audience only

**Comment by elisadcg** [comment]
Ok so here my suggestion :
option 1 : Curtain is a option available since the scene button
![244-curtain01](https://user-images.githubusercontent.com/7611913/114141998-a4e71200-9912-11eb-90a6-9cf69a810fb4.png)
option 2 : Curtain is a tool on the toolbox, always clickable
![244-curtain02](https://user-images.githubusercontent.com/7611913/114142011-a87a9900-9912-11eb-8aa4-ef74da2bc9a6.png)
Both solution : the behaviour of the curtain is defined on the BackStage/stage management.

**Comment by helenvarley** [comment]
i think i prefer 2; & i think it's fine that the curtain behaviour is defined Backstage - we should start with the simplest idea and then see how it works, before we get too fancy!

**Comment by vickis** [comment]
agree :) one click action (eventually what the curtain is for a specific
show might be possible in manage stages

**Comment by riadsalameh** [comment]
Option for curtains icons 

![Curtains](https://user-images.githubusercontent.com/71765608/114194413-c0bcd900-994f-11eb-9301-94f51056c0bd.jpg)

**Comment by paul-rohrlach** [comment]
Adding this to the backlog of R2-2021

**Comment by helenvarley** [comment]
looking at the curtain icons - i think i prefer the first, but i don't know why :)

**Comment by helenvarley** [comment]
important: the audience sees the curtain; players can see what they are arranging on the stage behind the curtain.

**Comment by helenvarley** [comment]
and the artists could upload image as curtain (another type of media)

**Comment by nguyenhongphat0** [comment]
Hi @elisadcg , can you send me the svg icon of the green curtain 🙏

**Comment by elisadcg** [comment]
i put it on slack

**Comment by helenvarley** [comment]
a sudden thought: can it be possible for the chat to be shown on top of the curtain? this will be really nice for the audience, to be able to chat together before the show, as you would at the theatre when waiting for the curtain to open. if there is no chat, the audience will individually feel very isolated and alone ...

**Comment by helenvarley** [comment]
ignore that! just realised you are as usual way ahead of me! :laughing:

**Comment by vickis** [comment]
That already happens :)

**Comment by nguyenhongphat0** [comment]
Yup I put the curtain below the chat because I hope they won't feel lonely. I've been there 😂

**Comment by vickis** [comment]
Aaawwww
