### ISSUE TITLE
chat: persistence and clearing

### ISSUE THREAD

**Issue by helenvarley** [upstage-org/mobilise#245]
text entered into the chat window of a stage should persist until it is cleared. this means that when i enter a stage for the first time, i can see chat that has already been written.
there is a "clear chat" button in the manage stage interface; this button removes all chat so that when i enter the stage again, the chat window is empty. for example this would be done before a live performance, to remove any rehearsal chat that the audience should not see.

there also needs to be a "save chat" button. this would save all the chat text as a text document that can be stored as part of that stage's documentation and statistics, and viewed and downloaded by players who have access to that stage. this button can be on the manage stage interface, so that you could save the chat text and then clear the chat.

**Comment by vickis** [comment]
agree :)

**Comment by nguyenhongphat0** [comment]
Can we merge the Sweep Stage and Clear Chat inside one button? Here is the reason:
- It's technically easier
- After you sweep stage, the performance will be saved inside a "record", when you replay a record the stage and chat be replay together, so there is no reason to separate them (in my opinion)

<img width="1062" alt="Screenshot 2021-04-20 at 15 00 45" src="https://user-images.githubusercontent.com/29925961/115359895-4f9be200-a1e9-11eb-8239-9c2261d7dd63.png">

**Comment by helenvarley** [comment]
there could be reasons for wanting to clear the chat without sweeping the stage ...

**Comment by helenvarley** [comment]
it's a bit hard to know until we have the "scene" feature, but often in the past we have cleared the chat just before a performance begins in order to have it clean for the public, but we have wanted to keep things on the stage.
actually, when we have the private player chat (#32) we could use that during rehearsals & prep to keep the publicly visible chat clean.
we could try having one button that is "sweep stage", which would remove all media and chat, & see how it works ... what do you think, @vickis ?

**Comment by helenvarley** [comment]
this issue is partially done, but we still need:

- [ ] separate "sweep stage" and "clear chat" buttons (issue #372 )
- [ ] a "save chat" button to allow you to export the chat as a text file
- [ ] after clearing chat, it should disappear not only from the stage but also from the chat screen in stage management
- [ ] in the chat screen on the stage management part of backstage, it would be helpful to have the chat separated into sessions, or by date/time - is that possible? (is that a new issue?)

**Comment by vickis** [comment]
Agree time stamp for chat will be useful :)

**Comment by nguyenhongphat0** [comment]
Okay we can now Save the chat to a txt file, using these Save Chat or Save All Chat buttons. However you cannot make text bold or italic in plain text file, so it might be tricky to know who is player and who is audience, here is examples: 

[[Chat] Demo Stage (a day ago - 25 days ago).txt](https://github.com/upstage-org/mobilise/files/6725924/Chat.Demo.Stage.a.day.ago.-.25.days.ago.txt)
[[Chat] gloria_test.txt](https://github.com/upstage-org/mobilise/files/6725917/Chat.gloria_test.txt)

Chat messages now put into tabs, each time you Clear chat, the current tab will be empty, just like the on stage chatbox, and a new tab will be generated, which allows you to see chats from previous performances 🙌 

<img width="1374" alt="Screenshot 2021-06-28 at 18 37 08" src="https://user-images.githubusercontent.com/29925961/123630543-da2f3c00-d83f-11eb-92ed-5045c772c31d.png">

<img width="1374" alt="Screenshot 2021-06-28 at 18 35 13" src="https://user-images.githubusercontent.com/29925961/123630364-a18f6280-d83f-11eb-8ce4-3d143d3ac36c.png">

**Comment by helenvarley** [comment]
great! :) & we are used to relatively unformatted chat logs, it's fine. the words are there, that's what's important :+1:

**Comment by helenvarley** [comment]
great! can we ask for some more enhancements?
- instead of 1 day ago, 2 days ago etc, can it have the date?
- when you save the chat, can the date also be saved at the beginning of the file?
- when i hit "clear chat", it created a new blank tab called "now"; the other older tabs and chats are still there. what's going to happen when there are 20, 30, 50 tabs? this will not be manageable with tabs ... could there be a tab for the current chat, and a tab for archived chats, which are a list of dates and you click on the date to get the chat?

**Comment by nguyenhongphat0** [comment]
> what's going to happen when there are 20, 30, 50 tabs?

I will show a scroll bar, so that you can see all of the tabs (screenshot). A tab and a list together is not going to be more convince, I think 🤔 

<img width="1050" alt="Screenshot 2021-06-30 at 14 51 33" src="https://user-images.githubusercontent.com/29925961/123922923-b6d8ce00-d9b2-11eb-982e-a3d972bede6e.png">

**Comment by nguyenhongphat0** [comment]
> when you save the chat, can the date also be saved at the beginning of the file?

Let me know if this naming format look good to you: `[Chat] Demo Stage (2021-06-30).txt` 👌

**Comment by vickis** [comment]
that's great for file name :)

the scroll bar makes sense too
can there be a facility to delete early recordings? - after you archive
them elsewhere

**Comment by helenvarley** [comment]
yes that looks great phat :)
& agree, would be good to be able to delete or at least archive chats. as you can see it will quickly become a lot!

**Comment by nguyenhongphat0** [comment]
Yes it should be part of #330, let resolve this issue for now 👌

**Comment by helenvarley** [comment]
actually could we not have the chats displayed in a similar format to the recordings?
- a list going down the page (instead of scroll bar across)
- chronological with most recent first, at top (recordings is currently showing oldest first, would be better the other way)
- then it could show both the date and xx days ago
- icon / link to download chat 
- icon / link to view chat
- icon / link to archive (or delete?) chat

**Comment by nguyenhongphat0** [comment]
Are you sure this is what you want? It takes you an extra step to actually see the chats 🤔 

<img width="1400" alt="Screenshot 2021-07-02 at 00 45 28" src="https://user-images.githubusercontent.com/29925961/124168097-e2e97180-dace-11eb-85c1-1ff872c6c41a.png">

<img width="1400" alt="Screenshot 2021-07-02 at 00 45 54" src="https://user-images.githubusercontent.com/29925961/124168128-e977e900-dace-11eb-9c95-72e479956fb8.png">
