### ISSUE TITLE
stage management menu

### ISSUE THREAD

**Issue by helenvarley** [upstage-org/mobilise#248]
whenever i go to stage management (e.g. https://app1.upstage.org.nz/V4.0/ui/dashboard/stage-management/U3RhZ2U6Mw==/) to add media to my stage, i intuitively try to click on the media type options that are visible as part of the "scenes" submenu. 
can this submenu only appear when you first click on scenes?
& maybe it also makes sense to have it the same as the media interface - that the media types are a dropdown, rather than items in the menu?

and it would be great to have a link to enter the stage directly from the stage management interface.

**Comment by vickis** [comment]
Agree on enter stage link
And drop down as with media management :)

**Comment by elisadcg** [comment]
So what do you prefer is : collapse scene submenu (wich is actually under construction and add a subsubmenu to Media
![248-mediamenu03](https://user-images.githubusercontent.com/7611913/114147279-d7940900-9918-11eb-99d0-f109fc2af615.png)
Here wireframe of new model : 
![248-mediamenu04](https://user-images.githubusercontent.com/7611913/114147439-fdb9a900-9918-11eb-86b6-dbecac7c5c3a.png)

**Comment by helenvarley** [comment]
yes, this looks good! & to be consistent is good :)

**Comment by vickis** [comment]
agree - great :)
