### ISSUE TITLE
chat text repeated multiple times

### ISSUE THREAD

**Issue by helenvarley** [upstage-org/mobilise#251]
one of the testers has reported her chat comment appearing multiple times when she had only entered it once:
![image](https://user-images.githubusercontent.com/3437324/114161358-3f058500-9928-11eb-88e2-2cc1c33fe1f5.png)

**Comment by nguyenhongphat0** [comment]
I just learned that this is a behaviour of mqtt when connection restarted: https://stackoverflow.com/questions/38281667/mqtt-client-repeating-last-message-when-restarted

Maybe Suzon is having a weak connection to the broker. But there is an easy way to fix this: I will manually detect duplicated message and prevent them from showing 👌

**Comment by nguyenhongphat0** [comment]
I believe that this issue is resolved. You can test it by manually turn off the wifi and turn on again 👌

**Comment by helenvarley** [comment]
i can't replicate the bug :)
