### ISSUE TITLE
unable to select avatar after releasing it

### ISSUE THREAD

**Issue by helenvarley** [upstage-org/mobilise#253]
i placed an avatar on stage and by default i am holding it.
then from the context menu i selected "release this avatar"
now i am not holding the avatar any more - this is what should happen :)
BUT
i am not able to re-select it at all. i can't do anything with it, delete it or hold it.

**Comment by nguyenhongphat0** [comment]
Told ya 🤣 https://github.com/upstage-org/mobilise/issues/235#issuecomment-815028298

**Comment by helenvarley** [comment]
sometimes i'm just very stupid!! :rofl:
