### ISSUE TITLE
backdrop opacity

### ISSUE THREAD

**Issue by helenvarley** [upstage-org/mobilise#259]
can there be a tool by the icon of a backdrop, that would allow players to:

- adjust opacity of the backdrop
- select whether the backdrop appears at full or reduced opacity when it is placed on the stage.

example: i want to fade in a backdrop from nothing. before selecting it, i reduce its opacity to zero, then select it so that it "appears" on the stage, but it's invisible because it's at zero. then i slowly move the opacity slider up to full opacity to make the image fade in.

i guess we will need some icons for this :)

**Comment by vickis** [comment]
yes a great to have :)
previously we would fade out and delete a colour overlay in front of the
backdrop
the 'publish' option we discussed earlier would enable something like a
backdrop to be selected and we are then able to manipulate it before it is
publically viewable

**Comment by elisadcg** [comment]
I suggest a slider below the backdrop in the overlay
![259-opacity-backdrop](https://user-images.githubusercontent.com/7611913/114676861-07bd1c80-9d0a-11eb-8a95-a89f3beac01a.png)

**Comment by vickis** [comment]
If we are hang tge opacity other backdrop we will also need to be able to
select background  colour - this would be in the stage management

**Comment by elisadcg** [comment]
yes in a new subsection about Theme wich allow choose the color of the background
and maybe the position of the chat too ?
![250-themeManagement](https://user-images.githubusercontent.com/7611913/114827901-89c04a80-9dc9-11eb-8e96-dcad058936b8.png)

**Comment by nguyenhongphat0** [comment]
This wireframe is very clear, thank you @elisadcg

**Comment by vickis** [comment]
yes great Elisa :)

**Comment by helenvarley** [comment]
actually it would be really cool if you could change the stage background colour on stage in real time as well ... ?

**Comment by nguyenhongphat0** [comment]
Right click on backdrop will give you a slider that can change backdrop opacity 👍 
<img width="1310" alt="backdrop opacity" src="https://user-images.githubusercontent.com/29925961/126291887-40b8b43a-90f4-41de-a372-8a9a82b43b91.png">

**Comment by vickis** [comment]
super!
