### ISSUE TITLE
Dashboard: layout of stage list interface

### ISSUE THREAD

**Issue by helenvarley** [upstage-org/mobilise#26]
as a logged in player, i expect to be able to see a list of stages that includes information such as:
- the access i have to each stage (e.g. audience, player, owner)
- a counter showing the numbers of players and audience currently on that stage
- date of creation
- date last used / accessed
and possibly other information such as when the stage was last used, or if a public performance has been announced to happen on that stage.

**Comment by helenvarley** [comment]
this is connected to #101.
this should be a table or list. "my stages" should be the default view or first list. "my stages" are the stages that this player has either created or been given access to. 

the list should include:
- name of stage (click on name to enter stage)
- buttons to edt/manage, clone/duplicate, and delete (do we also need a button to enter, if the stage name is a link to enter?)
- buttons to access chat log and (if we have the feature) screen recordings

is it useful to also have here the date the stage was created and by whom? this might be helpful in the list of other stages, for admin purposes e.g. deleting old stages. 

i think it's not necessary to have thumbnails here - this is in the dashboard, so about admin & being able to quickly find what you want - which will normally be your own current stage. how should the list be sorted - alphabetically by stage name? chronologically by date created? chronologically by most recently active? possible to sort by these things?

**Comment by elisadcg** [comment]
Wireframe of your idea

![wireframe-stagemanage](https://user-images.githubusercontent.com/7611913/103772919-909d2b80-502a-11eb-8834-99efa37ca406.png)

**Comment by helenvarley** [comment]
yes there needs to be a button at the top to create a new stage (phat has done this in the demo stage (http://159.89.19.111/V4.0/ui/dashboard - but i don't think things are working yet)

**Comment by helenvarley** [comment]
On this screen there should be a link to enter the stage
![Screenshot at 2021-03-28 12-04-38](https://user-images.githubusercontent.com/3437324/112748724-01b30600-8fbe-11eb-93d1-23c83844bcf9.png)

**Comment by helenvarley** [comment]
Currently the default display of "my stages" shows only the stages i have actually created myself; it should also show any stages that i have player access (or player and edit access) to, as many players don't create the stages themselves but are players on them. you want to always see the stages that you need access to, and this is often a stage that you are a player on but haven't created yourself. 
@nguyenhongphat0 is this possible?

**Comment by nguyenhongphat0** [comment]
Yes it's is possible. And do you need a dropdown to filter stages by "Player access" 🤔

**Comment by helenvarley** [comment]
:thinking:  i'm not sure - the most important thing is to be able to easily find the stages that i want to work on. as long as the stages are shown chronologically, with most recent first, it should be enough (and/or options to sort ascending / descending). 
@vickis what do you think, would it be useful to have a "player access" filter as well?

**Comment by vickis** [comment]
yes player access filter could be useful as more people are creating stages
(especially rehearsal spaces)

**Comment by helenvarley** [comment]
it's a bit confusing that the "Access" column comes immediately after the "Owner" column, as at a glance it can look like this is the role of the player whose name is in the "owner" column. it would make more sense if the "Access" column was just before the "Enter" button, or between "statistics" and "manage".

and, i think the "Details" pop-up is redundant. either it needs to be more useful/functional, or else we don't need it at all. the buttons to manage, duplicate or delete, and the statistics, are already there in the stages list. is it useful to have the pop-up showing the players for that stage? i don't know ... ???

![backstage_stages](https://user-images.githubusercontent.com/3437324/125894992-f16297b7-f7c0-47e1-b659-83e77f82deb8.png)

**Comment by nguyenhongphat0** [comment]
Well these detail "eyes" was created a very long time ago (before the stage even existed 😆) I can't remember how many time I ever clicked on those, maybe 1 or 2. Removing it should be better since necessary information is already there, and we can enter the stage to see the "detail" 👍

**Comment by vickis** [comment]
Agree it can be removed :)
