### ISSUE TITLE
context menu enhancements

### ISSUE THREAD

**Issue by helenvarley** [upstage-org/mobilise#260]
the context menu can be improved:

- about a quarter of the area of the context menu is unused - upper right-hand area. can the layout be changed to utilise this area, and/or make the size of the menu overall smaller?
- it would be great if the menu was semi-transparent, so that we can see what's happening behind. this is important particularly for selecting different frames of a multiframe av, to be sure that you have selected the right frame. but also there could be other activity and speech bubbles continuing by other players while you are looking at the context menu, so it would be good to be aware of this.
- the slider options take up a lot of space; could there be icons and tool-tips instead?
- the multiframe avatar icons are too small, for example dave's position is similar but his facial expression differs a lot, and i can't distinguish in these icons.
- space can also be released by reducing the text: "release avatar" instead of "release this avatar" - or maybe even just "release", since it can't relate to any other object; and "change your nickname" could just be "nickname"
- "bring forward" and "send back" would be clearer, as - i think - it does not bring the avatar all the way forward or back, just one step at a time? should there be 4 options? e.g. bring forward, bring to front, send back, send to back (as in the "arrange" menu in graphics apps).

![Screenshot at 2021-04-10 16-36-33](https://user-images.githubusercontent.com/3437324/114273728-8e78ad80-9a1b-11eb-9197-fae204f73596.png)

**Comment by vickis** [comment]
agree transparency of the context menu would be useful
otherwise i am fine with it :)

**Comment by elisadcg** [comment]
opacity or new context menu, always appear, no more right clic
![260-context-menu](https://user-images.githubusercontent.com/7611913/114678001-1d7f1180-9d0b-11eb-9742-73fc37358de7.png)

**Comment by vickis** [comment]
I prefer the context menu to be on right click
I think Performing with the Menu frame constantly active would be
distracting

**Comment by helenvarley** [comment]
requests from meeting on 29 april:

- [ ] mak context menu semi-transparent
- [ ] develop icons for the slider options (with tool-tips)
- [ ] reduce text wherever possible e.g.:
- [ ] "release this avatar" can be just "release"
- [ ] "bring to front" can be "bring forward" (because actually it should not immediately come to the front, it should move forward step by step between whatever other media is around it on the stage)
- [ ] "send to back" can be "send back"
- [ ] "change your nickname" can be "nickname" or maybe "avatar name" is better, since a player also has their own player name and this is changing the avatar name but not the player name
- [ ] rotation can be removed as we have the handle to do it now
- [ ] slider - icons

things to add to the context menu:

- [ ] horizontal & vertical flip?
- [ ] anything else?

**Comment by helenvarley** [comment]
@nguyenhongphat0 - just realised that you were not assigned to this issue, i don't know why ...

**Comment by nguyenhongphat0** [comment]
> make context menu semi-transparent

Should this transparent level is enough 🤔 

<img width="679" alt="Screenshot 2021-06-01 at 01 24 46" src="https://user-images.githubusercontent.com/29925961/120229812-28204680-c278-11eb-8c52-9227efb600f1.png">

**Comment by vickis** [comment]
Looks great :)

**Comment by helenvarley** [comment]
yes, that should be transparent enough - & looks great with the icons! are there tool tips when you hover over the icons? might be helpful ...

**Comment by nguyenhongphat0** [comment]
Yes hovering on icon will show tooltip 👌
