### ISSUE TITLE
media display on stage management interface

### ISSUE THREAD

**Issue by helenvarley** [upstage-org/mobilise#273]
it is already very difficult to find media on the stage management interface (eg https://app1.upstage.org.nz/V4.0/ui/dashboard/stage-management/U3RhZ2U6Mw==/media). there needs to be improvements to the interface:
- image icons can be smaller, and it would help if they were consistent sizes; sometimes there are 3 in a row, sometimes 4, and some are longer or shorter so it looks very messy.
- there could be an option to display media as a text list, rather than as icons, with a thumbnail appearing on mouse-over, or as a small pop-up on click. 
- option to select media uploaded by a specific player: this can be another dropdown menu next to the media type dropdown, so that you can select all avatars uploaded by a particular player.
- default display to include only media that you have uploaded (as with the stages list)

**Comment by vickis** [comment]
Agree management of media needs useful filters,
Listing can be text but should include ability to view

**Comment by helenvarley** [comment]
now that we have the media type available in the lefthand menu, can the dropdown filter be changed to player? this way we can select the media type in the lefthand menu and then filter to show media from a specific player. 
it could also be that it shows only your media by default, & then the dropdown gives the opportunity to show all players or specific player(s) - the same as on the stages page. (with option to hold ctrl key down to select multiple players)
![Screenshot at 2021-05-18 12-39-50](https://user-images.githubusercontent.com/3437324/118637785-76dcd380-b7d6-11eb-9d6e-c810d75792f2.png)
