### ISSUE TITLE
Backstage - new name for the dashboard

### ISSUE THREAD

**Issue by helenvarley** [upstage-org/mobilise#274]
recently we decided to use the term "Backstage" instead of "Dashboard", to refer to all of the adminitrative / management part - basically everything apart from the live stage. this needs to be applied across the interface and should also be used consistently across all the documentation AND in github as well. i notice that we also still have a "workshop" label, which is the term previously used for this area. @paul-rohrlach is it ok if i change the Dashboard label to Backstage, and can we merge it with the old workshop label?

In the Backstage area you can:
- create new stages and manage existing ones
- upload and manage media
- edit player profile
- admin tools e.g. player registration approval

the navigation along the top of the Backstage interface currently lists: Dashboard, Media, New Stage, Profile, Admin
i propose that this be changed to: Stages, Media, Profile, Admin
and that "New Stage" be accessed from the existing "New +" button on the Stages 

the word "Backstage" could be either part of the title in the coloured bar or it could appear above the bar at the left, before the menu items. if it's in the coloured bar, then the text could be as follows for each interface:

Backstage: Stages
Create a new stage, enter or manage an existing stage

Backstage: Media
Upload and manage media

Backstage: Profile
Update your player profile

Backstage: Admin
Manage players and system settings

**Comment by vickis** [comment]
Agree first part - addition of backstage as terminology

Second part seems confusing
You should either go to live stage (as either player or audience)
Or you are backstage (as logged in player) and have access to all tools

**Comment by helenvarley** [comment]
the audience won't be backstage ever, they will get to the live stage from the foyer or from other links.
logged-in players would access the live stage from the "Stages" interface, which would be the same as the current Dashboard interface (https://app1.upstage.org.nz/V4.0/ui/dashboard)

**Comment by elisadcg** [comment]
![issue274](https://user-images.githubusercontent.com/7611913/115367771-c673b380-a1c6-11eb-9f36-46abf871efeb.png)

**Comment by helenvarley** [comment]
great :) does it need to say backstage all the time in the grey bar? if it's in the top left corner and also in the breadcrumbs (Backstage > Admin etc) then it's maybe not necessary also in the bar?

first one should say "Welcome to the Backstage"

**Comment by elisadcg** [comment]
No sure !
