### ISSUE TITLE
audio formats

### ISSUE THREAD

**Issue by helenvarley** [upstage-org/mobilise#276]
the audio formats listed as possible to upload include mp4, which is a video format, and not mp3, which is the most common audio format and should be able to be uploaded:
![Screenshot at 2021-04-19 17-08-54](https://user-images.githubusercontent.com/3437324/115259276-076db880-a132-11eb-8bc2-7cdb30eaee51.png)

**Comment by helenvarley** [comment]
also in this interface, would it not be better to have a dropdown menu for the media type options? we don't need to see them all and only select one. it would leave more space for example to include beng able to assign the media item to stages during upload.

**Comment by nguyenhongphat0** [comment]
This media upload will soon get a re build. Dropdown is good 👌

**Comment by helenvarley** [comment]
we are trying to upload an audio file that is .m4a but it doesn't allow it. i think .m4a is now quite a common format, is it possible to be able to use that as well?

**Comment by vickis** [comment]
great to have - but cross platform formats might be better to get people to
use?

**Comment by helenvarley** [comment]
i've now learned that m4a is indeed a video format; so i'm not sure why the audio file got saved in that format (it was recorded on someone's phone). and i'm not sure why we were able to upload one file in that format and another we could not - maybe a codec thing??
what do you mean by cross platform formats?

at the moment this is listed on the audio upload window: Permitted file formats are .wav,.mpeg,.mp4,.aac,.aacp,.ogg,.webm,.flac.

**Comment by nguyenhongphat0** [comment]
We can upload .mp3 file on devapp1 now, and I also allow .m4a as an audio format. Can we resolve this issue?

**Comment by helenvarley** [comment]
great, worked for me :)
