### ISSUE TITLE
scolling on media bar makes it go back to the foyer page

### ISSUE THREAD

**Issue by helenvarley** [upstage-org/mobilise#277]
eva is using firefox on a mac; she was in the stage and wanted to scroll along the avatar bar to further avatars. the scroll bar was not visible, but when she used two fingers on her trackpad she could scroll.but, when she scrolled to the end, the stage disappeared and she was returned to the foyer page.
she doesn't see the scroll bar at all, only for a few seconds when she uses the two-finger scrolling.
it's the same for all bars (audio etc).

**Comment by nguyenhongphat0** [comment]
Scroll left/right with 2 fingers on Mac's Firefox is a shortcut of "back"/"foward history". It's all page behvior, not only Upstage. She should scroll down/up instead to move the tools

**Comment by nguyenhongphat0** [comment]
It's a firefox feature, but someone already considered it as a bug: https://bugzilla.mozilla.org/show_bug.cgi?id=282140

**Comment by helenvarley** [comment]
ok, interesting! the problem then for us is how to offer another way to scroll in that bar; the horizontal scroll bar did not show at all until eva started doing the two finger horizontal scroll, then it appeared but only for a second before she got thrown back to the foyer page. so there was no possibility for her to move the horizontal scroll bar. 
even if scrolling up and down on the bar will result in it moving horizontally, how are people going to know this? is there some other way that we can provide? i'm adding elisa, riad & vicki to this issue for thoughts. vicki is a mac user so maybe will also encounter this difficulty ...

**Comment by vickis** [comment]
i just use chrome for UpStage
two finger (or multi finger) scrolling or clicking offer many options
swiping can be used to page back and fwd
-so as @phat already pointed out it was operating via the system

i would recommend getting your workshoppers to use other than firefox as
this is currently a known issue :)

**Comment by nguyenhongphat0** [comment]
I don't consider this as a bug. Mac has no explicit scroll bar like Windows or Linux, it only visible when you scrolling. And about scrolling behavior, in a horizontal scroll only content, it's natural to scroll up and down (some mouse can only scroll up and down) to move your horizontal slider.
Another reason is I cannot prevent firefox from navigating the history when you swipe left/right. At least we can put this issue inside #211

**Comment by phat** [comment]
@vickis please tag correct user

**Comment by nguyenhongphat0** [comment]
Wow who is @phat 👀

**Comment by helenvarley** [comment]
wow imagine if we had 2 phats - think what we could achieve! :laughing: 

ok so we need to document it, & suggest that mac users use a browser other than safari. i guess this is not really an issue for audience, as they don't need to horizontal scroll :)

**Comment by helenvarley** [comment]
this is happening again for eva:
"scrolling to the left in the audio or whatever menue, it kicks me out of the stage again. this didn´t happen last time...."
she is using chrome on mac 10.14.6
(could not use firefox today as she can't enter the stage at all with firefox)

**Comment by vickis** [comment]
Is this possibly the smart scroll actions on the tablet which enables
browser page actions on swipe?
Will try and replicate :)

**Comment by helenvarley** [comment]
she was using a computer, not tablet, when this was happening yesterday.

**Comment by nguyenhongphat0** [comment]
This is a Chrome feature, so Mac users will have to turn off themselves. This annoying issue happens to every website, not just UpStage 😆

To turn it off:
1. Open terminal and paste `defaults write com.google.Chrome AppleEnableSwipeNavigateWithScrolls -bool FALSE`, hit enter
<img width="585" alt="Screenshot 2021-09-23 at 21 05 54" src="https://user-images.githubusercontent.com/29925961/134522088-00603cfc-4c27-4065-88c1-16dccc70e0e5.png">

2. Restart Chrome (by pressing Command+Q to quit it entirely, pressing the close button only won't work)

**Comment by helenvarley** [comment]
ok i will tell eva.  we should put this in the documentation somewhere ... trouble-shooting section

**Comment by vickis** [comment]
Thanks Phat certainly one to document :)

**Comment by CBeez23** [comment]
I'll get the basics of the problem and any solutions written down in troubleshooting.

Get Outlook for Android<https://aka.ms/ghei36>
________________________________

**Comment by vickis** [comment]
Good work Claudia :)
Phat has provided a screen grab and solution which will be ideal to use :)

**Comment by helenvarley** [comment]
i copied Phat's answer into the Troubleshooting chapter in the user manual. 
perhaps there needs to be a separate chapter for browser issues, as we also have the firefox configuration instructions which have been put into the Technical chapter near the beginning ... need to think about the logical place for these things.
