### ISSUE TITLE
media without a type

### ISSUE THREAD

**Issue by helenvarley** [upstage-org/mobilise#278]
today some media items got uploaded without a type; the players uploading them were pretty sure that they had selected a type at upload, but once uploaded the media items had no type, and it was not possible to set one via the media edit interface - we tried this and saved it, but it did not work.
if there is no media type, then it's impossible to use the media on stage. so all media must have a type when it is uploaded.

note: it seems like it would be possible to change the type of a media item - at least this appears to be possible in the edit interface. this could potentially be useful, altho i think not often needed.

**Comment by nguyenhongphat0** [comment]
We cannot create a typeless media any more 😅
