### ISSUE TITLE
multiframe backdrop

### ISSUE THREAD

**Issue by helenvarley** [upstage-org/mobilise#279]
as an artist i would like to be able to have multiframe backdrops. this is useful because sometimes there can be a lot of backdrops, & rather than have to have a long bar of backdrop icons i could have similar backdrops together as a multiframe.

i would like to be able to select this option in the upload process, and upload the separate frames at the same time as creating the backdrop.

there needs to be a tool to change which frame of the backdrop is showing. this might not be able to work in the same way as the right-click menu for avatars and props, as it might sometimes be difficult to access the backdrop to click on it - for example if there are many or large avatars or drawings. 
there might be some other tools that we want for the backdrop, such as opacity slider to fade backdrops in & out; so it would be good to think how these functions might be accommodated in the interface ...

**Comment by helenvarley** [comment]
it was me who created this issue, & it's specifically for multiframe backdrops. #259 is backdrop opacity. so they are separate functions, but it does make sense for the tool interface to be thought about together.

**Comment by elisadcg** [comment]
![issue279](https://user-images.githubusercontent.com/7611913/115364898-274dbc80-a1c4-11eb-98ab-2d25c92da350.png)
If multiframe backdrop then i imagine the same icon for annunce that it's multiframe than the avatar or props.
And what about the right click (on the top overlay) display the context menu to adjust speedness.

**Comment by nguyenhongphat0** [comment]
To sum up, we now can:
- Create multiframe backdrop in backstage, I also add a "multi frame preview" in media table:
<img width="952" alt="Screenshot 2021-05-31 at 22 14 20" src="https://user-images.githubusercontent.com/29925961/120213574-90adfa00-c25d-11eb-90c8-47f752e2d7af.png">

- Play the multiframe backdrop, change speed and frame of the backdrop using context menu:
<img width="1095" alt="Screenshot 2021-05-31 at 22 15 17" src="https://user-images.githubusercontent.com/29925961/120213687-b0ddb900-c25d-11eb-88ec-b906a441f8ed.png">

**Comment by vickis** [comment]
great work!
