### ISSUE TITLE
smartphone / tablet experience

### ISSUE THREAD

**Issue by helenvarley** [upstage-org/mobilise#28]
the experience of using/viewing/participating via a mobile or tablet is going to be different to the experience on a computer, therefore it makes sense to think about this & plan the functionality a bit differently, & try not compromise either experience because of the other one. the main differences are size, & the keyboard (i think - any others?)

from an audience perspective, the main issue will be the keyboard. when they want to type in the chat, the keyboard is going to obscure a significant amount of the screen & stage. i would guess that this means audience members participating via mobile/tablet are not going to comment as much as those with a proper keyboard (unless they're using a tablet with a separate keyboard). one possibility to facilitate easier input could be things like emoticons, & the applause button.

from a player perspective, what functions are going to be difficult/easy if using a tablet/phone?

- streaming: if you're using your device to stream, then you're probably not going to be doing anything else on it, as you'll need to be pointing it at whatever you're streaming.
- operating avatars: it might be ok to select and move avatars, but speaking is going to be difficult without a keyboard
- drawing: probably ok?
- audio: probably ok?
- using the workshop interface: might be tricky?

(i've copied the discussion from the limelight repo issue, https://github.com/upstage-org/limelight/issues/171, below)

vicki: 
it should be relatively easily to detect device and deliver accordingly - but it is probable that the users on mobile (small screen) are more likely to be audience
for using all the tools it seems likely the player would be using a laptop
however still a mobile device but with bigger screens are tablets - by the sounds of the size of your laptop hen maybe the screen size could be approaching yours - the only difference might be the keyboard appearing when trying to input text

helen:
my new laptop is 14", the old mac is 13", so at the smaller end of laptops. but plenty of people have small laptops.
what if we decided to make the mobile interface audience only? would that make programming easier, or would it not really make any difference? as vicki says, mobile users are more likely to be audience, apart from perhaps streaming (will that still require the use of another app? in which case it's also fine because currently we can stream from a mobile into UpStage, without needing to be in UpStage on the mobile device).

vicki:
arohamai - i meant audiences on mobile (as in phones)
tablets are another thing - and many are using these instead of laptops (this would include schools which is where i started running into issues with trying to do workshops …
i think it is too limiting to restrict ‘mobile’ to audience only
and its ok hen - size doesn’t matter ;)

helen:
it would be useful to do some early testing then, to work out how we can try to ensure that it isn't a frustrating experience on phones/tablets, & also that whatever modifications are necessary to achieve that don't end up compromising the experience for those on laptops.
i just succeeded in uploading an image from my phone, it works fine. i guess we need to wait for stages to be working on mobile & then see how it is.
@vickis - do the schools usually have keyboards with the tablets, or just use the on-screen keyboard?

vicki:
agree
schools do use a range
now that many have byod (bring your own device) they have everything
most would i think not use keyboards with tablets as a rule
but actually the last few projects in have done with schools have been in the hands on, outside and/or using electronics not in the classroom at all (as such)
agree it would be good to consider all users but to determine what works best for the majority
my internet would be in a space that does not have barriers to access (as in when it was important to have dial up all those years ago
the most ubiquitous tech is now the phone … but are we going to mass ubiquity
or really still a pretty niche product ;)

helen:
ubiquitous & accessible are 2 different things ... we aren't trying to be social media & i think if we did suddenly get hugely audiences then we would have a whole lot of new problems to deal with like paying for our server traffic for one thing!
from my own personal perspective, i don't think i would want to perform from a mobile device. streaming from a phone is one thing, but i don't think i'd even want to watch a performance on my phone. i might watch something on a tablet, but probably only if it wasn't possible for me to use a computer. that's because for me the text interaction is really important, & i think i'd find it really frustrating to not have a proper keyboard.
if you were designing a schools project using Limelight, & it was going to be in & outside the classroom, what kinds of things do you think the kids might want to do on their phones or tablets outside? i'm guessing that it might be mostly gathering live media, e.g. streams & images & sounds, that are being fed into a performance. so could it be that the mobile devices are mostly media gathering, & there would be some players with computers doing the onstage manipulation?
what other ways do you think that Limelight might be used on the go? (apart from audiences watching).

vicki:
off hand interacting between digital and physical space, mapping, motion sensing that kind of thing :)

helen:
can you describe how these might actually happen with limelight? what would the kids actually be doing, how would they be using limelight?

paul:
If I may interject here - Responsive design (more specifically, how we make assumptions on the device) is a bit more complicated than 'Phone, Tablet, Laptop, Desktop'
On the browser, we (quite rightly) have very limited access to information about the machine it's running on. We don't know exactly what kind of device we're on, we don't know what screen size we have. We don't even know the size of the window we're running in.
What we know is the size of our viewport. Using this, we try to guess what the screen size might be. But this assumes our viewport is 1:1 with the window size (Which we default to, but the browser can override if it wants to) and that our window is running full screen.
What I suggest we do initially is this:
- Anything that we assume is a computer, can access everything as normal
- Anything else is audience-only with slide-in chat in terms of the performance space
There isn't anything special about the workshop functionality so we can have a fully featured tablet/mobile experience here off-the-bat but obviously the UI will need to adapt (as it already does)
Over time, we can add performance functionality to the tablet/mobile experience provided that we can actually come up with a usable way of doing so.

vicki:
Well seeing as how i am working with school age youth now is alongside a coomunity engagement project around an urban waterway (aside from the weaving project with the harihari group)
They might be telling the story of the waterway
Walking around its previous path and introducing its current meander through the endangered inhabitants
They would be talking about the sensor array they have installed and describing how temperature can present a physical barrier to passage highlighting areas where the waterway is comprised due to canalisation.
They could be pulling in data from the sensors, overlaying it with live images of the stream and avatars of  the species that would be there in ideal conditions
They might draw in how improvements could be made

that looks reasonable Paul :)
i went off on a possibilities tangent there!
dreaming big ;)

helen:
big dreams are good :)
paul, your proposal sounds sensible. getting the mobile audience on board first, & then perhaps we have some interesting projects for future students in developing mobile features :)

**Comment by helenvarley** [comment]
wondering: should we be making an app for mobile devices (audience only)? would this be better than expecting audience on mobile devices to access UpStage via a website? we've always said "no download" but it's different now with everyone being so attuned to installing apps on their mobile devices. this might also allow us to create a better experience for the mobile audience?

**Comment by nguyenhongphat0** [comment]
Since we have forced landscape mode:
<img width="357" alt="Screenshot 2021-02-21 at 12 10 58" src="https://user-images.githubusercontent.com/29925961/108616200-de84bc00-743d-11eb-954b-38e23415504c.png">
And zoom the stage on mobile devices, which make the viewer larger and these components smaller:
<img width="664" alt="Screenshot 2021-02-21 at 12 12 01" src="https://user-images.githubusercontent.com/29925961/108616215-0411c580-743e-11eb-9811-e9da174a208d.png">

What should we do next to resolve this issue? 🤔

**Comment by helenvarley** [comment]
test it? :)

**Comment by paul-rohrlach** [comment]
> wondering: should we be making an app for mobile devices (audience only)? would this be better than expecting audience on mobile devices to access UpStage via a website? we've always said "no download" but it's different now with everyone being so attuned to installing apps on their mobile devices. this might also allow us to create a better experience for the mobile audience?

I would strongly advise against this route for now.  You would essentially have to duplicate everything we've been doing twice over.

Unless you go the WebView wrapper route - In which case, it's just an unnecessary complication.

**Comment by helenvarley** [comment]
yes that comment of mine was from october last year; we've since discussed it further in meetings & agreed that an app is not necessary :)

**Comment by vickis** [comment]
agree - we would spend a lot of time trying to make it fit on
various screens devices
suggest we just stick to the main frame and let users decide if they wish
to view on whatever device
my thinking is that mobiles will be used more for viewing or streaming in
info (or creating larger works with many small screens

but the testers and artists will i am sure push whatever boundaries we give
them ;)
