### ISSUE TITLE
drawing with tablet

### ISSUE THREAD

**Issue by helenvarley** [upstage-org/mobilise#284]
there might be an issue with the drawing tool and drawing tablets; one of the workshop participants had a drawing tablet and was trying to use it for the drawing tool, but it didn't really work. using the tablet he could only do straight lines or dots. when he drew with the mouse it worked as expected, and when he used the tablet with other applications it also worked as expected.
i don't know if this could be a problem with tablets in general or with the specific one he is using, or if there are any settings that might need to be changed in the tablet. @vickis have you been drawing with a tablet?

**Comment by elisadcg** [comment]
i have a graphic tablet and it's working in my side.

**Comment by helenvarley** [comment]
so it could be an issue with the kind of tablet that he has - i will try to find out what it is. it's a huge one.

**Comment by vickis** [comment]
i have not used the tablet yet - but it is very low tech and i expect to be
fine

I am on a marae in a remote part of the country and did not bring much more
than my analogue drawing implements with me :)

**Comment by helenvarley** [comment]
@vickis please try it when you're back, & put the model info here; i've asked kayvan also. @elisadcg what brand and model is your tablet that works?

**Comment by elisadcg** [comment]
Wacom intuos with the wacom driver for linux.
If your workshoper have a wacom tablet (like a centiq) then it was the same driver. Let see if had differences between the driver for windows, mac and linux for Live UpStage.
If your workshoper have a Huion tablet, then we have to test with a huion tablet. I can try to test with huion tablet next week.
And your workshoper have a graphic tablet with or withour screen ? he was on windows, mac or linux ?

**Comment by helenvarley** [comment]
it's a wacom intuos pro medium, 3 or 4 years old. the tablet itself didn't have a screen. i think his computer is windows, i will check.

**Comment by helenvarley** [comment]
yes kayvan uses windows.

**Comment by vickis** [comment]
i am not yet able to test tablet (as not yet home)
will do so asap

looks like lots of improvements!!

**Comment by vickis** [comment]
this has been working fine for me (when the tool is working ;)
