### ISSUE TITLE
stage: player / audience counter

### ISSUE THREAD

**Issue by helenvarley** [upstage-org/mobilise#29]
as either audience or player, i expect to be able to see a counter on stage showing the number of players and audience currently on that stage at any time. i expect this counter to update in real time if players or audience enter or leave the stage.

additionally, this counter would allow me to see the names of players and audience members (if they have chosen to have a name) - for example a dropdown list of names appears when i click on the number.

currently in UpStage this counter appears above the chat window:

![image](https://user-images.githubusercontent.com/3437324/91056192-ef3aad80-e625-11ea-9eab-1390b3a16b18.png)

**Comment by elisadcg** [comment]
![audience-counter](https://user-images.githubusercontent.com/7611913/97146428-246b9500-1768-11eb-882a-af461562d33d.png)

**Comment by helenvarley** [comment]
great :) 
but i wonder, does it make sense for the audience to have the counter on the same side as the chat window? or will it work for them to have it on the top left?

**Comment by vickis** [comment]
might it be that in making the stage layout mutable the connections
(audience, player, stage live indicator) are also able to be placed where
best for the show?

**Comment by helenvarley** [comment]
yes - then this issue perhaps connects to the https://github.com/upstage-org/mobilise/issues/50 - customisable chat window position.

**Comment by elisadcg** [comment]
We have some example... like Gimp, who is not famous for his ergonomic with 2 modes (Single window mode or not). As we are with the navigator and the mouse, it's maybe possible to drag'n'drop the layout. Or we can prepare some theme with tools on the left, on the right, (maybe all around ??)
![issue29](https://user-images.githubusercontent.com/7611913/97993927-03004e00-1de5-11eb-928e-44c631ed3344.png)

**Comment by helenvarley** [comment]
yes, it would be great for players to be able to determine the layout of the tools, chat etc :) this is really issue #50 

for this issue about the player/audience counter - to me it makes sense to have it at the top of the chat window, whether the chat is on the left or the right. then we need also to think about where it would be on mobile devices ...

**Comment by elisadcg** [comment]
![issue29-2](https://user-images.githubusercontent.com/7611913/98221330-c9982180-1f4f-11eb-96bc-184c926cb03d.png)

OK view in desktop.
I imagine the counter for audience above the chat.

**Comment by helenvarley** [comment]
@paul-rohrlach @gloriajw @nguyenhongphat0 - how far away are we from having a player/audience counter on the stage? this would be very useful already, so that we can see when others are on the stage with us.

**Comment by nguyenhongphat0** [comment]
I'm working on this as well, but I'm afraid it is not stable enough to be included in R1-2021. There was some issue with the counter when someone suddenly left the stage (like an network error or lost power situation) 🤐

**Comment by helenvarley** [comment]
ah that's a pity. would it be easier to include it somewhere in the dashboard for now, & onto the stage later? or it's difficult anywhere?

**Comment by nguyenhongphat0** [comment]
In the dashboard 🤔? If you want to know how many audiences **visited** the stage then it can be include in the dashboard. The number of `online audiences` can only count when are connected to the stage, @helenvarley

**Comment by helenvarley** [comment]
this would be very useful - to have a record of how many audience were in past performances ... can it be kept connected to a date and time, so you can look back afterwards & see how many audience at various shows?

definitely we want a live counter on the stage; previously we also had the live numbers showing alongside the stage list, so that you could see at a glance how many people were on different stages. this is useful when doing workshops across several stages, or in festivals when you want to get an overview of how many concurrent people are there.

**Comment by gloriajw** [comment]
MQTT is vague about this, and does not break down counts by channels, which is what we would need. 
Despite this, we can do our own counting: 

`
def on_connect(client, userdata, flags, rc):
   global flag_connected
   flag_connected = 1

def on_disconnect(client, userdata, rc):
   global flag_connected
   flag_connected = 0
   `
and we can also keep a tally of who is using which channels, which would show us a stage count. Not too bad, it just needs to be written to the DB, and we need an endpoint to get it.

**Comment by nguyenhongphat0** [comment]
Yes and I'm using that `on_connect and on_disconnect` technique to count audiences. But the issue when implement this on the front end is that when someone suddenly leave the stage, the browser won't raise the disconnect event to others audiences, which make the counter not correct 😩 

Is there anyway to do this on the broker side, Gloria?

**Comment by gloriajw** [comment]
Yes, I think the solution is to write the counter to the DB, as an atomic operation, then query the DB for the counters.
`ChannelCount.query.filter_by(channel==some_mqtt_channel).update(
        {ChannelCount.count: ChannelCount.count + 1}
    )`
    Same for decrement. Then you query these counts using a graphql interface, so you get live updates. 
    This isn't perfectly atomic, and the count doesn't have to be pinpoint-accurate within the millisecond. So this should be fine.

**Comment by helenvarley** [comment]
you devs are amazing! you can find a solution for everything :1st_place_medal:

**Comment by helenvarley** [comment]
it would be really useful to also have the player/audience counter on the stages list https://app1.upstage.org.nz/V4.0/ui/backstage/stages
it doesn't need to give the names of who is on the stage, just the numbers (we had it like this in the old UpStage) - this way you can easily see if people are already at your rehearsal or performance, and if you're about to sweep or edit the stage, you can check first if people are currently using it.
