### ISSUE TITLE
chat: possibility to expose or hide during performance?

### ISSUE THREAD

**Issue by helenvarley** [upstage-org/mobilise#290]
a feature suggestion from our artists: the possibility to choose to expose or hide the chat window during a performance. for example, there might be a part of the performance where the artists don't want the distraction of the chat, they want all focus on the on-stage action; and then another part where they want to bring the chat in to the performance.

if this is possible to do, could it be that there is a fade in / fade out or similar effect, so it's not that the chat abruptly appears or disappears?

& if it is possible to do this on the live stage, maybe we don't need to have an option in the stage edit interface to have the chat or not, because you can do this on the live stage ... ?

**Comment by nguyenhongphat0** [comment]
Yes, and it is easier to do this on the live stage instead of the stage edit interface. But where should we but this button 🤔

**Comment by helenvarley** [comment]
either:
- in the chat settings that you can access from the gear icon top right of chat window? this would need to be only visible to players; & then the question is how to access it when the chat is hidden, to make it appear again ...
- or perhaps better, another option in the left-hand tool palette, that opens the chat settings window?

**Comment by nguyenhongphat0** [comment]
Great, I think I will create another tool in the left-hand palette, called Settings, and we can Show/Hide the chat from there, and do something else that we want in the future 🙌

**Comment by nguyenhongphat0** [comment]
Here you go 🎉 
<img width="1319" alt="Screenshot 2021-04-25 at 21 06 36" src="https://user-images.githubusercontent.com/29925961/115996616-2f658c00-a60a-11eb-885a-e00f7cb43cfb.png">

**Comment by helenvarley** [comment]
good! there might be other stage settings that could be grouped there too - for example maybe this is a better place for the stage background colour than in the backdrops bar?

**Comment by nguyenhongphat0** [comment]
Agree!
