### ISSUE TITLE
consistent position of "new" buttons

### ISSUE THREAD

**Issue by helenvarley** [upstage-org/mobilise#294]
i noticed that the buttons to create a new stage, or to upload a new media item, are differently placed:
![Screenshot at 2021-04-28 16-05-39](https://user-images.githubusercontent.com/3437324/116417613-bb122f00-a83b-11eb-8cc1-c962e48f5e49.png)
![Screenshot at 2021-04-28 16-05-56](https://user-images.githubusercontent.com/3437324/116417621-bcdbf280-a83b-11eb-87b4-ec013c85d7ef.png)

it would make sense to have them both in the same position, & i think  my preference is where the Media one is - as this is more prominent and also your cursor is usually closer to it, if you have just clicked on Media in the top navigation.
But the font of the New button for a new stage is bolder & maybe a little bigger (?) than the Media one, & i think this is better.

**Comment by elisadcg** [comment]
Yes consistency on layout is helpful for users.
![issue-294](https://user-images.githubusercontent.com/7611913/116420713-894e9780-a83e-11eb-857f-307de076508c.png)
I suggest to let the title alone
and right under the title the actions in a row.

We think that the name of the page display on the banner is efficient, so no more description (like in Backstage page : erase the "Presentation of the goal of the page".

**Comment by vickis** [comment]
agree - re positioning :)
