### ISSUE TITLE
graphics formats

### ISSUE THREAD

**Issue by helenvarley** [upstage-org/mobilise#298]
i noticed on the upload interface it says that allowed graphics formats are .jpg, .png, .gif, .bmp and .svg.
is it appropriate to have .bmp and .svg? i don't know enough about graphics but i thought these are more like formats for print graphics?? do we want to upload those to UpStage?
also, the last time i tried to upload a gif it didn't work.
this issue relates to #37

**Comment by nguyenhongphat0** [comment]
In my opinion, .svg is a perfect format for UpStage, since it can be scaled to any size without quality lost
And I seen .bmp a lot but I don't know much about it. But I thought it's a good idea to supporting as many media format as possible 🤔

**Comment by helenvarley** [comment]
ok, great. i will try the gif again :) & it's fine to have all the graphics formats, if they are useful to have :)

**Comment by helenvarley** [comment]
elisa says that we can't play animated gifs on the stage. it would be very good to be able to do this - can we???

**Comment by elisadcg** [comment]
.gif run good now ! i think .bmp is now a very old format. .svg is very good :)

**Comment by nguyenhongphat0** [comment]
Okay so we have .gif working, .bmp removed and .svg is fine. I think this issue is resolved 🎉
