### ISSUE TITLE
real-time text - writing & animating text on the stage

### ISSUE THREAD

**Issue by vickis** [upstage-org/mobilise#3]
As a player, I want to write text directly onto the stage and manipulate/animate it in real time. I expect to be able to do this in a way that is intuitive and compatible with the other on stage player tools.

**Comment by elisadcg** [comment]
Ok si let's add another tool on the sidebar with his option (1). Or maybe includ this tool inside the Draw palette (2 : to be developed in the wireframe). And we can imagine some already Preset prepared for text (3). Just clic in it and the selected tool be styled.

![issue3](https://user-images.githubusercontent.com/7611913/98118062-eb8b9880-1eaa-11eb-9be9-9739dd479c6e.png)

**Comment by helenvarley** [comment]
looks great! can the text also be moved around the stage?

**Comment by elisadcg** [comment]
![issue3-b](https://user-images.githubusercontent.com/7611913/98212395-d0b93280-1f43-11eb-9525-dc87c3dd70db.png)

Yes i imagine the manipulation as an avatar, so it can be rotate, flip, scale and change it z-index (layer).
