### ISSUE TITLE
stage: audio tools

### ISSUE THREAD

**Issue by helenvarley** [upstage-org/mobilise#30]
As a logged-in player on a stage, i expect to be able to access an audio tool palette that shows an alphabeticised list of audio files that have been assigned to the stage, and tools that allow me to:
- select one or more tracks
- play, pause and stop one or more tracks
- mix two or more tracks together
- cross-fade between two tracks
- adjust the volume of each track individually
- adjust the volume of all tracks together
- see the length of a track, and how far through it is
- start or stop the track at a specific timecode

**Comment by helenvarley** [comment]
a volume control for each track is very important!
most of the other feature requests here can be left for later, or even not needed - if we can get streaming working then for more complex audio mixing people can use whatever software they want & send an audio stream to the stage.

**Comment by elisadcg** [comment]
i Suggest a right click on it to adjust the volume as the item is on the top bar

**Comment by nguyenhongphat0** [comment]
That right click volume sound good. Thank you @elisadcg

**Comment by helenvarley** [comment]
and we also need an option to loop

**Comment by elisadcg** [comment]
we want to be able to play a sound with loop, to get the duration visibility and to adjust his volume. I suggest this option stil visible on the overlay and usable when a sound is running.
![30-sound](https://user-images.githubusercontent.com/7611913/114871225-5c8b9080-9df9-11eb-9299-ecb9cc0db3a6.png)

**Comment by helenvarley** [comment]
we need to think how these tools can work in the bar when there could be many audio tracks, and more than one playing at a time; or does the audio bar need a different layout to the others?

**Comment by nguyenhongphat0** [comment]
When the audio is playing we can expand its width so that we can have the progress slider, pause, loop and volume buttons, like this `Typing` and `sound 2`:

![](https://user-images.githubusercontent.com/7611913/113400356-f424c400-93a1-11eb-96c7-8c6b67962c42.png)

**Comment by vickis** [comment]
great :)

**Comment by helenvarley** [comment]
looks great; but where is the volume control and loop button?

**Comment by helenvarley** [comment]
damn i forgot to assign this one to C3PO - it's pretty important. we desperately need the ability to loop audio files, and to adjust the volume.
the volume needs to be able to be adjusted live, so that you can fade a track in and out; and also possible to set before you start the track playing, so that for example you can have a sound at a very low volume if you want.

**Comment by nguyenhongphat0** [comment]
Maybe we would need a new icon for that Loop button, it look quite inconsistent with the others 😅 
<img width="594" alt="Screenshot 2021-06-16 at 14 26 26" src="https://user-images.githubusercontent.com/29925961/122176511-e239c400-ceae-11eb-9295-b09b19190a75.png">

**Comment by vickis** [comment]
do you mean the pause button?

**Comment by nguyenhongphat0** [comment]
No I meant the Repeat icon, I'm using the rotate 45 degree icon instead 😅

**Comment by vickis** [comment]
Ah ok you could try the infinity symbol ...

**Comment by helenvarley** [comment]
the infinity symbol sounds nice, but also the rotate symbol is logical to me. shall we ask our icon-expert @riadsalameh for an opinion? :)

**Comment by vickis** [comment]
Agree it can be used in both contexts :)

**Comment by riadsalameh** [comment]
Hey, hey 😁

Maybe it can be something like this??
And I also suggest to change the toggle button as well since it looks a bit disconnected with everything else. 

![Audio Loop](https://user-images.githubusercontent.com/71765608/122666846-ff70da00-d1af-11eb-80f3-5d388e65f132.jpg)

**Comment by vickis** [comment]
Great thanks Riad
I prefer option 2

**Comment by helenvarley** [comment]
yes me too, option 2 :)

**Comment by helenvarley** [comment]
i'm reopening this issue because we need some refinements with the audio tools:

- the scroll bar is very difficult to manage when you are trying to operate several tracks
- it must be possible to set the volume and looping BEFORE the track starts playing
- can it be possible to save settings, such as loop and volume, on the stage so that you do not have to re-set every time you want to play that track, or every time you enter the stage?

**Comment by vickis** [comment]
Tracks that are playing could all appear first perhaps
Then the rest alphabetical as usual?

**Comment by nguyenhongphat0** [comment]
> the scroll bar is very difficult to manage when you are trying to operate several tracks

Now we can use hotkeys (1-9) to play audio 👍 And you can hold Shift to "temporary compact" the toolbox, to see all of it content without scrolling. Watch the screen capture video below, let me know if it helps 🙏 
https://user-images.githubusercontent.com/29925961/125476093-c0ca1ecd-0f9c-4124-954f-476476980815.mov

> Tracks that are playing could all appear first perhaps

This was a good idea but only when we don't combine it with hotkeys. It would be harder to remember the hotkeys when position of tracks keep changing


> it must be possible to set the volume and looping BEFORE the track starts playing

It is possible now!

> can it be possible to save settings, such as loop and volume, on the stage so that you do not have to re-set every time you want to play that track, or every time you enter the stage?

These changes should persist, Helen 🤔

**Comment by helenvarley** [comment]
wow great work phat! :clap: 
i will ask eva to have a play, as she is keen to use the audio tools. 
one thing i noticed is that when i did a right click to get the loop & volume tools for a track, and then clicked another track to play, the loop and volume tools remained visible - but for the first track, not the second track. this was a little bit confusing, as i adjusted the volume & expected that to be for the second track i'd selected. could the number of the track be shown in right corner of the loop & volume tools, to remind you which track this is for?

**Comment by nguyenhongphat0** [comment]
Hotkeys only work for the first 9 tracks. The others must use mouse click like we used to do. Do you want to assign other hotkeys for them as well? 🤔 

> number of the track be shown in right corner of the loop & volume tools, to remind you which track this is for?
Yes we can, but number only works for the first 9 tracks, should I put the name of the audio instead?

**Comment by helenvarley** [comment]
no, let's wait for feedback from the artists. eva will also try using an audio stream so that she can mix using ableton live on her desktop, & as long as the audio streams function well this is probably a better solution than trying to make a complex audio tool within UpStage. (don't reinvent the wheel if we don't have to!)

**Comment by helenvarley** [comment]
when i hit the pause button, it functions as a stop button rather than pause. it would be good if, next to the pause button, there was a stop button.
the pause button should pause the track at that point in the track, so that if you click it again, the track resumes playing from the same place. the slider should remain visible when the track is paused.
the stop button should stop the track, so that if you start it again, it's at the beginning of the track.
it should also be possible, when the track is paused, to move the slider so that you can go to another part of the track and then unpause it.

**Comment by helenvarley** [comment]
and: how can we fade a track in and out? if i move the volume slider while a track is playing, the volume level jumps to the new setting, it doesn't increase or decrease as i slide it.
this is quite an important feature to have as we will often want to fade sounds in and out.

**Comment by helenvarley** [comment]
one more thing :)
the volume slider and the slider that shows how far through the track you are, are identical. it's easy to get mixed up and try to adjust the volume with the time one. @elisadcg @riadsalameh any ideas for how this can be improved?

**Comment by vickis** [comment]
dashed line for time? segmented

**Comment by helenvarley** [comment]
yes something like that would be good for the time slider, as you might want to jump to a certain point in a track and some kind of marking would help with that

**Comment by vickis** [comment]
exactly :)

**Comment by elisadcg** [comment]
I have send the loop.svg in slack.
For this i suggest,
![issue-30-02](https://user-images.githubusercontent.com/7611913/126874408-beb5359e-c412-43cd-b708-8f55ee4326ef.png)

above a sound playing, a little menu appear with the loop option, the play/pause toggle button.

Actually the context menu is on top of the sound wh
![Screenshot_20210724_180958](https://user-images.githubusercontent.com/7611913/126874462-a18dcdec-aca1-4d30-9545-ded517c31998.png)
ich is heavy.

**Comment by helenvarley** [comment]
don't lose the volume slider ...

**Comment by nguyenhongphat0** [comment]
Okay so now we have:
- Separated Pause and Stop button
- Volume fading
- An easier to seek duration and change volume, which is more distinct 🙌 

https://user-images.githubusercontent.com/29925961/129404496-7a822c03-5f56-41ec-98aa-85ef7dd62439.mov

**Comment by helenvarley** [comment]
great! how can i adjust the volume before starting to play a track?

**Comment by nguyenhongphat0** [comment]
You can click on that button to show the volume slider. It is now visible even when the track is not playing

<img width="243" alt="Screenshot 2021-08-18 at 23 16 20" src="https://user-images.githubusercontent.com/29925961/129934256-6d0cc867-6bca-41e7-aa82-338691232f66.png">

**Comment by vickis** [comment]
great! :D

**Comment by helenvarley** [comment]
ok, got it - i was clicking on the icon in the audio bar, but now i see we can hover over it to get the tools without starting it playing (will note this in the manual) :+1:

**Comment by vickis** [comment]
brilliant :)

**Comment by helenvarley** [comment]
i find it still a bit confusing between the volume slider and the length-of-track indicator; the only difference is the colour, and the only way to toggle between is the volume icon. we need to use it more to work out if it's ok like this, so let's get it onto app1 & see what others say.

**Comment by riadsalameh** [comment]
To differentiate the audio length from the volume, I suggest something similar to this. I personally think that option one is more intuitive and it is a visual representation that most people are used to because of youtube and other audio or video platform that follow that format. What do you think? 
![VOLUME_OPTION-01](https://user-images.githubusercontent.com/71765608/132198815-ce3c96b8-5f53-466e-b96c-70191706b836.jpg)

**Comment by nguyenhongphat0** [comment]
Great @riadsalameh! Option 1 look more handy 👍

**Comment by vickis** [comment]
Yes Agree!
The dashed line was for a difference between volume slider and time stamp
Option 1 is great :)

**Comment by helenvarley** [comment]
yes i agree, option 1 looks good - as long as it's not so small that it's difficult to make small adjustments. this was sometimes the case in the old UpStage - we also had quite a small volume slider there. but also this arrangement is more similar to how it used to be & i think people will find it intuitive :)

**Comment by helenvarley** [comment]
great, having the volume slider at the side makes it much clearer what is what :)
