### ISSUE TITLE
stage: private communication for players

### ISSUE THREAD

**Issue by helenvarley** [upstage-org/mobilise#32]
as a logged-in player on a stage, i want to be able to communicate privately (unseen or heard by audience) with one or more of the other logged-in players.
currently in UpStage players have the ability to "whisper" to each other - send text messages that are not visible to the audience. this is done with the /wh command, in the chat window. it is problematic for many reasons - very easy to make a typo & have your whisper appear to everyone; not intuitive; time consuming especially when you want to whisper to specific individuals rather than to all players on that stage.
it would be great to find a new solution, that would allow the players on a stage to communicate privately; that doesn't take up much space & is quick & easy to do in the heat of a performance (as it's usually when something isn't going quite right during a performance that you need this feature!)

vicki:
perhaps as with the water-wheel there is the ability to open a chat window that is just for players on stage - like a prompt space .. that would alert all to stage directions etc
AND there is something like the @t command...

**Comment by elisadcg** [comment]
This invovle : number of audience display, and list of nickname available on chat !

**Comment by helenvarley** [comment]
i can imagine this as a second layer to the chat window, with tabs to switch between the public / audience chat, and the private chat for players. 
the tab to switch should be at the bottom, somewhere near the text input field (maybe in this yet-to-be-implemented bar that would also have tools for whispering & shouting?)

**Comment by vickis** [comment]
Also scrolling up and down chat would be useful - if focused on player and
needing to switch back and catch up with audience chat

a work around to enable overseeing both might be to have a split chat
window with the top for logged in and the bottom for audience (that way
there will be no possibility to accidentally type in wrong tab (the
waterwheel implemented this)

**Comment by helenvarley** [comment]
there is a scroll bar - it only appears when there is something to scroll (at least - in firefox on linux! does it work same on all browsers?)
the split chat is what they had in the Tap; it's definitely an option to consider, but what i found in the Tap was that this made it difficult to follow if there was quite a bit of chat - easy to miss things as there was not so much space to glance back. 
could there be other indicators to help avoid accidentally typing in the wrong chat, such as the player chat having a different colour, and/or different options by the input field? for example you would not need options for thinking & shouting in the private player chat as the text would not appear as a speech bubble or be spoken aloud.

**Comment by elisadcg** [comment]
i don't know Tap chat. 
But split chat seams to be hard in so tiny place. What about chat in different tab ? with notification when new messages comes ?
The possibility for color and options different for each chat is good idea.

**Comment by helenvarley** [comment]
yes, i'm with elisa on the different tab, notification of new message & colour differentiation to avoid mistakes :)
people might be using tablets or very small screened laptops as players, so a split chat would be pretty difficult.

**Comment by helenvarley** [comment]
here's a proposal for the player chat: it's a pop-out window at the left-hand side of the stage, so no confusion with audience chat.
there's an icon in the toolbar to open and close it, so if you don't need it, it's not there
if someone types your player name into the player chat, this either makes the player chat pop open, or the icon flash? to indicate that there is a message for you.
the chat box is the same as the audience one but smaller, and doesn't need the reaction emojis. maybe doesn't need the settings icon either? could have some other slimming down perhaps - it's purely for player communication so never visible to audience, and needs to be functional.
![player_chat_proposal](https://user-images.githubusercontent.com/3437324/125364758-25f8ee00-e3c7-11eb-975a-d44d66ff6536.png)

**Comment by vickis** [comment]
Agree great to be able to move it & def needs to be able to minimise

**Comment by helenvarley** [comment]
or it could just "close" & disappear? no real need to have it minimise, if there is a button on the toolbar to make it appear/disappear ...

**Comment by vickis** [comment]
yes correct that's what i meant
usually indicated by a bar (orange button) collapses it to only show a
tab or icon to reinstate it

**Comment by elisadcg** [comment]
Two idea :
- 2 tab on the chat window
- or 2 separate chat. The chat have to minimize and something showing that new message arrived (like color change for example)
![issue-chat-privacy](https://user-images.githubusercontent.com/7611913/125425263-5721b354-0715-4128-9221-65732b898e55.png)

**Comment by nguyenhongphat0** [comment]
I would prefer the second option 🙌

**Comment by vickis** [comment]
Yes 2nd for me too! :D

**Comment by helenvarley** [comment]
yes i also prefer a separate chat. but i don't think it needs to be visible all the time. as players, we don't need it most of the time. can there be an icon in the left-hand toolbar, click to open the chat window, with some indicators, e.g.:
- when another player has opened the chat window, the icon in the toolbar becomes highlighted for all players on that stage
- when a player's name is mentioned in the player chat, the player chat window will open for them if it isn't already open
- closing the chat window removes it entirely from the stage

is it possible for it to be a moveable window? that appears in the bottom left corner by default but can be moved by players if they need to?

**Comment by nguyenhongphat0** [comment]
Okay we now have a separated chat box that is hidden from the audience, and can be move/resize:

<img width="1307" alt="Screenshot 2021-07-15 at 18 15 41" src="https://user-images.githubusercontent.com/29925961/125780035-9e1dbc08-d637-4f9c-9b54-b4939a2e9787.png">

You can minimise it to the left toolbar

<img width="1307" alt="Screenshot 2021-07-15 at 18 14 33" src="https://user-images.githubusercontent.com/29925961/125780007-730e37ee-aa81-46e1-8c8a-97b65aae83d8.png">

And click on the player name (on the audience counter) to **mention** a player. Mentioned player will have their chat box auto appeared

<img width="1320" alt="Screenshot 2021-07-15 at 18 16 31" src="https://user-images.githubusercontent.com/29925961/125780303-3bb6d195-4244-4d75-8fc2-675f294d41cf.png">

**Comment by vickis** [comment]
wow super work Phat!
vicki :)
