### ISSUE TITLE
blank page after logging in

### ISSUE THREAD

**Issue by helenvarley** [upstage-org/mobilise#326]
is https://dev-app1.upstage.org.nz/V4.0/ui/backstage meant to be blank? after logging in, i can see the navigation options at the top but the rest of the screen is blank.
it would be good if we could use this page for customisable announcements & information for players.

**Comment by nguyenhongphat0** [comment]
Sorry about this, I patched a hot fix 😅

**Comment by helenvarley** [comment]
great! :)
(but it would be good to think about this for the future - that maybe here would be useful to have a customisable page of info for players ... )

**Comment by nguyenhongphat0** [comment]
Yes we can put anything we like on this screen, but let's open another issue for this 😅

**Comment by helenvarley** [comment]
i'll do it now otherwise i'll forget ... :laughing:
