### ISSUE TITLE
stage list - do we need toggle button?

### ISSUE THREAD

**Issue by helenvarley** [upstage-org/mobilise#327]
https://dev-app1.upstage.org.nz/V4.0/ui/backstage/stages
the default view is to show stages that you have created. to see others, you have to first toggle the green button and then choose either all players or a specific player.
why do we need the toggle?
couldn't it just show our stages, and then if we want to see others we just choose from the dropdown?

**Comment by vickis** [comment]
agree all your own stage on first logging in (created by and player on)
toggle to all stages

**Comment by helenvarley** [comment]
actually what i am saying is that the toggle is a redundant step; you can choose from the dropdown menu, the first option is "all stages" and then it lists the players so that you can select the stages of a particular player.
so the toggle is not actually needed.

**Comment by elisadcg** [comment]
![issue-327](https://user-images.githubusercontent.com/7611913/122545290-f8ba5980-d02d-11eb-868d-bcd5c48f2712.png)

**Comment by helenvarley** [comment]
closing this as now the toggle button is needed with the new layout.
