### ISSUE TITLE
recordings & chat in stage management interface

### ISSUE THREAD

**Issue by helenvarley** [upstage-org/mobilise#330]
In the stage management menu, there is "Chat" and "Records". Could this be combined into one, that is just called "Recordings" ?
Here i would expect to find a chronological list with links to the replay recording and chat log for each time period, as well as options to edit or delete the recordings.

**Comment by nguyenhongphat0** [comment]
Well technically it's is possible, but why 🤔 ?
The Chat is just like a log, you can see all of the messages that ever been sent by users

<img width="1440" alt="Screenshot 2021-05-14 at 23 20 58" src="https://user-images.githubusercontent.com/29925961/118299532-c66e8700-b4d8-11eb-8bbe-3dd5a7139192.png">

The records is something else, it replay the performances, and chat will appear from time to time, and only chat of that performance only
<img width="1440" alt="Screenshot 2021-05-14 at 23 22 14" src="https://user-images.githubusercontent.com/29925961/118299659-eef68100-b4d8-11eb-8a68-99b9ec0ae185.png">

**Comment by helenvarley** [comment]
most often what we will want is the chat log and recording of a specific period of time, e.g. a rehearsal or performance. so we need to be able to locate that, e.g. to find the recording of a performance or the chat log from a rehearsal a few days ago. so having the chat as one long log, without any time breaks, is actually going to be quite frustrating.
here's a screenshot of how the recordings from BBB are organised. it would be good to have something similar to this, but with "chat log" instead of "whiteboard", so that you could access the data for a specific date & time. is that possible?
![Screenshot at 2021-05-15 12-05-00](https://user-images.githubusercontent.com/3437324/118356514-f0c25200-b575-11eb-84ba-a2ccc979de9a.png)

**Comment by helenvarley** [comment]
it's probably good for you to know how the artists will use these logs & recordings:

- chat logs: from rehearsals, we often copy and paste bits of dialogue and create scripts; from performances, excerpts from the chat logs can be used in the public documentation of a performance, as examples in articles & blog posts, and also in funding applications and reports. so it's important to have the chat logs as text documents that can easily be searched and copied as text.
- recordings: from rehearsals, we might want to watch part of or the whole rehearsal to see what works or not. from performances, we often take excerpts from recordings to make documentation and reports. it is most useful to have the recording in the audience view, so that it is only showing what the audience see & hear, not the logged-in player view.
- recordings are also important for making tutorials about how to use UpStage; in this scenario, we would want the player tools to be seen. so it would be great if there was an option for the recordings, to be audience view or player view - the default should be audience view.

**Comment by vickis** [comment]
agree
chat = dated searchable txt documents

and awesome if there could be player or audience view of recordings!
vicki :)

**Comment by helenvarley** [comment]
could it be that when you use the button "clear chat and sweep stage" in the stage management interface, that the chat up to that point is saved as a file with date & time filename, & then on the chat recordings interface there can be a list of files?
(maybe it would also be good to separate that button into two "save and clear chat" and "sweep stage" - separate issue i know!)

**Comment by helenvarley** [comment]
looking at the chat & recording interfaces in stage management: 

- [ ] there needs to be some correlation between the chat log and the replay, as usually we will want both for a specific performance or rehearsal. this is why i've proposed a single interface like we have with BBB, in the screenshot above. at the moment, i see a time-frame for the chat, as well as how long ago it was, while the replays only say how long ago it was. on the demo stage, there are 13 chats going back 20 days, and 12 replays going back a month. the chats show the most recent first, the replays show the most recent last. 
- [ ] we should probably use the word "replay" consistently rather than "recording", since it is in fact a replay, not a recording
- [ ] the single menu item could say "Replays and Chat"
- [ ] there needs to be a delete button

it maybe required a bit more thought, & maybe even a manual saving system, since what is useful for the artists is to be able to have the chat & replay from the actual rehearsal and performance events - but this will be very difficult to find and organise if for example there are several events in a short space of time that are all included in the same replay or chat. it might be more useful for the artists if we can specify the start and end of the replay and chat at the time of the event.
what do you think, @vickis ?

**Comment by helenvarley** [comment]
just had an idea - could the menu item for chat & replays be "Archive" ? and on this screen we have access to the chat and replays for specific periods, laid out in a way similar to the BBB screengrab above, so we can see which chat goes with which replay, and what time and date it all is.

**Comment by helenvarley** [comment]
this looks great! :) naturally i have a couple of thoughts ... ;)
- does the delete icon delete both chat and replay?
- "download all chat" presumably means all the archived chat files; whereas "clear chat" just means clearing the on-stage chat?
- how does the "Archive Performance" button work?

**Comment by nguyenhongphat0** [comment]
> does the delete icon delete both chat and replay?

Yes it does, and there is a warning before you delete:

<img width="504" alt="Screenshot 2021-08-02 at 10 31 40" src="https://user-images.githubusercontent.com/29925961/127800921-bc2636b9-2ff0-4443-b3dd-438afd615282.png">

> "download all chat" presumably means all the archived chat files; whereas "clear chat" just means clearing the on-stage chat?

Yes, download all chat is like you download all these individual chats and merge them into one file. Clear chat will clear the on-stage chat, without affecting other objects on the stage. Clear chat won't create new archive, so an archive can have multiple clear chat. Take a look here:

<img width="1114" alt="Screenshot 2021-08-02 at 10 33 02" src="https://user-images.githubusercontent.com/29925961/127800989-8af61cb0-b287-46fd-8fbc-54cda1b3d9de.png">

> how does the "Archive Performance" button work?

Technically, Archive Performance work exactly the same as Sweep Stage, which clear everything on the stage and store them into an archive, including chat and replays

**Comment by vickis** [comment]
superb!

**Comment by helenvarley** [comment]
can the delete warning say "Deleting this archive ... " rather than "Deleting this performance ... " ? also "replays" and "undone" (not "undo")

do we need the "clear chat" button here? it's in other places e.g. on stage and in the general information section, so it's not really necessary to have on the archive screen & is confusing, as it doesn't actually change the archive.

**Comment by helenvarley** [comment]
this is still a bit frustrating, to have hours & hours of nothing, even when there is a mark where the activity is it's still very hard to precisely get to it.
is it not possible to have the recording only activated when there is an action?

**Comment by nguyenhongphat0** [comment]
Well it is possible now. I propose the new Recording column in the stage table, that you can start and save recording for a specific stage. The recorded result was... weird, but it look quite promising 😅 

<img width="1345" alt="Screenshot 2021-08-11 at 00 25 30" src="https://user-images.githubusercontent.com/29925961/128906504-ef565eae-145b-4185-8aab-f338456d1520.png">
<img width="1362" alt="Screenshot 2021-08-11 at 00 25 44" src="https://user-images.githubusercontent.com/29925961/128906452-956a9f92-e53a-455d-8ee2-f417e3af2c7e.png">

**Comment by helenvarley** [comment]
great! :)
i made a test recording & there are a couple of things:
- i played the applause sound at the beginning but this is not in the recording
- the recording should be in audience view, but i can see a grey icon over the avatar that i'm holding
- i replayed it at 1x speed, but it was definitely faster than i had been able to do the actions
- the first three lines of avatar speech came very rapidly one on top of the other
- i guessed to click on the recording info again to stop it, maybe there needs to be a mouse over message?

it's great that we can give the recording a name, & that it shows up in the archive with the date; is it possible to include the time as well? maybe it can be "recorded on [date] from [time] to [time]" ?

**Comment by vickis** [comment]
The grey Tane is an issue from earlier needs to be reopened if visible to
audience again :)

**Comment by helenvarley** [comment]
i checked this with another browser in audience view & don't see the carrot. now i tried another recording, but this time none of the media has been captured, when i play the replay i only get the avatar text appearing in the chat & nothing else at all - no backdrop, no avs, no drawing, no voices ...

**Comment by nguyenhongphat0** [comment]
> no backdrop, no avs, no drawing, no voices

This is why we need to decide whether we should:
 - Clear the stage when we start a recording
 - Or includes all the actions from the beginning of the performance, which made the recording more heavy

What is the right way to go? 😅

**Comment by vickis** [comment]
I think if it were a given that stage is cleared before a recording begins
(then for those 'setting up a stage for a perfromance... usually that is
~15-20 mins before, then they could cut the prep part out of the recording

scenario
>> recording activated (stage is cleared)
>> set-up happens and a brief pause then the curtain goes down)
...audience start arriving, some may chat
>> curtain comes up and perfromance begins
...whoever started the recording could make a time marker for the start of
the show ...
eg in chat
her's and hims, them's and they's...
get ready for the show!!

the timestamp could also be recorded locally (eg i know the show starts at
10.30 local time,
at 10.20 I start the recording (stage is cleared)
i set up the stage and at 10.30 we begin (when i replay to screen record
the event i begin ten minutes in )

does that make sense?

**Comment by helenvarley** [comment]
> > no backdrop, no avs, no drawing, no voices
> 
> This is why we need to decide whether we should:
> 
>     * Clear the stage when we start a recording
> 
>     * Or includes all the actions from the beginning of the performance, which made the recording more heavy
> 
> 
> What is the right way to go? sweat_smile

let's go with clear the stage when the recording starts. there needs to be a warning, but as vicki describes above, as long as the players know that the stage will be cleared then we just need to make sure we have time to set everything again.
if we are using the scenes tool, then we can set up a first scene, so that once we start the recording then we just need to select the first scene & away we go :)

**Comment by vickis** [comment]
yes perfect :)

**Comment by nguyenhongphat0** [comment]
I already fixed these:

- [x] i played the applause sound at the beginning but this is not in the recording
- [x] the recording should be in audience view, but i can see a grey icon over the avatar that i'm holding
- [x] i replayed it at 1x speed, but it was definitely faster than i had been able to do the actions
- [x] the first three lines of avatar speech came very rapidly one on top of the other
- [x] i guessed to click on the recording info again to stop it, maybe there needs to be a mouse over message?

By the way let's focus on recording in issue #53 , this issue is about the Recording & Chat interface in backstage. And I believe this should be closed 😅
