### ISSUE TITLE
avatar voice resets to default if you drop and rehold avatar

### ISSUE THREAD

**Issue by helenvarley** [upstage-org/mobilise#335]
i spent time finding a good voice for my avatar, but as soon as i dropped it, the voice reset to default.
this is urgent to fix - a voice needs to stay as it is set! we don't have time to constantly reset the voice every time we put the avatar on stage ... 
HIGH PRIORITY PLEASE!!

**Comment by nguyenhongphat0** [comment]
Sorry about this 😅 I believe this issue is resolved 🎉
