### ISSUE TITLE
avatar voices speak emoticons as numbers and punctuation

### ISSUE THREAD

**Issue by helenvarley** [upstage-org/mobilise#337]
if you are holding an avatar and use emoticons, these are spoken aloud by the avatars as punctuation and numbers.
can the voices be taught not to speak emoticons aloud?
if not, we need to know this as players - not to use emoticons ...

**Comment by nguyenhongphat0** [comment]
> can the voices be taught not to speak emoticons aloud?
Yes, I stripped out emoticons before pass it to meSpeak. This issue is resolved 🎉
