### ISSUE TITLE
voice changes

### ISSUE THREAD

**Issue by helenvarley** [upstage-org/mobilise#338]
i have my avatar voice set to be male4, scottish, deep and slow. mostly it speaks like this, but every now and again it switches to be some kind of european german-ish accent, pronouncing the words wrong.
i haven't managed to record it sorry. but the voice is not consistent.
![Screenshot at 2021-05-17 11-54-35](https://user-images.githubusercontent.com/3437324/118471069-a1ac2680-b707-11eb-9183-e1ab495ec98c.png)

**Comment by nguyenhongphat0** [comment]
This issue is part of #369, and it got resolved as well 👌
