### ISSUE TITLE
stage: chat styling

### ISSUE THREAD

**Issue by helenvarley** [upstage-org/mobilise#34]
This issue proposes that we more distinctly represent various types of dialog in the chat window so that we can use a higher number of variations. To begin with:
![image](https://user-images.githubusercontent.com/3437324/91060513-59098600-e62b-11ea-9ad8-9848263ed1f4.png)

helen:
i agree that it's good to be able to distinguish between different types of chat input, however i think we need to be quite careful with this & definitely make it optional. the chat window is important but it needs to work with what's going on visually on the stage - which is often quite a lot - & not clash with it or dominate (unless of course that is wanted by a particular performance).
can there be options within the stage set-up, where you can choose whether to have plain text or styled in the chat?

vicki:
oops should have commented about the colours here
i quite like it
the synaeathesists should be consulted!

**Comment by elisadcg** [comment]
First point, if the backdrop of the stage is colored, some colors of the bubble chat (green, red etc) will not displaying correctly. So we have two possibility for the place of the backdrop :
- backdrop take all the place of the screen (see image 1, 2 and 3)
- backdrop is not under the left palette and not under the chat (see image 4, 5 or 6).
We can imagine more styling on the chat, like put an little stroke around the bubble chat or/and a shadow.

![backdrop-chat-position01](https://user-images.githubusercontent.com/7611913/95970875-c1493c80-0e10-11eb-8aa3-7e3e2eb2cd5c.png)

**Comment by vickis** [comment]
Could you not just give chat a white background independent of the backdrop
(it may be collapsed in some instances

If the background colour does not fill the screen then the audience see a
white strip which on smaller devices would be wasted realestate

Perhaps also the tool palette needs to be collapsible
:)

**Comment by helenvarley** [comment]
the proposal for more distinct and various chat styling is from Limelight, & it came from the developers rather than something the artists requested. looking at elisa's mock-ups, i don't think it's what i as an artist actually want.

it's definitely good to have some definition. currently we have audience light grey & smaller, players black & slightly bigger; then there is thinking (light blue and in curly brackets), shouting (red, capitals) and whispering (only visible to players; blue). these are all just font colours, nothing dramatic (apart from shouting) & no different backgrounds for different lines of text. the different coloured backgrounds are what i find too much.

one of the things that is so beautiful about the current UpStage is that for the audience, the interface is very discrete, so that the focus is on the choices the artists make, rather than on the software. compared with something like Adobe Connect, where you never ever can forget that you're in Adobe Connect because of the interface, UpStage is much more of an empty stage for artists to create in.

i wrote above that it should be optional, & now my feeling is that it's perhaps really a "nice to have" in the future rather than something we need now ...

**Comment by vickis** [comment]
agree

**Comment by helenvarley** [comment]
there is now no distinction between audience chat text and player chat text; previously, text input by the audience was light grey and slightly smaller than the player text which was solid black. this made it easier to read just the players' text, if you wanted to follow the performance and ignore or pay less attention to chatter from the audience.
do we want to have a distinction between player and audience text? could the audience nicknames and text be slightly smaller and lighter coloured, as it was before?
maybe this can be an option to choose to have or not in the stage admin?

**Comment by vickis** [comment]
names appearing beside chat do now provide for that somewhat (as in you can
differentiate avs and nicknames of audience etc - especially if show hide
names is implemented ;)
but agree - distinction between player and audience would be great :)

**Comment by elisadcg** [comment]
![34-stylingchat](https://user-images.githubusercontent.com/7611913/114679981-fc1f2500-9d0c-11eb-8578-af668ed8f858.png)

**Comment by vickis** [comment]
Great yes the third one is my preferred option
I guess it means to refer chat UpStage must somehow detect login
The third optio gives players prominence :)

**Comment by helenvarley** [comment]
agree, third is also my option. can we prioritise this?

**Comment by helenvarley** [comment]
and i discovered that audience members can also "think" and "shout" - see image above. this is cool :)

do we want shouting to be like this, in a red bar, in the text chat? or is that too much? alternatively it could be that the text is red and bolded ... thoughts, @vickis @elisadcg ?

**Comment by vickis** [comment]
i think i like the red lettering and all caps (an understood image of
shouting)
and the light blue is fine

i also think that audience should be slightly smaller and grey
great progress!

**Comment by elisadcg** [comment]
Uppercase in red instead of background in red, could be enought for shouting.
And yes audience's nickname : normal no bold is good idea and their chat in grey lighter than player.
and what about a ((bla bla bla)) to a player become a false audience ?

**Comment by helenvarley** [comment]
> and what about a ((bla bla bla)) to a player become a false audience ?
thinking about this. previously in UpStage, if you weren't holding an avatar and you typed in the chat, it appeared as if you were audience. now, it appears with your username (unless you change it in the chat settings).
i think we need a quick & easy way to do it - something similar to the thinking & shouting prompts, such as typing - before your text.

**Comment by nguyenhongphat0** [comment]
Okay to cap up, we have:
- Player name is in bold
- Audience chat text is lighter
- Less red for shouting
- Type - to pretend to be an audience

<img width="300" alt="Screenshot 2021-06-18 at 21 10 55" src="https://user-images.githubusercontent.com/29925961/122574261-ae5eca00-d079-11eb-86a0-8ef500c9468d.png">

**Comment by helenvarley** [comment]
looking great! why is the audience text on the next line down from the name?
& if you type - to pretend to be audience, what name will show in the chat? if it shows your player username, then it might be obvious that you are not audience. perhaps it could show no username? @vickis what do you think?

**Comment by nguyenhongphat0** [comment]
> looking great! why is the audience text on the next line down from the name?

If the text is too long to be inline, it will be displayed in a block below that line 😅 

<img width="303" alt="Screenshot 2021-06-18 at 21 57 30" src="https://user-images.githubusercontent.com/29925961/122580481-33e57880-d080-11eb-8548-8e69a8a840d1.png">

**Comment by helenvarley** [comment]
ah, ok. it can't just wrap from the first line?

**Comment by nguyenhongphat0** [comment]
in that case the block would be indented, if the nickname is quite long then it would be very narrow to read the long text 🤔

**Comment by helenvarley** [comment]
ok, no problem :)
i think when we are simulating audience with the - (which is great!) the text should appear without any name.
and can the font size of the name be the same as the font size for the text? bold, but same size.
![Screenshot at 2021-06-19 15-49-18](https://user-images.githubusercontent.com/3437324/122644568-1d89fc00-d116-11eb-88e9-fed25d96eb1a.png)

**Comment by nguyenhongphat0** [comment]
Hide your name when pretends to be an audience will make your pretending more obvious (because audience have their name) 😆 
I suggest put your name after that - sign, for example: "-John I'm a real audience" will display John as the chat nickname. What do you think?

**Comment by helenvarley** [comment]
that sounds like a good solution :)

**Comment by nguyenhongphat0** [comment]
It is on dev-app now ☝️

**Comment by vickis** [comment]
Great solution  :)
If there is no name given after the - will the fake audience be assigned
the first word as a name by default

**Comment by helenvarley** [comment]
only if there is no space between the - and the first word.
so to make your fake audience name be bob, you need to type: -bob hi i'm bob
if you type -hi i'm bob then it will show your name as hi
if you type - hi i'm bob i think it will be with no name

**Comment by vickis** [comment]
roger that ;)
