### ISSUE TITLE
position of speech bubble when avatar is rotated

### ISSUE THREAD

**Issue by helenvarley** [upstage-org/mobilise#340]
we need to consider what happens to an avatar's speech bubble when the avatar is rotated. as this screengrab shows, if the avatar is "lying down" the speech bubble is pretty much unreadable.
probably the speech bubble should either stay always above and upright.
![Screenshot at 2021-05-17 11-25-05](https://user-images.githubusercontent.com/3437324/118486343-c7422b80-b719-11eb-8c3b-478626c55e9b.png)

**Comment by helenvarley** [comment]
![118476473-d6bb7780-b70d-11eb-8289-9e25933197b1](https://user-images.githubusercontent.com/3437324/118487461-0755de00-b71b-11eb-8ce9-8698384b3e4b.png)

**Comment by vickis** [comment]
Agree speech Bubble always aligns to top & bottom of the screen
