### ISSUE TITLE
minimum width of speech bubble

### ISSUE THREAD

**Issue by helenvarley** [upstage-org/mobilise#341]
there needs to be a minimum width for a speech bubble, so that even if an avatar is very tiny, its speech bubble is still readable. 
is it possible for the minimum width to adjust dynamically to the length of the longest word in whatever you have typed?
![Screenshot at 2021-05-17 11-06-53](https://user-images.githubusercontent.com/3437324/118486788-4afc1800-b71a-11eb-85ea-757c2bcedbb0.png)

**Comment by elisadcg** [comment]
We have to verify is the text inside the speech buble keep the normal behaviour of a text, wich is in CSS : 

word-break: normal;

**Comment by nguyenhongphat0** [comment]
> there needs to be a minimum width for a speech bubble, so that even if an avatar is very tiny, its speech bubble is still readable.

This got fixed 🙌 

> We have to verify is the text inside the speech buble keep the normal behaviour of a text, wich is in CSS : word-break: normal;

Yes `word-break: normal` is good but with a word that is too long (for example: a link), it will got overflow (screenshot). I guess `word-break: break-word` is the best choice 😅 
<img width="394" alt="Screenshot 2021-05-21 at 13 54 06" src="https://user-images.githubusercontent.com/29925961/119095084-0931e100-ba3c-11eb-8145-bfeacbead242.png">

**Comment by nguyenhongphat0** [comment]
Sorry, wrong button 😅 This should be closed after the pull request got approved

**Comment by helenvarley** [comment]
doesn't seem fixed yet?
![Screenshot at 2021-05-21 12-23-33](https://user-images.githubusercontent.com/3437324/119123063-7be88f80-ba2f-11eb-9b8e-2dcaf0a504f2.png)

**Comment by nguyenhongphat0** [comment]
It not yet approved, Helen 😅 I'll let you know when it's ready

**Comment by helenvarley** [comment]
i'm so impatient! :laughing:

**Comment by nguyenhongphat0** [comment]
It's on dev-app1 now, Helen ☝️

**Comment by helenvarley** [comment]
looks great! shall we close this then?

**Comment by nguyenhongphat0** [comment]
Yes please 🙏
