### ISSUE TITLE
workshop: media edit interface

### ISSUE THREAD

**Issue by helenvarley** [upstage-org/mobilise#35]
as a logged-in player, i expect to be able to access a media edit interface that provides a thumbnail preview of the media item along with tools to:
- edit information e.g. name, voice
- replace media item with a new file
- delete media item
- download media item

and showing information including:
- player who uploaded this item
- date of upload
- stages to which it is assigned
- permissions (e.g. anyone can use it / no-one can use it / use only with uploader's permission)

the current UpStage v3 media edit interface is quite good:
![image](https://user-images.githubusercontent.com/3437324/91061177-2744ef00-e62c-11ea-89f7-e22d441360ec.png)

**Comment by helenvarley** [comment]
the media management interfaces are looking good (https://app1.upstage.org.nz/V4.0/ui/dashboard/stage-management/U3RhZ2U6Mw==/media) but they are going to quickly become very crowded once there is a bit more media on it. 
as well as the filter for media type, can there be a filter for player/uploader, and a way to sort by date uploaded?

**Comment by elisadcg** [comment]
yes i think any filter would be relevant !

**Comment by helenvarley** [comment]
don't forget about the "replace" function - this is super useful when creating media, & trying things out on the stage. it's much easier & less confusing than deleting the media you don't want & uploading new, if from a media's edit screen you can simply choose to replace it with a new media file.

**Comment by elisadcg** [comment]
If it was on the edit media modal, then i suggest before the  Clear button. In not green neither red, better a orange one.

![issue35](https://user-images.githubusercontent.com/7611913/118495070-1e003300-b723-11eb-8e94-1d5625974e33.png)

I wonder why this modal need a lateral scroll, this behaviour is not responsive. should be 90% width and no need of horizontal scroll

**Comment by helenvarley** [comment]
yes it should be on the edit media interface, & yes an orange button is nice :)
there shouldn't need to be a scroll here - the "type" options can be a dropdown menu - better, as it can only be one type! no need to have all of the types visible as if you could select multiple types ...

**Comment by nguyenhongphat0** [comment]
> I wonder why this modal need a lateral scroll, this behaviour is not responsive. should be 90% width and no need of horizontal scroll

Sorry, I removed the scroll 😅 
I really hate these unnecessary scroll bar, trully! But since I switch to a Mac it's hard for me to notice, because the system keep hiding the scroll 🤣

**Comment by helenvarley** [comment]
can we have a "download" option on the media edit interface? it's sometimes very useful ... :)

**Comment by nguyenhongphat0** [comment]
A Download button will be do it 🙌

**Comment by nguyenhongphat0** [comment]
Here is the download button I've promised 😅 

<img width="1026" alt="Screenshot 2021-06-30 at 23 35 53" src="https://user-images.githubusercontent.com/29925961/123998717-f546ab00-d9fb-11eb-8557-88ec03cb494c.png">

**Comment by riadsalameh** [comment]
Hey everyone. I think using the save button for download can be a bit confusing. I can send @nguyenhongphat0 a new icon for the download option.

**Comment by nguyenhongphat0** [comment]
Yes please give me the icon you want to that button 🙌 
Should I change the "Save chat" button to "Download chat" 🤔 (in Stage management > Chat)

**Comment by nguyenhongphat0** [comment]
And a retro version of that edit icon should be great too @riadsalameh 
<img width="80" alt="Screenshot 2021-07-01 at 00 11 16" src="https://user-images.githubusercontent.com/29925961/124003233-e57d9580-da00-11eb-9503-751736042dbe.png">

**Comment by riadsalameh** [comment]
Those are the options that I was thinking of. Let me know your thoughts 

![Workshop Icons](https://user-images.githubusercontent.com/71765608/124016136-98d89100-d9e5-11eb-98f0-0d32b59c826e.jpg)

**Comment by vickis** [comment]
Great Riad!
the arrow to the line I read as download

Save has to be the floppy disc :)

**Comment by riadsalameh** [comment]
ahh yes!! I meant it as download, not as save.
 Sorry for the confusion

**Comment by vickis** [comment]
All good Riad :)

**Comment by nguyenhongphat0** [comment]
Great icons 🙌 Can you send me the svg version of them @riadsalameh 🙏

**Comment by helenvarley** [comment]
we don't yet have the possibility to REPLACE a media item with a new file. this is super useful, as often the first time you upload something and try it on stage you realise that it isn't quite right and have to remake it & reupload it. have the replace option reduces the amount of unwanted media left lying about on the server, as people usually forget to clean up. 
it should be an option in the media edit interface, to replace the media item with a new file.

and while i'm looking at the media edit interface: the preview of the media item is unnecessarily large, & it's a bit annoying having to move the cursor from bottom right to top left and back down again. is there a better layout that puts the things you need to click or edit closer together, and doesn't have such a huge preview? @elisadcg any suggestions?

**Comment by elisadcg** [comment]
![issue35-02](https://user-images.githubusercontent.com/7611913/126875306-316aee61-8230-48c8-bd73-47921b44300a.png)
I suggest this two proposals.
The first is not breaking too much the actual behaviour. But putting the Save button close to the X is "dangerous". But definitively, all pop up are very big and i think they are not very mobile compliant.
The preview can be visible only in the 50% of the window. And the second column show all option valuable.
Why not another pop up for just manage this opion ?

**Comment by helenvarley** [comment]
that's a good point about the mobile interface. we have said that players probably will not use a phone to perform, but uploading media from your phone will definitely be something people want to do.

**Comment by nguyenhongphat0** [comment]
Sorry for the late response 😅 Here is the screenshot of the new layout. Let me know if it look good to you:
<img width="1298" alt="Screenshot 2021-07-30 at 23 05 01" src="https://user-images.githubusercontent.com/29925961/127680639-da165fc3-2c27-48bd-a393-92ad1e904888.png">
<img width="1295" alt="Screenshot 2021-07-30 at 23 05 49" src="https://user-images.githubusercontent.com/29925961/127680724-960b00cb-9bbd-41db-a5eb-80e15a59d98f.png">

**Comment by nguyenhongphat0** [comment]
And by the way, can we take a look at the "rounded corners" proposal 😅? Things in 7-A39 look very stiff at the moment, some soft curving might make it look better. Let me know what you think about this 🙏

<img width="1440" alt="Screenshot 2021-07-30 at 23 27 55" src="https://user-images.githubusercontent.com/29925961/127683882-10c99986-6278-4a6c-b45f-08da610b784f.png">

<img width="1432" alt="Screenshot 2021-07-30 at 23 27 27" src="https://user-images.githubusercontent.com/29925961/127683884-a97f1ccc-8c14-4b17-8c54-fa4b6ef09a97.png">
  
<img width="1435" alt="Screenshot 2021-07-30 at 23 29 00" src="https://user-images.githubusercontent.com/29925961/127683864-a947f4a0-e3f8-4063-a7a5-2af08e686d2f.png">

**Comment by helenvarley** [comment]
rounded corners are fine by me, but does that fit with our pixelatet icon style? @riadsalameh @elisadcg ?

the layout is looking better to me. still quite a big window - the example is showing a backdrop which needs space, & the permissions, but what about when it's a small avatar or prop, or audio file? will the window adjust down in size or still be big? actually it's not such a problem when all the buttons etc are together at the top there.

could the replace button also go in the top? or is there a reason for putting it below the preview image?

does it fit ok on a mobile screen?

**Comment by nguyenhongphat0** [comment]
This is how it look on mobile screen. There is still some annoying scroll bars, but I should fix them after we finish discussing on how the mobile layout should look like:

<img width="369" alt="Screenshot 2021-07-31 at 16 01 53" src="https://user-images.githubusercontent.com/29925961/127734877-e45a08e4-5ec3-4a79-992e-780a3acc24d2.png">

> could the replace button also go in the top?

Yes we can 🙌

**Comment by nguyenhongphat0** [comment]
> could the replace button also go in the top?

Is that the right place for it 😅 And I make the popup not full screen anymore 👌 

<img width="1439" alt="Screenshot 2021-07-31 at 16 20 42" src="https://user-images.githubusercontent.com/29925961/127735365-636cd36c-9523-48ab-adc4-7a6523b67cde.png">

**Comment by helenvarley** [comment]
great! :)

**Comment by vickis** [comment]
I think the rounding is discrete enough to still fit with theme and do
soften the design :)
