### ISSUE TITLE
opacity slider functionality

### ISSUE THREAD

**Issue by helenvarley** [upstage-org/mobilise#350]
it doesn't seem possible to use the opacity slider to make an avatar or prop fade out gradually. if i adjust the opacity slider, regardless of how slowly the movement slider has been set or whether or not the live action bulb is on or off, it just goes immediately to whatever new opacity setting.
the movement speed slider seems to affect the speed of resizing, so couldn't this also affect the speed of opacity change? it would be great to be able to fade things in and out.

**Comment by vickis** [comment]
agree
gradual fade is really important
especially once we have streams and want to start mixing between visual
inputs :)

**Comment by elisadcg** [comment]
i resuggest a fade in or fade out button ^^

**Comment by helenvarley** [comment]
as well as the slider? as part of the slider? or a separate button that simply fades from 0 to 100% or the other way around?
would this work if we wanted to fade up to 50%?

**Comment by elisadcg** [comment]
i imagine this a separate button 0 to 100% (if it's visible, only fade out, and if it's visible fade in)
 For 50% ...mmm, could we imagine to get in the context menu the fade settings ?

**Comment by helenvarley** [comment]
:thinking: won't it be confusing to have two separate opacity tools? can we not have both functions in one?

**Comment by vickis** [comment]
Agree
The context menu is already quite busy
Fade happening at the speed the  action happened would avoid extra tools :)

**Comment by elisadcg** [comment]
i'm not seeing the button fade in or fade our like a opacity button, but like a quick action.
And for 50% let's just control the slider opacity ?

**Comment by helenvarley** [comment]
yes the opacity slider does not produce a fade in or out, it just changes the opacity immediately to the new setting. this is ok if you want that to happen, but more often i think we will want a media item to visibly fade in or out.

**Comment by vickis** [comment]
Agree yes gradual fade would be my preference
