### ISSUE TITLE
default avatar size

### ISSUE THREAD

**Issue by helenvarley** [upstage-org/mobilise#351]
when i place an avatar on stage, it appears by default as a standard small size. i then have to adjust it if i want it larger, and the audience can see this. i want to be able to resize the avatar before the audience can see it. 
i am not sure what the solution might be, but could we have something like theatre wings, or some way that we can prepare a little bit before appearing? 
maybe when you first drag an avatar onto the stage it is not on the stage, but on an interim overlay, where you can adjust its size, rotation, opacity etc and the right position, then make it appear?

**Comment by vickis** [comment]
i thought we discussed this in terms of published change (where it was
possible to make changes that were not visible to audience and publish them
to make them appear instant ...

**Comment by helenvarley** [comment]
that's the live action bulb (#288 ) - but i'm talking about when you first put the avatar onto the stage. you don't have access to the bulb until the avatar is on the stage. 
for example with the doctor in jeux de massacre, he should be much bigger when he first appears. but i have to place him on the stage first, as the default size, which the audience see, and then resize him. i would like him to appear at the larger size.

**Comment by vickis** [comment]
yes of course - sorry that's what i meant
perhaps by default the live action bulb needs to be unpublished so thsat an
avatar can be placed sized and any other settings confirmed before it
'appears' on stage for audiences
...

alternatively the avatar needs to appear on stage at the original size
setting (for larger avs)

**Comment by helenvarley** [comment]
maybe it would be a solution, that your media doesn't appear on the stage until you click the lightbulb. this way, you can drag the media to the place you want it, make it the size and opacity you want, & if it's a multiframe av you can select the frame you want. 
then click on the light bulb and voila, it appears.
this could also help to understand the lightbulb - when it's green the audience is seeing everything, when it's white the audience is not seeing anything.

**Comment by nguyenhongphat0** [comment]
So this is how the light bulb should works 🤦‍♂️ If it turn off means your changes to the avatar happens locally, and when it turn on the changes are visible to audiences. This light bulb make more senses and less crash 🙌

**Comment by helenvarley** [comment]
does this mean that the light bulb is off to start with, when you first drag an avatar to the stage? so that you can resize & position it & get the right frame & all that before making it visible?

**Comment by nguyenhongphat0** [comment]
Yes, when you place the avatar on the stage the lightbulb is off by default. But is it unconvienece? Because you will have to hit the light bulb on every new avatar 🤔

**Comment by helenvarley** [comment]
yes. this might be inconvenient - but let us try it, & see how it works. it's hard to know until we try :)

**Comment by nguyenhongphat0** [comment]
Hi @helenvarley, the new bulb is available at http://dev-app1.upstage.org.nz/ui/live/demo, you can try it. Here is a quick demo of how it's behaving right now:

https://user-images.githubusercontent.com/29925961/119836015-9210b700-bf2b-11eb-8a51-38cdeeda6dcd.mov

**Comment by helenvarley** [comment]
the video doesn't work ... but i will have a look soon on dev=app :)

**Comment by vickis** [comment]
Seems ok as also solution to having to resize in view of the audience
