### ISSUE TITLE
on stage - change "delete" to "remove"

### ISSUE THREAD

**Issue by helenvarley** [upstage-org/mobilise#353]
in the context menu for avatars, props, & other objects that can be placed on stage, let's use the word "remove" instead of "delete" - to avoid confusion with "deleting" a media item from the server.

- we upload or delete media to and from the server
- we assign or unassign media to and from a stage
- we place or remove media on or from a stage

**Comment by vickis** [comment]
yes agree better wording :)

**Comment by elisadcg** [comment]
![issue353](https://user-images.githubusercontent.com/7611913/118773538-3b4d1280-b885-11eb-9d74-b4989ab04dbb.png)
Yep and some other words fixes too

**Comment by helenvarley** [comment]
this is #260 - @nguyenhongphat0  please look at my comments at the end of #260

**Comment by nguyenhongphat0** [comment]
This issue is part of #260 , which got resolved 🎉
