### ISSUE TITLE
media upload layout

### ISSUE THREAD

**Issue by helenvarley** [upstage-org/mobilise#359]
If we decrease the black space we get this dialog smaller.
![issue347](https://user-images.githubusercontent.com/7611913/119098033-b2191580-ba15-11eb-8a31-68c2c6142bfc.png)
If the window is smaller, then the parts can go under
![issue347-b](https://user-images.githubusercontent.com/7611913/119098324-fe645580-ba15-11eb-8910-d2da87ff072e.png)

But i did not understand the multiframe tab.... we are in the media page. This dialog open when we edit an already media uploaded. For what purpose the artist need the multiframe tab ?

_Originally posted by @elisadcg in https://github.com/upstage-org/mobilise/issues/347#issuecomment-845723763_

**Comment by elisadcg** [comment]
I think all is done in this issue :) Great Job !
