### ISSUE TITLE
avatar names should stay as saved 

### ISSUE THREAD

**Issue by helenvarley** [upstage-org/mobilise#367]
every time an avatar is placed on stage, we have to reset the avatar name.
i have changed the names in the backstage, but on stage they are still appearing as the old names. we have to reset the name when we put the avatar onto the stage, and then if we take it off and put it on again, we have to rename it.
maybe this is already fixed in C3PO?

**Comment by nguyenhongphat0** [comment]
Yes this already fixed on C3PO. After you update the name in the backstage, new avatar placed on stage will use that new name instead 👌
