### ISSUE TITLE
can't move an avatar if it is behind another avatar

### ISSUE THREAD

**Issue by helenvarley** [upstage-org/mobilise#368]
if the avatar i'm holding is completely behind another avatar, i can't access the context menu to bring it to the front and i also can't drag it to move it.
the frame of the avatar seems to be square, rather than the dimensions of the image. the doctor:
![Screenshot at 2021-05-24 12-03-20](https://user-images.githubusercontent.com/3437324/119331947-3a065600-bc88-11eb-9b11-8fe59855eb1e.png)

**Comment by helenvarley** [comment]
![Screenshot at 2021-05-24 12-09-13](https://user-images.githubusercontent.com/3437324/119332479-ee07e100-bc88-11eb-8d72-f5d5dfed7409.png)

**Comment by elisadcg** [comment]
Mmm could we come back with the idea of the list of assets available in Scene Tool (like a layer dialog on a graphic app) ?

**Comment by helenvarley** [comment]
would this let you select & operate your avatar, even if it's behind other things?

**Comment by elisadcg** [comment]
If we want preview + name, then it could appear on top overlay. This allow selection, whatever their "z-index".
How do you think about helen ? And Phat ? Is it possible ?
![issue368](https://user-images.githubusercontent.com/7611913/119335020-11805b00-bc8c-11eb-822e-b0dfa0648645.png)

**Comment by helenvarley** [comment]
actually i'm not sure that this will help with the particular problem of not being able to operate your avatar when it is behind another media item - we need something quick & easy ...
when the media item on top is held by someone else, it shouldn't be possible for you to select it. so if your avatar is behind an avatar held by another player, you should still get your avatar's context menu when you right click there, & be able to drag your avatar to move it, since you should not be able to operate the one in front that is held by another player.
however we also have the same issue with props (see #58), & as props aren't held by a player, there needs to be another solution for that ...

**Comment by helenvarley** [comment]
but maybe the solution elisa proposes is the best one - thinking about it a bit more; if it's possible, it would solve the problem for props as well as avatars. & perhaps it's not going to be a situation we encounter too often in actual performance, as we will have worked through the issues ...

**Comment by helenvarley** [comment]
i realised that there was no issue specifically for the scene tool, so i have created one (#370)

**Comment by elisadcg** [comment]
In graphic app, if we do Ctrl+clic, we select under. Maybe this hotkey shoud be allowed here ?

**Comment by helenvarley** [comment]
how doesthat work when there are more than 2 things on top of each other?

**Comment by elisadcg** [comment]
if there are several items one on top the other, each time you hit Ctrl+click you go down of one level.
The problem after is to right click on it. Is not possible in this situation.
So maybe it could virtually go on top of all, but with less opacity to show it's "virtual" then you can right click on it to navigate in the context menu.
Then when you de-hold it, it's come back under the other media.

**Comment by vickis** [comment]
Ctrl click is a good solution but you need to know how many layers are
between the top a and your one to get to it
I think the ‘layer’ selection is probably best generally (perhaps ctrl
click also exists but to be sure you are always getting the right object in
stage a layers function is available

**Comment by helenvarley** [comment]
the square frame is really a problem. the frame of a graphic media item should fit to the dimensions of that item. otherwise it takes up much more space than necessary.
![Screenshot at 2021-05-27 12-35-09](https://user-images.githubusercontent.com/3437324/119812193-2fe29280-bee8-11eb-94ee-084e7893bde7.png)

**Comment by vickis** [comment]
It may be a hard one to change as it’s pretty standard graphic scenario...
also if the dimensions change for a wide short object what happens to the
sliders (should they follow the longest dimension? )

**Comment by nguyenhongphat0** [comment]
I believe this issue is resolved using the Depth tools. Futher issue about the Depth tools should happens in #389 🥶
