### ISSUE TITLE
"scene" function

### ISSUE THREAD

**Issue by helenvarley** [upstage-org/mobilise#370]
the idea of the on-stage "scene" tool is that an arrangement of media can be saved and activated as the start of a new scene. when the specific scene is selected and activated, the backdrop and media items appear in the positions and sizes that they have been preset in, and if audio has been saved as well this starts playing. this will allow players to have everything for the new scene appear at the same time, in the right place, and it can cue the scene for all players.

when the "scene" toggle in the toolbar is activated, a list of pre-saved scenes appears and the player can select the one they want.

there is also the possibility that the media for that scene can be displayed in the top bar, so that media items can be selected there if they are behind others. (but would this show only the media saved for that scene, or also other media added after the scene starts?)

**Comment by elisadcg** [comment]
You right. It's better keep what he have thinked.
Scene tool, after choose wich scene, you see all the media assign.
And then you can go throught this list to select the one wich is under another one to move it.
When it selected in this overlay, the right click have to be functional.
And all the media added have to appear here too.
![issue370](https://user-images.githubusercontent.com/7611913/119346331-5e6b2e00-bc9a-11eb-9ca5-8d3864c286f6.png)

**Comment by vickis** [comment]
the scene took works like a library
Archiving the placement and settings to be re- activated when selected -
once the action starts if that scene is selected again it should return to
the preset state

**Comment by nguyenhongphat0** [comment]
Instead of display Scene 1, Scene 2 and the media list, I propose displaying screenshots of these scenes on the top bar. What would you think 🤔 ?

![](https://user-images.githubusercontent.com/7611913/119346331-5e6b2e00-bc9a-11eb-9ca5-8d3864c286f6.png)

**Comment by helenvarley** [comment]
the curtain looks great! :)
could there be two (or 3) options for how it closes & opens?

1. drops down and lifts up (as it currently does, but a little slower)
2. fades in/out
3. closes from the sides in and opens from the middle out

**Comment by helenvarley** [comment]
just saw that the secen tool is also there! :+1: 
i think we need to be able to name a scene when we save it, as there could be multiple scenes with the same backdrop so difficult to tell the difference without a name.

**Comment by vickis** [comment]
Agree - perhaps even just numbers to avoid lengthy texts

**Comment by nguyenhongphat0** [comment]
Got this, you will be asked for scene name when saving 👌 
<img width="663" alt="Screenshot 2021-07-05 at 16 59 45" src="https://user-images.githubusercontent.com/29925961/124454362-9a71d280-ddb2-11eb-9f5c-84b948db5c12.png">

**Comment by nguyenhongphat0** [comment]
> the curtain looks great! :)
> could there be two (or 3) options for how it closes & opens?
> 
> 1. drops down and lifts up (as it currently does, but a little slower)
> 2. fades in/out
> 3. closes from the sides in and opens from the middle out

The animation will be slower 👌

About the third animation (closes from the sides), I have to "double" the curtain (one for the left and one for the right side) to implement to transition, so it would make your curtain look quite repeated (screenshot) 😅
<img width="1434" alt="Screenshot 2021-07-08 at 22 04 44" src="https://user-images.githubusercontent.com/29925961/124945610-8212e980-e038-11eb-9b6d-1e40fcf1c9a5.png">

**Comment by vickis** [comment]
Fabulous Phat
Great solution :)

**Comment by helenvarley** [comment]
looks great :)
