### ISSUE TITLE
layout of admin / player management

### ISSUE THREAD

**Issue by helenvarley** [upstage-org/mobilise#375]
the layout of the admin interface for player management needs improvement. rather than have all of the players showing all the time, under the menu options of registration approval, reset password, switch role, etc., i want to be able to access a player's profile and make various changes to that one player, without having to go back to the list each time.
i would like to have:

- a list of all players, that is searchable and sortable (alphabetically, chronologically and by role)
- when i click on a player, i get their profile, and can make all of the changes i want there in the popup profile window (accessible currently from "profile management"

**Comment by nguyenhongphat0** [comment]
> i want to be able to access a player's profile and make various changes to that one player, without having to go back to the list each time

That would be easier to use 👍 Here is the new layout, everything is under 1 table, and you can filter players by role or name/nickname/email:

<img width="1433" alt="Screenshot 2021-08-08 at 21 23 21" src="https://user-images.githubusercontent.com/29925961/128635515-843d1c93-5872-4abb-9b5c-b2d099d3edf3.png">

**Comment by helenvarley** [comment]
awesome!! :clap:

**Comment by vickis** [comment]
great work! :)
