### ISSUE TITLE
"guest" role

### ISSUE THREAD

**Issue by helenvarley** [upstage-org/mobilise#376]
we need a role that is "guest": players with this role can access the on-stage tools on stages that the player is assigned to, but in the backstage they cannot upload or edit media, or create or edit stages.
this role is needed for workshop situations, where participants are learning how to use UpStage but may never go further with it. if they are interested to keep working in UpStage we can then create their own account and then they have backstage access.
we can change the password for the guest accounts between workshops (see issue #375 - would be great to be able to do this as a batch, rather than individually ... )

**Comment by nguyenhongphat0** [comment]
I believe this issue is resolved as part of #2 , we now have an admin section to batch create guest user, and we can change a role of user to/from Guest, allow them to upload and create media and stages

**Comment by helenvarley** [comment]
great! can we also batch-change the password? i.e. select 10 guest accounts and change all the passwords in one go? i did a change yesterday & it was good that the same password appeared for each one i had to change :)
