### ISSUE TITLE
finding players to assign to stage

### ISSUE THREAD

**Issue by helenvarley** [upstage-org/mobilise#377]
in the stage management interface, i can search the list of players to find the one that i want to assign to the stage. however this list only shows the "display name" of the player. i wanted to add elisa, but i didn't know that her "display name" is chut, so i could not find her. i had to go to the admin section and look through the list of players and found that her username is elisa, and her display name is chut.
is there a way that, when i type "elisa" into the search field for player access, that it can also find the player who has "elisa" in their username or email address?

**Comment by elisadcg** [comment]
Player access list should be propose some filters like : first name, last name, nickname.

![issue-377](https://user-images.githubusercontent.com/7611913/122542347-e1c63800-d02a-11eb-8975-876f16c4127a.png)

**Comment by helenvarley** [comment]
or can it be more simple? for example if i type "elisa" in the search field, can the search look for any "elisa" in the players' names and email addresses, and offer any matches, from which i can select the right one?

**Comment by elisadcg** [comment]
if it's allowed yes ! it would be mervellous !

**Comment by nguyenhongphat0** [comment]
We already have that search box, it is looking for nickname only. I can match the searching keyword with full name and username as well 👌

**Comment by vickis** [comment]
Yes good idea Phat!
 as sometimes nicknames are not common and not naturally associated with a
player

**Comment by helenvarley** [comment]
great!
