### ISSUE TITLE
dfference between username and chat nickname

### ISSUE THREAD

**Issue by helenvarley** [upstage-org/mobilise#385]
during our LGM demo on thursday, i changed my nickname from helen (my username) to bob, to demonstrate how we could have different nicknames in the chat.
on sunday i uploaded some media and discovered that the owner of the media shows as "bob".
when i saw this, i went onto a stage and changed my nickname back to helen, and now i see in that the media i uploaded as "bob" is now shown as uploaded by "helen". 

changing your chat nickname should not change your username. otherwise it's very confusing - when i've changed my nickname in the chat, all of my stages and media are showing as owned by bob. another player, looking to enter a stage i've uploaded or find media i've uploaded, won't be able to find it, and for me it's also confusing. as admins we may need to do things for other players, and we won't be able to find things if they have forgotten that they changed their nickname in the chat.

you username should always be what you log in with, and shown for your media and stages. you should not be able to change your username.
your nickname should be your username by default, and on the live stage you can change it. but this should only be on that stage and for that live session. when you leave that stage, and re-enter that stage or another stage, your nickname should default back to your username.

**Comment by nguyenhongphat0** [comment]
Done, this got rolled to dev2 🙌
