### ISSUE TITLE
costume prop

### ISSUE THREAD

**Issue by helenvarley** [upstage-org/mobilise#388]
As a player on the stage, i want to attach a prop to the avatar that i'm holding, so that it moves around the stage with the avatar when i move it.
for example: my avatar puts on a hat that is a prop. i need to be able to resize the prop and then attach it to the head of the avatar.
i also need to be able to remove it when i want to.
if i remove the avatar from the stage while the prop is still attached to it, the prop should also be removed from the stage.

**Comment by elisadcg** [comment]
I suggest, in media managment we can attach prop for an avatar.
In stage, when we place the avatar, the overlay appear with their prop.
When we place the prop in stage, and turn the light bulb in green, then the prop moove with avatar.
How do you think @helenvarley & @vickis ?

**Comment by helenvarley** [comment]
this wouldn't really be any different to having a multiframe avatar, with the prop in one frame, and switching to that frame. 
& it wouldn't allow us to spontaneously take a prop and add it ...
i think we need a way to be able to select a prop and somehow stick it to the avatar we are holding - this can only be done when you are holding an avatar. maybe a right-click in the prop that is "add to avatar" ?

**Comment by elisadcg** [comment]
How the tool understand wich avatar ? The next click show it the good avatar ?

**Comment by helenvarley** [comment]
it could only be attached to the avatar you, the player, are holding. so, you have to be holding an avatar already, before you chose the prop. then in the context menu of the prop, there could be the option "add to avatar". if you aren't holding an avatar, this option would be greyed out and not do anything.
once the prop has been added to the avatar, it moves with it, scales & fades & rotates with the avatar; & the "add to avatar" menu option would change to "remove from avatar". selecting that would release the prop from the avatar, and then you could click on the prop's x to remove it from the stage or manipulate it without the avatar.
probably when the prop is attached to the avatar, its frame and controls should not appear. i think that mostly i would want the prop to move, fade, resize etc along with the avatar. maybe there would be a situation where you want the prop to rotate or something, but then i think it would be enough that you remove the prop, rotate it, then reattach it.
(it will probably take us a bit of time to learn & experiment with this!)

**Comment by nguyenhongphat0** [comment]
I propose a new tab in Media Create/Edit interface, called Costume. From that tab you can put as many props as you want around your avatar. And then you hit save, I will save it into a frame of your avatar's multiframes. Is this sound good?

**Comment by helenvarley** [comment]
that might be good in some situations, but it wouldn't allow for spontaneously adding a prop during a performance, which is what we really want ...

**Comment by vickis** [comment]
Agree
Your solution is great Phat but could be replicated other ways as Helen
suggests

The issue seems to be ensuring UpStage understands when you select a prop
you are still holding your last active avatar so it can be attached

This would need to detect your if you have an active avatar onstage not
just the last avatar you held, to allow us to float a prop around if
required

**Comment by nguyenhongphat0** [comment]
Prop now have the Add to avatar and Remove from avatar option. After wearing a costume, the prop will move/resize along with the avatar 👌 

<img width="763" alt="Screenshot 2021-06-26 at 11 38 01" src="https://user-images.githubusercontent.com/29925961/123501994-08135580-d673-11eb-81fa-f95ab6840bf6.png">

**Comment by helenvarley** [comment]
great! i will test after this weekend (when festival is over ... )

**Comment by helenvarley** [comment]
great! this might need some tweaks though ... for example, i have a star on my forehead, and everything is fine, it moves with the avatar and scales and fades, but when i rotate ...
![Screenshot at 2021-06-29 22-44-55](https://user-images.githubusercontent.com/3437324/123865090-c8c35e00-d92b-11eb-92f6-e40d2219398d.png)
![Screenshot at 2021-06-29 22-45-15](https://user-images.githubusercontent.com/3437324/123865102-cb25b800-d92b-11eb-8249-74d13e331107.png)
![Screenshot at 2021-06-29 22-45-35](https://user-images.githubusercontent.com/3437324/123865105-cc56e500-d92b-11eb-91d0-eda3a52f8a80.png)

**Comment by elisadcg** [comment]
i don't know how to re open it, someone ?

**Comment by nguyenhongphat0** [comment]
After some crazy computation, I manage to make the costume stay at the same position on the avatar after rotating. However during the animation you won't be able to see it "rotate along" with your avatar (see the below video). Hope you are fine with this 🙏 
https://user-images.githubusercontent.com/29925961/123946768-c9123680-d9c9-11eb-9c85-3839bda7e4a9.mp4

**Comment by helenvarley** [comment]
very awesome - but still not quite there ... i put the star on my head, rotate, and the star is ... not any more on my head ... (maybe it's just not possible? have we finally exceeded the limits of possibility???)
![Screenshot at 2021-06-30 17-27-36](https://user-images.githubusercontent.com/3437324/123988911-b2b7ab00-d9c8-11eb-9c31-75d143131984.png)
![Screenshot at 2021-06-30 17-28-00](https://user-images.githubusercontent.com/3437324/123988916-b4816e80-d9c8-11eb-8976-1521ced06b40.png)

**Comment by nguyenhongphat0** [comment]
I found another way to implement the rotating. This time you can see the actual rotate animation 🎉 But the bad news is, after you "detach" the prop from the avatar, it will jump back to the previous position (when it was attached to the avatar). This is the most I can do, sorry 😓 
https://user-images.githubusercontent.com/29925961/124082240-adb13500-da76-11eb-8025-a34543bf19a9.mp4

**Comment by vickis** [comment]
Oh we have been asking the near impossible for sometime
Amazingly Phat and the dev team are conjuring magic!

**Comment by nguyenhongphat0** [comment]
It's not near impossible, Vicki. It was because this takes a lot of time to do, but have so little value, I would prefer spending time working on these other issue, such as the curtain or the scene at the moment. If we are not happy with the current costume rotate. I will spend more time on it after these other issue are finished 👌

**Comment by vickis** [comment]
agree Phat!

I think we have other more crucial elements as although not 'on the fly'
we can achieve the look of the appearance of a prop which acts the same as
an avatar by maling the avatar as a multiframe :)

keep up the great work :)

**Comment by helenvarley** [comment]
> I found another way to implement the rotating. This time you can see the actual rotate animation tada But the bad news is, after you "detach" the prop from the avatar, it will jump back to the previous position (when it was attached to the avatar). This is the most I can do, sorry sweat
> https://user-images.githubusercontent.com/29925961/124082240-adb13500-da76-11eb-8025-a34543bf19a9.mp4

this is great, phat. & it's not such a big problem that the prop jumps back when detached, as you can also remove the prop, which takes it off stage; & this might be what you want to do anyway. i think we can work with this :)

**Comment by vickis** [comment]
Great work!
