### ISSUE TITLE
depth tool

### ISSUE THREAD

**Issue by helenvarley** [upstage-org/mobilise#389]
the depth tool works great for being able to move your avatar when it is behind another avatar or prop. 
but, we cannot access the context menu, the light bulb or the x of the avatar that is behind.
could these things be accessible from the top bar, where we can drag the icon?

**Comment by vickis** [comment]
The context meu might work like the semi transparent screen o drawing
Wen you are moving an avatar between layers or across stage you als have
access to all ways you can manipulate the avatar

**Comment by helenvarley** [comment]
yesterday we discovered that it is possible to move an avatar that's held by someone else, using the depth tool. this was handy yesterday as vicki's connection had dropped but she was still showing as being on the stage and her avatar was sitting in the middle, and no one else could operate it. so we were able to drag it to the side using the depth tool. but this is not really how the depth tool should work, you should only be able to move the one that you are holding.

**Comment by elisadcg** [comment]
Probably when we select an avatar with depht tool, it could be "falsy" on top of all avatar . Just few second, time for artist to adjust it and get accessible the context menu.
problem :  
![issue-389-depht](https://user-images.githubusercontent.com/7611913/122540016-809d6500-d028-11eb-8b80-828aa38d1ec1.gif)

**Comment by helenvarley** [comment]
could the "falsy" float on top, only seen by the player, so that you could access the tools? & if you resize or whatever, this makes the change on the avatar behind?

**Comment by nguyenhongphat0** [comment]
Okay so when you select an avatar with the depth tool, your avatar will be "falsy" float on top, so that you can access the context menu and move and do whatever you want. Other audiences will still see your avatar at the correct depth 👌 

Example:
<img width="1297" alt="Screenshot 2021-06-19 at 13 44 18" src="https://user-images.githubusercontent.com/29925961/122633776-7ea8d400-d104-11eb-90f6-a3facf3cd628.png">
How the audience or other players see:
<img width="1297" alt="Screenshot 2021-06-19 at 13 44 06" src="https://user-images.githubusercontent.com/29925961/122633782-88323c00-d104-11eb-979d-cae374a4a59d.png">

**Comment by helenvarley** [comment]
great! this is really good :)
i see it works just with a roll over on the depth toolbar, you don't need to click :)
the one trick is that you have to already be holding an avatar before it's hidden behind another object, otherwise you get the frame & can move it, but don't get the context menu or lightbulb. double-clicking on the falsy doesn't allow you to hold it.
let's try it as it is for now, & see if we manage or if there needs to be a way to hold an avatar that's hidden as well.

**Comment by nguyenhongphat0** [comment]
> the one trick is that you have to already be holding an avatar before it's hidden behind another object

You can click the avatar on the depth toolbar to hold it (if it is not being held by someone else)

**Comment by helenvarley** [comment]
another thought about the depth toolbar: is it possible to re-order objects there by dragging them in the toolbar? 
for example if the left-hand end is the furtherest back, and the right-hand end is the one at the front, could you drag an icon in that toolbar to reorder it on the stage?

**Comment by nguyenhongphat0** [comment]
Yes you can drag an object to a new position in the depth tool, so that their depth level will change. It was the main usage of the depth tool 😆

**Comment by helenvarley** [comment]
should that be working now on dev-app? i'm trying but it doesn't work ... :thinking:

**Comment by nguyenhongphat0** [comment]
Oops, sorry, my bug 😅 It got fixed, pls wait for the next pull request 🙏

**Comment by helenvarley** [comment]
i think we also need something to make the depth tool bar different to the avatar or props bar - i am getting mixed up, thinking i have the depth bar when it's the avatar one, or vice versa :laughing:

**Comment by nguyenhongphat0** [comment]
Would you like a diffrent color for each tool on the stage 😂 I can make it look like a rainbow, but I hope it's not too much!

**Comment by helenvarley** [comment]
could be something like that - let's get input from @elisadcg & @vickis on this one :)

**Comment by nguyenhongphat0** [comment]
Let's make another issue for it 👌 
I fixed the bug. This issue is resolved 🙌
