### ISSUE TITLE
stage: removing inappropriate links from the chat

### ISSUE THREAD

**Issue by helenvarley** [upstage-org/mobilise#40]
as a logged-in player on a stage, i expect to have the ability to remove a link that has been posted into the chat, if it is for any reason inappropriate.

**Comment by elisadcg** [comment]
This means that artist who lead the show, and audience loggin-in player can remove the link posted into the chat ?

**Comment by helenvarley** [comment]
good question. there could be a situation where a player is logged in, but not assigned to a stage, so they are in the audience; & it's easier for them to remove something offensive from the chat than for the performing players to have to take care of that as well.

and, perhaps audience members should be able to remove their own comments? if someone writes something that's a bit offensive or stupid & then regrets it? but this could be complicated ...

i am imagining that an intuitive way to make this work would be to be able to right-click on a line of text & get a contextual menu with the option to delete/remove that line.

**Comment by helenvarley** [comment]
questions to answer:
- how can an inappropriate link be removed from the chat?
- WHO should be able to do this? any logged-in player who is on that stage? or only players who have player access on the stage?
- should anyone be able to delete their own chat messages?
- should players be able to delete others' chat messages?

**Comment by nguyenhongphat0** [comment]
This issue is not too complicated to implement (in technical view). We just have to clear these questions above and I will jump to it 👌

**Comment by elisadcg** [comment]
In my opinion 
- players can remove all messages from the audience and him in his accessible stage
- one can always remove his own message

**Comment by vickis** [comment]
Agree
Player has ultimate editing  control in chat :)

**Comment by helenvarley** [comment]
ok; but any logged in player? or only those who have player access to that stage? i think probably it should be only those who have player access to that stage.
so it would be:
- anyone (including audience) can remove their own message (links & text)
- a logged in player, who has player access on that stage, can remove any message (links & text) 

the way to remove would be to hover over the message & get a delete option.

**Comment by elisadcg** [comment]
me too

**Comment by helenvarley** [comment]
an artist has asked if it's possible to highlight a line of chat in some way. if there's going to be a hover or right-click menu to delete chat, could that menu include an option to highlight? (i know, it's a new issue ... )

**Comment by helenvarley** [comment]
great! :)
