### ISSUE TITLE
stage: hide player nickname

### ISSUE THREAD

**Issue by helenvarley** [upstage-org/mobilise#41]
as a logged-in player, i expect to be able to hide my nickname in the chat window if i want my text to appear as anonymous audience text.

**Comment by elisadcg** [comment]
not yet implemented ?

**Comment by helenvarley** [comment]
actually this is maybe irrelevant now, since audience members have nicknames too, so there isn't the same kind of anonymous text chat that we used to have in UpStage. & i just tried having a username that is a blank space, and this works; so i will close this issue :)
