### ISSUE TITLE
"ghost player" - need a way to remove

### ISSUE THREAD

**Issue by helenvarley** [upstage-org/mobilise#413]
yesterday in our rehearsal, vicki lost her internet connection, but for some time after she was still showing up in the player counter list, and the avatar she had been holding remained visible on the stage, held by her. no one else could operate the avatar. (we eventually found we could move it using the depth tool, which was handy, but really that's a bug - it shouldn't be possible to move an avatar held by someone else).

we need a way to be able to remove ghost players, if for some reason the system doesn't register it. could it be something like a right-click on that player's name in the counter list, & an option to remove from the stage? then this would release the avatar if they are holding one. 

it could also be useful to have this remove option for audience, if someone was being really obnoxious ... we have NEVER had that in all of UpStage's long and glorious history, but now that we are perched on the edge of famousity, we probably should anticipate it ...

**Comment by vickis** [comment]
ooh weird i had closed out and restarted
- def needs to be sorted

**Comment by nguyenhongphat0** [comment]
> we eventually found we could move it using the depth tool

Yes that is a bug 😆 And I realize that we don't need to drag the avatar on the depth tool to move it to the new position, since now we have the "falsy" float on top, we can move the avatar more easier when they are behinds another avatar/prop.

So instead, we can drag the avatar out of the depth tool, to remove the ghost player. Here is an example, let me know what you think:
https://user-images.githubusercontent.com/29925961/122634109-8e291c80-d106-11eb-9459-58ffea0ba919.mov

**Comment by helenvarley** [comment]
that looks like a good solution - and i wonder, maybe it's a good way not only to remove a ghost player but also to remove any avatar or prop that is behind something? the other way is to hover over the tool bar to get the falsy and then click the x on the falsy, so maybe dragging it off the bar would be a bit more intuitive?

**Comment by nguyenhongphat0** [comment]
That would be great 🙌

**Comment by nguyenhongphat0** [comment]
You can now use the depth tool to remove any object from the stage, so use it carefully, since you can remove someone else's holding avatar 😅 But don't worry, I prompt a warning before you do that 👌

**Comment by vickis** [comment]
Super! :)
