### ISSUE TITLE
how to assign a stream to a stage?

### ISSUE THREAD

**Issue by helenvarley** [upstage-org/mobilise#418]
at the moment, when you start a stream, it can be accessed on all stages. streams need to be assigned to a specific stage - how can we do this?
streams must only appear on the specific stage
![Screenshot at 2021-06-18 16-19-08](https://user-images.githubusercontent.com/3437324/122575625-3aa8c700-d051-11eb-9c01-d1c2602c13f5.png)
![Screenshot at 2021-06-18 16-18-25](https://user-images.githubusercontent.com/3437324/122575630-3bd9f400-d051-11eb-8e11-b03c51b6bc75.png)
![Screenshot at 2021-06-18 16-22-53](https://user-images.githubusercontent.com/3437324/122575991-8b202480-d051-11eb-96b2-648cc6e07d01.png)
![Screenshot at 2021-06-18 16-18-22](https://user-images.githubusercontent.com/3437324/122575629-3b415d80-d051-11eb-9900-70c3f569e274.png)

**Comment by nguyenhongphat0** [comment]
You can create an RTMP Stream in Media page, that way you can assign a stream to a specific stage, and it will always be there no matter you turn on or off your stream source.

<img width="1351" alt="Screenshot 2021-06-18 at 21 49 11" src="https://user-images.githubusercontent.com/29925961/122579374-0ba94a00-d07f-11eb-8ea8-0926c3620f4e.png">

> at the moment, when you start a stream, it can be accessed on all stages

I did this on purpose, so that you can put your stream on the stage without the hairy configurations. Should I disable this feature 🤔

**Comment by helenvarley** [comment]
ah., interesting! i will have to test this - tomorrow; i have to go out now.
but then how does it work if someone just starts streaming, and it appears on all stages? should it be that you always need to first create the rtmp stream and assign it to the stage?

**Comment by nguyenhongphat0** [comment]
Yes we can turn off the auto detect live streams so that we always have to create the backstage stream first!

**Comment by helenvarley** [comment]
great!
could this be a setting in the on-stage setting tool? because it could be cool if you could at some point invite an audience member to send a stream, for example. or if someone's stream failed and another player needed to jump in with a stream that hadn't been pre-assigned to the stage.
if that's too tricky, then the priority would be to turn off auto=detect for live streams.

**Comment by nguyenhongphat0** [comment]
Okay we can turn on that switch, to enable auto live streams detection. The default is off 👌 

<img width="1423" alt="Screenshot 2021-06-20 at 01 43 45" src="https://user-images.githubusercontent.com/29925961/122664038-fa6c5480-d1c8-11eb-9c7a-34fa6b3ac821.png">

**Comment by vickis** [comment]
Great! Creating a stream ‘av’ to assign to a stage makes sense
And the auto detect ability adds another layer of lively possibility :)
