### ISSUE TITLE
differentiated tool bars

### ISSUE THREAD

**Issue by helenvarley** [upstage-org/mobilise#421]
it is easy to get confused between the depth tool bar and the avatar or prop tool bar, as when you have several media items on the stage the depth tool bar starts to look like the avatar or props bar. how can we make it easy to always know which tool bar you have open?
- different coloured backgrounds?
- an icon at the beginning that is the same as the avatar, prop or depth tool icon?
- something else?

**Comment by vickis** [comment]
Could there be a small z added to the thumbnail?
Or the background of the toolbar be stripped (yellow / black like hazard
tape )

**Comment by nguyenhongphat0** [comment]
Have we jump into conclusion yet? 😅

**Comment by helenvarley** [comment]
no :laughing:  
i don't think a striped background would be good, as it might make it difficult to differentiate icons on that bar (for example in jeux de massacre there are several very similar avs)
could we try a different coloured background, just one flat (light) colour? this might also give problems with some icons, if they merge into the colour, but this could happen with any colour of course.
i am a bit out of ideas for the moment but will keep thinking about it.

**Comment by nguyenhongphat0** [comment]
I painted a different colour for each toolbar, let me know if it look good to you 🙌 
And if you would like to change them to another colour that you want, just send me the specific colour code for each toolbar  👌

**Comment by vickis** [comment]
That looks great Phat
I think a different colour for each palette is a great idea - (could w
chose a palette in stage settings somehow

also it seems that the text tool is broken
my internet is being super flakey so after my workshop tomorrow i will test
it again but it appeared i couldn't save text....

**Comment by helenvarley** [comment]
great! :) let's try it out & see if there might be any tweaks needed.

**Comment by nguyenhongphat0** [comment]
So should I switch the colour between the Depth tool and the Curtain 🤔

**Comment by helenvarley** [comment]
yes, try that :)

**Comment by helenvarley** [comment]
looks good to me!

**Comment by helenvarley** [comment]
@vickis if you're happy also with the dark background for the depth tool then i think we can close this one.

**Comment by vickis** [comment]
I like the dark backgrounds for curtain and depth yes

**Comment by helenvarley** [comment]
the curtain has a light background now, it's only the depth tool with a dark background.
for me that works, as the depth tool is the one most easy to get mixed up with the avatar or props toolbar. the curtain one is pretty obvious what it is.

**Comment by vickis** [comment]
all good :)
