### ISSUE TITLE
depth tool: stream identification

### ISSUE THREAD

**Issue by helenvarley** [upstage-org/mobilise#425]
when there are streams on the stage, these show up in the depth tool as the default icon. when there are several streams on the stage, i need to be able to identify which is which in the depth tool.
would displaying the stream key be a solution?

**Comment by nguyenhongphat0** [comment]
> would displaying the stream key be a solution?

Yes, stream now being displayed as a stream icon with key below it, on the the depth tool (screenshot) 👍 

<img width="471" alt="Screenshot 2021-07-10 at 13 18 14" src="https://user-images.githubusercontent.com/29925961/125153926-4c2d4c80-e181-11eb-8baf-2a88ce988778.png">

**Comment by vickis** [comment]
that's great Phat! :)
