### ISSUE TITLE
resizing frame not immediately accessible when placing avatar or prop on stage

### ISSUE THREAD

**Issue by helenvarley** [upstage-org/mobilise#427]
when i first drag an avatar or prop onto the stage, the resizing frame is not accessible. i have to click away on another part of the stage and then click on the avatar or prop again in order to be able to resize it.
resizing is usually the first thing we want to do before making the avatar visible, so it would be good if the frame was immediately visible.

**Comment by vickis** [comment]
Agree resize active you default is useful
