### ISSUE TITLE
audio toolbar - track names hidden on chrome

### ISSUE THREAD

**Issue by helenvarley** [upstage-org/mobilise#428]
on chrome and chromium, the track names in the audio toolbar are partially hidden by the scroll bar:
![Screenshot at 2021-06-21 18-24-34](https://user-images.githubusercontent.com/3437324/122796010-36cdac80-d2be-11eb-9815-ef3a6022c669.png)

**Comment by helenvarley** [comment]
![screenshot-doris](https://user-images.githubusercontent.com/3437324/122806243-62ef2a80-d2ca-11eb-9e7e-f60ae53ac303.jpg)

**Comment by nguyenhongphat0** [comment]
Hi Helen, this got fixed 👌 

<img width="1308" alt="Screenshot 2021-06-22 at 00 55 19" src="https://user-images.githubusercontent.com/29925961/122806475-8fb83780-d2f4-11eb-9459-c7d3830548b3.png">

**Comment by helenvarley** [comment]
has anbody ever told you how utterly awesome you are, phat? :smile: :clap: :clap:

**Comment by nguyenhongphat0** [comment]
Thank you for your compliment @helenvarley . And the answer is no 🤷‍♂️

**Comment by helenvarley** [comment]
well that's something we can fix! you are UTTERLY AWESOME!!!!!

**Comment by vickis** [comment]
Oh I cannot believe no one has defined your awesomeness Phat - upStage
brings out the awesome in everyone and definitely working on you - thanks
so much for your superb work :D

**Comment by nguyenhongphat0** [comment]
Thank you everyone 🙏
