### ISSUE TITLE
stage: show player nickname

### ISSUE THREAD

**Issue by helenvarley** [upstage-org/mobilise#43]
as a logged-in player, i expect my nickname to show in the chat window with my text when i am not holding an avatar.

**Comment by elisadcg** [comment]
it was the same as #44 ?

**Comment by helenvarley** [comment]
no - this is for logged-in players, not audience. 
until now, if a player is not holding an avatar and they enter chat, it appears as audience chat input. this is really useful, we often want to pretend to be audience ;)  if the player is holding an avatar, then their chat appears with the name of the avatar.

so now, when the audience has the option to have a nickname (or not), what does this mean for the player when not holding an avatar & typing in the chat? are they anonymous? can they also have the option to show a nickname? should it be their player username? or any nickname that they choose, similar to how the audience can choose a nickname?

**Comment by elisadcg** [comment]
Ok i think this point is more a discussion between artist and dev will make their magic. After that we can style the chat-bubble-text for each "statement" (player, anonymous, logged-in)... right ?

**Comment by helenvarley** [comment]
this is solved - the player name appears if you are not holding an avatar, and you can change your name to just be a space if you want to be anonymous.
