### ISSUE TITLE
best proportions for stage cover image?

### ISSUE THREAD

**Issue by helenvarley** [upstage-org/mobilise#431]
today i made a stage cover image for the mobilise-demobilise stage, and thought i'd positioned it well for the text and everything. it's great in full screen, but if you aren't in full screen then it's too big and doesn't all display ...
can there be a way to make the cover image resize automatically or somehow display better, no matter what size people have their browser at?
and / or recommendations in the manual for the best dimensions?
(i'm tagging this with backdrops as well, as i think often the cover image will be a backdrop from a performance with some text added, so it would be good if they could be same dimensions)

![Screenshot at 2021-06-21 20-01-54](https://user-images.githubusercontent.com/3437324/122807376-cd549a80-d2cb-11eb-9ea2-91765eecc60f.png)
![Screenshot at 2021-06-21 20-00-29](https://user-images.githubusercontent.com/3437324/122807379-cded3100-d2cb-11eb-950a-7d47eb08bd33.png)

**Comment by vickis** [comment]
This could by default scale to 100%
On upload we should ensure there is  some white space around the border and
remember he screen realestate given for chat (even though chat window can
be minimised

**Comment by helenvarley** [comment]
the chat doesn't appear on the cover image - the example i've used is an image that is a screengrab from the live stage, not the actual chat window.

**Comment by helenvarley** [comment]
awesome work! :)
