### ISSUE TITLE
video is squashed and jerky

### ISSUE THREAD

**Issue by helenvarley** [upstage-org/mobilise#435]
when you first drag a video onto the stage, it is squashed and square. it's possible to get the right shape but only by first putting a frame onto it and then taking it off and resizing it.
the video playback is very jerky, unless the video is kept very small.
![Screenshot at 2021-06-22 22-47-35](https://user-images.githubusercontent.com/3437324/122997141-fba9a700-d3ab-11eb-9fe5-e17f02eca668.png)

**Comment by nguyenhongphat0** [comment]
This issue is resolved as part of #458. When you drag a video on stage, it will have the rectangle shape (as the size of the stream). The jerkiness is gone as well 🙌
