### ISSUE TITLE
clear chat doesn't work properly

### ISSUE THREAD

**Issue by helenvarley** [upstage-org/mobilise#437]
after clicking "clear chat and sweep stage", and then "save stage" (just in case) there is still one line of chat showing in the chat window of the stage, and the chat is still all there on the chat page in stage management.

**Comment by helenvarley** [comment]
this has happened on both Mobilise-Demobilise and Jeux de Massacre stages. 

it's also strange that there is no option to clear the chat, on the Chat page.

**Comment by nguyenhongphat0** [comment]
This issue is resolved as part of #245 🙌

**Comment by helenvarley** [comment]
fixed :)
