### ISSUE TITLE
stage: audience nicknames

### ISSUE THREAD

**Issue by helenvarley** [upstage-org/mobilise#44]
as an audience member on a stage, i expect to have the option to choose a nickname when i enter the stage; if i don't choose a nickname, my chat will appear anonymously, without any preceeding nickname.

**Comment by elisadcg** [comment]
![issue44-01](https://user-images.githubusercontent.com/7611913/98101705-e4f12700-1e92-11eb-8dc3-488ee65a89d1.png)

Ok i imagine this possibility above the chat.
Choice between 1 and 2 : the 1 show all others option aboves the chat
or option 2 : the audience member has just the possibility to change his name, and zoom in text, zoom out text ?

Last, i think it's a good idea to make his own participation of the chat visible ? Does it make sens ?

**Comment by helenvarley** [comment]
i go for option 2, that the audience has the font size adjustment buttons and the nickname change option there under the chat.

re having the chat on alternating sides - this could be good. do you mean that it is just your own chat that appears right-aligned? or all audience, with the players left aligned? maybe there's an argument for having all audience chat input right-aligned? this would make it easier to read just the player text, or just the audience chat, if you wanted to.

maybe there's also an argument for having just your own text right-aligned. @vickis @petyrv - do you have thoughts about how it would work in performance?

**Comment by elisadcg** [comment]
In ergonomie, we learn that a text with left-align is more quickly readable and less effort. And text with align center are So that's why i imagine a difference by his own chat text in different styled (and choose the harder one). And the idea to get the entire chat in right-align, be careful ^^.
![issue44-02](https://user-images.githubusercontent.com/7611913/98215591-47582f00-1f48-11eb-9455-3651609dbd00.png)

**Comment by helenvarley** [comment]
yes, i find left-aligned easiest to read. let's keep this idea of separating or distinguishing one's own chat input for a bit further along, when we can try it out & see how it works & feels.

**Comment by nguyenhongphat0** [comment]
Wow I didn't know about this issue when I building the chat box and nicknames, sorry 😅 Now we are able to change (and save) the nickname, I hope this issue is resolved!

**Comment by vickis** [comment]
super great work Phat
