### ISSUE TITLE
on-stage sweep button?

### ISSUE THREAD

**Issue by helenvarley** [upstage-org/mobilise#445]
now that we have a "clear chat" button in the on-stage stage settings, i'm wondering if it would also be useful to have a "sweep stage" button there as well? for times when you just want to remove everything all at once?

**Comment by vickis** [comment]
Agree that Woukd be great - especially for piles of drawings :)

**Comment by elisadcg** [comment]
i think a button like this already exist in Dashboard and General Information.

**Comment by nguyenhongphat0** [comment]
Yes and @helenvarley want it on-stage 😆 
She's so greedy 😈

**Comment by elisadcg** [comment]
maybe it's the time to think in the scene tool ?

**Comment by vickis** [comment]
Great thinking - so in the scene tool the current stage is saved and can be
swept clear?

**Comment by nguyenhongphat0** [comment]
We now have the "Blank Scene" button (on the scene tool) which will do what an on-stage sweep button does 👍

**Comment by vickis** [comment]
..super! :)
