### ISSUE TITLE
hearing last line of previos text spoken again when entering stage

### ISSUE THREAD

**Issue by helenvarley** [upstage-org/mobilise#455]
this bug was fixed but today i'm hearing it again (on dev-app1), both as a logged in player and as audience: when i enter the stage, the last line of avatar text is spoken again.

**Comment by helenvarley** [comment]
sad to say but i heard the last line of text spoken as i entered the demo stage as audience today ...

**Comment by nguyenhongphat0** [comment]
Can you make a fresh reload on dev-app1, Helen 🤔 I can't re-produce this bug, look like it is caching issue

**Comment by vickis** [comment]
Agree i didn’t hear it

**Comment by helenvarley** [comment]
ok, i cleared cache & everything & reloaded & didn't hear it, so let's close this one again (until it rears its ugly head again!)

**Comment by helenvarley** [comment]
sorry phat, i'm reopening this one ... i am in the demo stage as audience, i cleared the cache today & then have left that window open while doing other things. the wifi is quite flaky & it just disconnected, then shortly after reconnecting (without having even looked at the tab with the stage open) i got a replay of all the voices from before, not just the last line but all of it from "true" etc ...

**Comment by nguyenhongphat0** [comment]
> i got a replay of all the voices from before, not just the last line but all of it from "true" etc ...

This was fixed in pull request #471. It looks like this issue doesn't happens anymore, let's close it 🙌
