### ISSUE TITLE
as audience, seeing avatar frame and able to move and rotate avatar

### ISSUE THREAD

**Issue by helenvarley** [upstage-org/mobilise#456]
this might be the poltergeist bug!
as an audience member, not logged in, i can see the green frame around an avatar, i can rotate it and i can move it!!
this happened with a prop.
but it doesn't happen all the time.
i can also see some media items that do not have the lightbulb turned on, greyed out.
![Screenshot at 2021-07-04 18-17-59](https://user-images.githubusercontent.com/3437324/124392109-325cb700-dcf4-11eb-9792-8f92443d3681.png)

![Screenshot at 2021-07-04 18-10-36](https://user-images.githubusercontent.com/3437324/124391939-58358c00-dcf3-11eb-9934-091f60b61666.png)

**Comment by gloriajw** [comment]
Ah, good, this makes me feel better.

**Comment by helenvarley** [comment]
yes - it explains the twirling & moving - if people could see the frame, then some of them for sure would be inspired to fiddle with it!! but maybe not all could see it, or not all the time? anyway, the audience should NEVER see it :laughing:

**Comment by helenvarley** [comment]
but - there are also some strange things to do with logging in & out. when i went in before, i used cromium & did not log in, & showed up as audience. but now i opened chromium again, & went to the stage without logging in - and found that i could see all the tools. but i was showing as 1 audience member ...
does the log-in somehow connnect to the IP address? (it should not ... )

**Comment by gloriajw** [comment]
This sounds like more caching issues. Nothing is bound to IP address.

**Comment by helenvarley** [comment]
ok. i cleared my cache & entered the stage again as audience. this time i don't see the frames on media items that were already on the stage, but i can edit the text object on the stage. and, when i put a new avatar onto the stage (i am logged in in firefox, and audience in chromium), then in audience view i can see the frame and i can scale, rotate and move the new avatar.

**Comment by nguyenhongphat0** [comment]
Uugh new features come with lots of impact on old features, sorry about this 🤦 Fixing...

**Comment by helenvarley** [comment]
i'm not seeing the frames now, which is great :)
but i am, as audience, still sometimes seeing greyed out props which do not have their lightbulb on. i tried to work out if this was because i had entered the stage after the props were put on, or if it was that their light bulbs had been on and then off again, but i can't manage to replicate it.
![Screenshot at 2021-07-05 16-50-44](https://user-images.githubusercontent.com/3437324/124489723-9abd9e00-ddb1-11eb-8538-e78f87936ce9.png)
![Screenshot at 2021-07-05 16-50-26](https://user-images.githubusercontent.com/3437324/124489725-9beecb00-ddb1-11eb-96c9-7a9f3d54596e.png)

**Comment by helenvarley** [comment]
as audience, able to manipulate stream ...
![Screenshot at 2021-07-05 17-01-27](https://user-images.githubusercontent.com/3437324/124490849-e15fc800-ddb2-11eb-8e2c-61b12ccff56d.png)

**Comment by nguyenhongphat0** [comment]
> but i am, as audience, still sometimes seeing greyed out props which do not have their lightbulb on

It was a bug with the "save scene" feature, which got fixed. However, these scenes that was saved before the bug fix might still have gray out objects. I've prune them all 👌

**Comment by vickis** [comment]
super! :)
