### ISSUE TITLE
streaming improvements

### ISSUE THREAD

**Issue by helenvarley** [upstage-org/mobilise#458]
at our last dev meeting, we agreed that if the jerkiness and latency in streams is (partly?) caused by Canvas, which is required to make the shapes on the streams, that we would prefer smoother and less laggy streams than the optoin to have circles etc.
we need to see how much better the streams work when the shapes are taken off.
the initial re-size of a stream is very slow, but maybe this will also improve without canvas.

**Comment by gloriajw** [comment]
@nguyenhongphat0 can the canvas be removed completely when rendering a video? I'm not sure about this. 
I am also not sure if it is jerky for everyone. It seemed smooth for others when we tested, and Helen's machine kept overheating. 
I thought we all agreed that the jerkiness was due to a graphics card issue on an old machine.

**Comment by nguyenhongphat0** [comment]
Yes we don't need canvas to plqy a stream, canvas is only required for shaping. About the jerkyness, it is not happening on my end, at least until we have 5 or more streams on the stage at the same time. It could also so network issue, not just graphic card!

**Comment by vickis** [comment]
Also not jerky
But sometimes network latency for me
I can try and be on a faster network for the artist meet tonight and we can
test again
:)

**Comment by helenvarley** [comment]
but we don't know what kind of machines the audience will have; i think we can assume that most will not have high-end systems. also how good are the streams on tablets & phones?
we will need to make a compromise, but we want it to be good for most people. 
we also need to load test - it might be fine for 3-4 simulataneous streams when there are only 4-5 people on the stage, but when there are 50, will it still be ok?
