### ISSUE TITLE
audience entering live stage

### ISSUE THREAD

**Issue by helenvarley** [upstage-org/mobilise#459]
i think we can make some improvements on how the audience enter the live stage. at the moment, the popup window emphasises the nickname field, the writing underneath that field is pretty small and i don't really pay any attention to it.
instead of "Welcome to UpStage" could the heading of this popup window say "Click anywhere to enter the stage"
and then underneath that, above the nickname field, "Choose a nickname if you want one:"
i think it's not necessary to say "welcome to UpStage" on this window.
![Screenshot at 2021-07-05 17-07-50](https://user-images.githubusercontent.com/3437324/124491543-b0cc5e00-ddb3-11eb-962d-32e9ea2261cc.png)

**Comment by vickis** [comment]
Agree text change to click anywhere Works :)
