### ISSUE TITLE
streams: audio muted locally as default

### ISSUE THREAD

**Issue by helenvarley** [upstage-org/mobilise#467]
when i send an audio stream, or video and audio stream, it should be locally muted by default - that is, i don't want to hear my own audio.

**Comment by vickis** [comment]
Agree that would useful :)
Looking forward to playing with streams locally :)

**Comment by helenvarley** [comment]
and the audio should not be heard by anyone until lightbulb is on

**Comment by nguyenhongphat0** [comment]
This is now available on dev-app1!

> and the audio should not be heard by anyone until lightbulb is on

No one except you will see or hear your stream until you turn on the light bulb, Helen. However, after you turn on the light bulb for the first time, and then turn it off, other would still hear you but they just don't see you resize/rotate/move your stream around.

**Comment by vickis** [comment]
something to be aware of (eg locally mute audio if 'disappearing for
awhile ) and will perhaps  be an interesting device! :)

**Comment by helenvarley** [comment]
this is great phat :)
but on more thing :wink: - sometimes you do want to hear the stream, for example if i have put the stream onto the stage but it is coming from the phone of someone who is out in the street. 
can the mute icon in the bottom right corner be clicked to turn the sound on if you want it?

**Comment by nguyenhongphat0** [comment]
Yes I will do that 👌

**Comment by nguyenhongphat0** [comment]
It is now on dev-app1 🙌

**Comment by helenvarley** [comment]
i don't see a way to un-mute if i want to hear my local stream - how can i do that?

**Comment by nguyenhongphat0** [comment]
You can click on the mute icon to mute/unmute it. Sorry I forgot to switch the branch on dev-app1, that's why you don't see the changes 😅
