### ISSUE TITLE
different media in audience and player view

### ISSUE THREAD

**Issue by helenvarley** [upstage-org/mobilise#468]
i just went to check if the frames are still showing in audience view (they don't seem to be) and found that i am seeing different media on the stage in the audience and player views:
![Screenshot at 2021-07-11 15-00-22](https://user-images.githubusercontent.com/3437324/125181446-eca27000-e258-11eb-824a-1da25021a410.png)
![Screenshot at 2021-07-11 15-00-05](https://user-images.githubusercontent.com/3437324/125181448-ef04ca00-e258-11eb-9438-fcdfeaffc7f7.png)

**Comment by nguyenhongphat0** [comment]
This was a bug with the Blank Scene feature, which got fixed. Sorry about that 😅
