### ISSUE TITLE
different coloured backgrounds on same stage

### ISSUE THREAD

**Issue by helenvarley** [upstage-org/mobilise#473]
i am seeing different coloured backrgounds on https://dev-app1.upstage.org.nz/V4.0/ui/live/upstage_team, as a logged in player on firefox and an audience member on chromium. i haven't changed the backdrop colour since entering.

and when i was on the demo stage, as audience in chromium it is just entirely black, i don't see anything ...

![Screenshot at 2021-07-14 17-48-58](https://user-images.githubusercontent.com/3437324/125569767-262562f1-4b95-4f63-b691-62ae9d020015.png)
![Screenshot at 2021-07-14 17-48-43](https://user-images.githubusercontent.com/3437324/125569783-937b07d4-cc40-4267-945d-0dd4ae457727.png)

**Comment by helenvarley** [comment]
also i just noticed, there is a typo in the green welcome message at top right - it should say "Your nickname is ... " (not "You nickname"

![Screenshot at 2021-07-14 17-51-02](https://user-images.githubusercontent.com/3437324/125569986-0aab2a6c-6cff-4651-9270-b68a093981e1.png)

**Comment by nguyenhongphat0** [comment]
Sorry for the black screen, it was fixed 😅

**Comment by helenvarley** [comment]
thanks @nguyenhongphat0 :clap:
