### ISSUE TITLE
stage status: live, upcoming or rehearsal

### ISSUE THREAD

**Issue by helenvarley** [upstage-org/mobilise#476]
in stage management we can set the status of a stage to live, upcoming or rehearsal - but what does this actually do?
is it:
- "live" means that the stage is featured on the Foyer page, and audience can enter.
- "upcoming" means that the stage is featured on the Foyer page, but audience can't enter
- "rehearsal" means that the stage is not featured on the Foyer page, and audience can't enter

**Comment by nguyenhongphat0** [comment]
Exactly, these status will decide which stage are shown on the Foyer, at what position. Is it what we expect? 🤔 

<img width="1171" alt="Screenshot 2021-07-17 at 21 05 27" src="https://user-images.githubusercontent.com/29925961/126039530-b176f39a-1dbf-43f9-9b55-8407f8c17cd1.png">

Technically, when a stage is hidden away from the foyer, audience can still enter the stage if they have the url of the stage. For example: go to http://dev-app1.upstage.org.nz/demo will load the stage for you, no matter if I set it status to upcoming. It just they will see nothing, just like go the the cinema without any movie are shown.

**Comment by vickis** [comment]
Sounds good  :)

**Comment by helenvarley** [comment]
great. we need to reqork the Foyer page - @riadsalameh is going to look at that when he has finished his studies - as sometimes there will be no live or upcoming shows, & it needs to be customisable for others who host their own UpStage instance. 

if the audience can still technically see any stage if they have the url, what exactly happens? do they really see "nothing" or do they see the cover image or can they actually enter - for example if we are rehearsing, they could just enter and see what we are doing? this is in fact how it's always been in the past for UpStage, but we never had an automated system that put the live or upcoming shows on a publicly accessible page. 
is it not possible to make it that audience cannot enter untli the stage is made "live"? they just arrive at the cover image and instead of the stage loading message they get some other message saying that this stage is not currently open to the public?

**Comment by vickis** [comment]
yes like the 'cover image' lockable foyer

once the show is due to be live then allowing them in to chat and see the
curtain will be great also!
vicki :)

**Comment by nguyenhongphat0** [comment]
> they just arrive at the cover image and instead of the stage loading message they get some other message saying that this stage is not currently open to the public?

Will do 🙌

**Comment by nguyenhongphat0** [comment]
Sorry for the late implement 😅 Since upcoming stage could not be entered anymore, I brought back the UpStage logo on the top right, so that audience can click on it to exit the stage. Unfortunately, it got conflicted with your beautiful cover, sorry 😆 

<img width="1328" alt="Screenshot 2021-09-13 at 23 26 01" src="https://user-images.githubusercontent.com/29925961/133121467-73bf58ea-5bad-4d2b-bd63-c5e30c346cad.png">
