### ISSUE TITLE
player access to stage - how to remove individual players?

### ISSUE THREAD

**Issue by helenvarley** [upstage-org/mobilise#478]
it seems not possible, or at least not intuitive, to remove players from having player or edit access to a stage.
- to give individual players access, i just click on their name in the list and they jump over to the right. to give them edit access as well, i click on the individual's name at it jumps to the right.
- if i've given 5 individual players player access, and want to give all of them edit access as well, i can click on the >> button without selecting an individual player's name, and the whole list jumps over; this is quite good, as often we will want the whole player team to have edit access to the stage.

but if i want to take away that access - clicking on an individual name in the "player and edit access" list does nothing. if i search for the name, so that only that player is displayed in the list, and click on the << button - the whole list jumps back one column. this also happens if i try to remove an individual from the "player" column - clicking on their name moves them right to the "player and edit" column, and searching for their name then clicking on the << button moves the entire list of names back to the "audience access only" column.

there needs to be a way to remove an individual. i guess what would make most sense is if clicking on the name does not automatically move it to the new list - it just selects it. then you have to click >> or << depending on which way you want to move the individual.
in this scenario it would be helpful to be able to select multiple but not necessarily consecutive players by holding down the ctrl key.

**Comment by nguyenhongphat0** [comment]
Try right click on the name, Helen. Left click will promote a user permission, right click will demote it.
About the >>, I will take a look. Thank you

**Comment by helenvarley** [comment]
ahah!! good trick - but not at all obvious. we need to add the instruction, perhaps on the left there underneath "Player access":

"Click on a player's name to move them to the column to the right. Use a right-click to move them back to the left."

**Comment by helenvarley** [comment]
i just saw that this instruction is already there at the end of the player list. but i didn't see this before as it's further down the screen, i only saw it when i scrolled down. i think it would be more visible if it is at the left, underneath the heading "Player access"

**Comment by nguyenhongphat0** [comment]
That would look better 👍 
<img width="1046" alt="Screenshot 2021-07-17 at 22 32 45" src="https://user-images.githubusercontent.com/29925961/126041991-145cf2b3-42ee-4e22-9d76-5dad6e430b6d.png">

**Comment by vickis** [comment]
Great :)

**Comment by nguyenhongphat0** [comment]
The >> and << button now only transfer filtered players, not the entire list. I believe this issue is resolved  👍
