### ISSUE TITLE
Erase part or all of a drawing

### ISSUE THREAD

**Issue by helenvarley** [upstage-org/mobilise#48]
as a logged-in player on a stage, i expect to be able to select and erase part or all of a drawing i have made.

previously in UpStage it has only been possible to clear an entire layer, which means that if you make a mistake or for whatever reason want to remove part of what you've drawn, you have to remove the entire thing.

could there be one button to clear the whole layer, & another that is an eraser tool that can be used to rub out any part of a drawing? an "undo" feature that allowed you to undo the immediately previous line would also be useful.

**Comment by vickis** [comment]
superb work on the drawing tool @nguyenhongphat0  :D
