### ISSUE TITLE
stage management interface layout - stage ratio

### ISSUE THREAD

**Issue by helenvarley** [upstage-org/mobilise#480]
in the Customisation section of Stage Management, the Stage Ratio options take up a massive amount of screen real estate for what they are. it's good to be able to see the difference, especially the live adjustment with the custom ratio, but there's really no need for them to be so huge.
at the moment there is not a lot on this screen so it's not a big deal, but i can imagine that there could be more settings here - for example it might be useful to be able to set the background colour for the stage here, and other things that we'll think of as we go.

**Comment by vickis** [comment]
Sure Ok by me :)
We can set Te background onstage also
Once we find the ‘other things’  perhaps we could the ask for an adjustment
here  :)

**Comment by helenvarley** [comment]
yes good idea. let's start a list for things that could be in the customisation section:

- [ ] background colour
- [ ] chat window position - earlier we talked about having the option to have the chat window on the left or the right, i know this hasn't been implemented yet but i'm guessing it isn't a hugely difficult thing, so when it does get done then this would be the place to set it, as part of the layout
- [ ] curtain image? are we going to have the option to upload our own curtain image? if so that could also be here
- [ ] audience participation - also not yet developed or even imagined, but if we come up with more possibilities for the audience, such as polls or other things, they could be turned on & confiugred here
- [ ] anything else?

**Comment by nguyenhongphat0** [comment]
Curtain can be uploaded just like other media type, in Media page. Just like shapes, curtains is system wide, which means you don't have to go to each stage to assign a curtain.

<img width="353" alt="Screenshot 2021-07-22 at 11 56 31" src="https://user-images.githubusercontent.com/29925961/126591735-9bcce79c-34eb-4e8f-b193-ebb87c3fe5b1.png">

I will implement Chat window position in the Settings tool 👌 And I don't think it's necessary for chat window position and background color in backstage, they already on the Settings tool, where you can see the change immediately without having to save and reload,...

**Comment by helenvarley** [comment]
yes that's true - if we can do things on the stage, where we can see what the result is, then it's probably not necessary to also have it in the stage management.
the only thing that it might be useful for is similar to the avatar voices - if you want something e.g. a background colour to be there every time you go to the stage, and then changed during the performance, there might be a reason to have a setting in the stage management that is the default setting for the stage. but let's not worry about that now, let's first start using it & then see whether something like that would be useful or not.

**Comment by vickis** [comment]
Awesome work Phat!
This will be excellent for shows very exciting!

**Comment by nguyenhongphat0** [comment]
Here you go:

- Chat position in Settings tool:
<img width="1382" alt="Screenshot 2021-07-22 at 21 59 30" src="https://user-images.githubusercontent.com/29925961/126661620-2ae9a2c7-d200-4c6b-95eb-a82c08663138.png">

- Refactored stage customisation page, smaller ratio section
<img width="1431" alt="Screenshot 2021-07-22 at 21 58 18" src="https://user-images.githubusercontent.com/29925961/126661497-d8d91e02-1271-416a-97ec-ffcc5b16f354.png">

Let me know if it looks good to you 🙌
