### ISSUE TITLE
stopped stream visible to audience

### ISSUE THREAD

**Issue by helenvarley** [upstage-org/mobilise#485]
if a stopped stream has been left on the stage, it is visible to both player and audience when they enter the stage as a status bar trying to connect.
this is ok for the players to see, but for the audience it would be better that if there is no stream, or the connection is lost to the stream, that the audience sees either the last frame of the stream or nothing at all.
![Screenshot at 2021-07-19 14-40-01](https://user-images.githubusercontent.com/3437324/126095154-738195fa-d07d-4c59-9b16-d70a948f5f05.png)

**Comment by nguyenhongphat0** [comment]
These stream that are not running anymore will automatically be cleanup up, audiences won't see them anymore 🙌
