### ISSUE TITLE
 change text for logging in at stage

### ISSUE THREAD

**Issue by helenvarley** [upstage-org/mobilise#487]
the hover message on the popup window for logging in at the live stage needs to be changed. currently it says "Has an account? Please login instead to use the performance tools!"
i don't know if we really even need a tool tip here at all, since the button text "player login" is pretty self explanatory. only players who have access to the stage will be able to access the on-stage tools, & there will often be players who are just coming as audience. 
@vickis any thoughts? no tool tip needed?

![stage_login_1](https://user-images.githubusercontent.com/3437324/126102245-26fa4d7a-6278-4275-a1a3-0e3b55f6bbbd.png)

**Comment by vickis** [comment]
agree :)
not needed

**Comment by helenvarley** [comment]
i'm still seeing that tool tip text ... ??

**Comment by nguyenhongphat0** [comment]
Oh sorry, I forgot to switch dev-app1 to the new branch 😅 Can you check again, thank you 🙏
