### ISSUE TITLE
creating a stream media item

### ISSUE THREAD

**Issue by helenvarley** [upstage-org/mobilise#493]
in the media management window for creating a new stream media item, it shows the unique key as 179754f4f45c45dbaf106aa9095d5c42 - why? wouldn't it be better to say something like "your_stream_key" ? and then to write underneath that this should be replaced with the same name or key that is used in OBS, Larix or whatever streaming application is being used?
also on this screen, it says "Use this URL to publish your stream: rtmp://streaming1.upstage.org.nz:1941/live/179754f4f45c45dbaf106aa9095d5c42"
how can this be edited, for example if the university installs its own UpStage or we are hosting a separate instance for it, and a separate streaming server is being used?
isn't it a bit risky to have our upstage.org.nz streaming url in the code? even here on github, as it's publicly visible so potentially could be used by anyone to stream anything, & cost us the data ... ??
![Screenshot at 2021-07-21 22-16-20](https://user-images.githubusercontent.com/3437324/126474158-88af200c-92fe-496e-bb4c-c57ca3183583.png)

**Comment by gloriajw** [comment]
I'll look into how to wrap permissions around this without affecting the functionality.

**Comment by vickis** [comment]
Great hands Gloria
Agree having ability to mask sounds sensible and to edit stream name so we
can call the stream something we want be excellent :)

**Comment by vickis** [comment]
Great *thanks!
Although I have to say you three are pretty handy with the code ha ah :)

**Comment by nguyenhongphat0** [comment]
> in the media management window for creating a new stream media item, it shows the unique key as 179754f4f45c45dbaf106aa9095d5c42 - why? wouldn't it be better to say something like "your_stream_key" ?

Well we used uuid v4 to generate the stream key whenever you want to create a new stream. uuid v4 can make sure that the key is always unique, but it's not really easy to look/remember 😅 I replace it with "your_stream_key" and add a unique check server side, which mean you can never save 2 stream with the same key anymore 👌 

> also on this screen, it says "Use this URL to publish your stream: rtmp://streaming1.upstage.org.nz:1941/live/179754f4f45c45dbaf106aa9095d5c42"
how can this be edited, for example if the university installs its own UpStage or we are hosting a separate instance for it, and a separate streaming server is being used?

All the url in our system (API, MQTT, Streaming,...) is configured in Vue's config file. When we setup a separated instance of UpStage, we will need to update all of these information because each instance would have their own sub component (I guess), so it would be better to put them all in one place

> isn't it a bit risky to have our upstage.org.nz streaming url in the code? even here on github, as it's publicly visible so potentially could be used by anyone to stream anything, & cost us the data ... ??

Now we're required to provide a correct sign in order to publish to our streams, and the correct sign is only returned to the stream owner and no one else, so you don't have to worry about this 💪

**Comment by helenvarley** [comment]
i scanned the QR code but i have no idea how to get the stream key into larix???

**Comment by nguyenhongphat0** [comment]
After you scan the QR Code, a new connection with the same name as your stream media will automatically created. You just have to choose it and start streaming

![streaming](https://user-images.githubusercontent.com/29925961/130399614-404f6b6a-6a21-4c29-ab4d-db95bf6674ca.jpg)

**Comment by helenvarley** [comment]
unfortunately that doesn't happen for me. i guess it's because i've got an old phone & old version of larix. i will have to upgrade everything soon, but until then is it possible for me to stream from larix? i can do it from OBS, but would be good also to have the larix option. & we do need to consider that other users may also be on older phones ...

**Comment by nguyenhongphat0** [comment]
<img width="1111" alt="Screenshot 2021-08-27 at 11 31 47" src="https://user-images.githubusercontent.com/29925961/131213767-d69acfcb-bf7e-489b-bb7e-945b8b6c143f.png">

The issue was because of wrong stream key. I don't know how but your stream key appear to be a stream link 🤣 After updated your stream key to "helen" it works fine 👌

**Comment by vickis** [comment]
i cannot seem to save my stream
i can access media by typing in the url - but not through using the links
in backstage ...

[image: image.png]

**Comment by nguyenhongphat0** [comment]
I cannot see you image, Vicky 😅 

It show "[image: image.png]"

**Comment by vickis** [comment]
sorry i successfully made a stream this morning - so the issue i was having
i resolved myself ...
might have been my very flakey internet

**Comment by vickis** [comment]
update i have made a stream but cannot seem to get either obs or larix to
access it....

**Comment by nguyenhongphat0** [comment]
I see your stream in Backstage, and it look good. What was the error code that Larix/OBS gave you, Vicky?

**Comment by vickis** [comment]
Yes thanks phat :)
We had a session with interAkt and during that I got obs working last night
but not larix
Will try again today and screen grab the error Message

**Comment by vickis** [comment]
![image](https://user-images.githubusercontent.com/4249450/131595655-20096017-5693-4f70-9926-9057129cc523.png)

i can stream via OBS - but even with typing the entire URL (including vicki?sign=...) I cannot seem to get Larix to stream into UpStage

**Comment by vickis** [comment]
the above was the Larix stream before OBS stream had arrived 
now when i pull the stream onto stage it seems to show the first few frames then stop (as i have stopped OBS anyway)

**Comment by vickis** [comment]
It seems my stream key has changed? 
![image](https://user-images.githubusercontent.com/4249450/131596665-1a1fff3e-f912-432a-8e73-8ba8005c9d60.png)
![image](https://user-images.githubusercontent.com/4249450/131596886-5e83713b-4fb6-4eda-9d8e-c66cd971f045.png)

**Comment by vickis** [comment]
was successfully atreaming last night... from OBS

**Comment by vickis** [comment]
changing the stream key gave me a few seconds of stream then froze again ....

**Comment by helenvarley** [comment]
i've managed to get the stream working on OBS & Larix now (not at the same time - it's the same stream key). 
with larix, i can't use the qr code because of old version; so i copied & pasted the key from OBS. the first time i put this in, it didn't work - it said unknown connection error. i checked and it was all exactly right. there was a line break happening between the server url & the stream key, so i did a backspace - which took out the / - and then replaced the /
after this it worked.

**Comment by vickis** [comment]
cool i have managed to sort OBS with only a 16sec lag (most likely my local
wifi)
so i set up a new stream specifically for larix

this is what the QR scan returns ...
larix://set/v1?conn[][url]=rtmp%3A%2F%2Fstreaming1.upstage.org.nz
<http://2fstreaming1.upstage.org.nz/>
%3A1941%2Flive%2Fvickistream%3Fsign%3D1646022473-7754337e78e9aeb47666f63ed024d6ba&conn[][name]=vickistream&conn[][overwrite]=on

i have not managed my phone to automatically send that to larix so cannot
choose it as a connection have to manually set it up ...

couldn't get that going and also couldn't then get obs to stream - again
saying issue with connection to server
am chunking through data trying to resolve this so might leave it for a day
or so

hmmm i am baffled by this

**Comment by helenvarley** [comment]
@vickis have you tried manually entering the server url & stream key into larix? (same as what you have in OBS) that's what i've done & it works.

**Comment by vickis** [comment]
yep

**Comment by nguyenhongphat0** [comment]
Hi Vicki, do you still having issue when trying to publish your stream?

**Comment by vickis** [comment]
Yes
I am thinking there might be a conflict with my network
We are in lock down right now but in a week I should be able to move to a
venue with good internet
Will try everything out again then :)

In the meantime should the unique string keep changing?
That is at least one thing I have noticed

**Comment by helenvarley** [comment]
the unique string should last for 6 months, that was what we agreed at the last meeting. mine is still working, i used it again last night & have not had to change it since i got it working last week.

**Comment by nguyenhongphat0** [comment]
Yes the sign can be used up to 6 months, and also yes that it will keep changing, and these signs have different time to live. For example: the sign you copied yesterday will have 5 months and 29 day to live, while the current key will have exactly 6 months

**Comment by vickis** [comment]
I got both streams working properly just now 
what i realise now is that each time you open the OBS instructions it gives you a new string .... 

part of the issue is related to the local internet being a bit intermittent i think :)

![image](https://user-images.githubusercontent.com/4249450/131947610-614daa22-4c28-4eaf-b082-3636237e21bb.png)

**Comment by vickis** [comment]
will test again on fast internet next week hopefully :)
