### ISSUE TITLE
on-stage tool bar - order of tools

### ISSUE THREAD

**Issue by helenvarley** [upstage-org/mobilise#495]
i'd like to propose a re-ordering of the tools in the left-hand tool bar on the stage, to group them together more logically:

- Audio
- Backdrops
- Avatars
- Props
- Streams
- Drawing
- Text
- Depth
- Curtain
- Scenes
- Settings
- Player Chat

this way the Depth tool comes at the end of all of the graphical media which are the ones that need the depth tool, followed by curtain and scenes together, then settings and lastly the player chat, so that this is easy to find quickly when you need it.

**Comment by helenvarley** [comment]
and maybe also some separators might help too - between Audio & Backdrops, between Text & Depth, and between Scenes and Settings - what do you think?

**Comment by vickis** [comment]
Agree with the list arrangement and with the seperators that would be
helpful - even just a small dash icon would be useful :)

**Comment by helenvarley** [comment]
looking great! just a couple of tiny details about the tool tips. some of them are plural & some singular, it would be good to be consistent. & the scenes icon doesn't have a tool tip. 
the scenes icon also is larger than all the others, and changes from grey to green when activated. none of the other icons change when activated. i think this is because originally the whole tool bar was going to change to a scenes tool bar, which we realised we didn't need. the icons should either all change when activated, or none change when activated ...

tool tip corrections:
Backdrops 
Streams
Scenes 
Settings

**Comment by nguyenhongphat0** [comment]
Yes, and do you think we need a new icon for the Scene tool? I don't think a "switch" for it is suitable anymore 😅

**Comment by vickis** [comment]
Perhaps it’s a tiny s
Or a document...

**Comment by helenvarley** [comment]
i agree, a switch doesn't make sense any more. let's ask our icon expert @riadsalameh :)
