### ISSUE TITLE
Message Mouse Hover

### ISSUE THREAD

**Issue by elisadcg** [upstage-org/mobilise#503]
on Stage, as a player, when we hover the toolbox we get a tooltip. It's would be good when we hover the chat, we have a tooltip too (minimize/no minimize and settings button)

![Screenshot_20210802_080553](https://user-images.githubusercontent.com/7611913/127811895-4973be61-d044-44cd-90bf-2f4c4181d8eb.png)

**Comment by nguyenhongphat0** [comment]
Here you go @elisadcg 🙌 Let me know if you would like to add tooltip to anywhere else 🙏 

<img width="334" alt="Screenshot 2021-08-02 at 23 35 01" src="https://user-images.githubusercontent.com/29925961/127894621-4f43c52e-de56-4d97-9c8b-65603f25fc3a.png">
<img width="333" alt="Screenshot 2021-08-02 at 23 35 13" src="https://user-images.githubusercontent.com/29925961/127894652-cbfd5567-a6bc-45a8-b8bc-39cd0692b726.png">
<img width="336" alt="Screenshot 2021-08-02 at 23 35 24" src="https://user-images.githubusercontent.com/29925961/127894673-b1de2568-dce0-4431-a774-64c2e4004a92.png">
<img width="323" alt="Screenshot 2021-08-02 at 23 35 38" src="https://user-images.githubusercontent.com/29925961/127894705-a328f2e5-ec52-41e7-9036-f861187553a9.png">

**Comment by vickis** [comment]
Super work Phat! :)

**Comment by helenvarley** [comment]
great! could you please spell "minimise" with an s instead of a z? (it's the same as customise - z is american spelling, s is british ... )

**Comment by elisadcg** [comment]
great work :)

**Comment by nguyenhongphat0** [comment]
Here you go 👍 
<img width="137" alt="Screenshot 2021-08-03 at 16 34 14" src="https://user-images.githubusercontent.com/29925961/127993512-47f0ca5b-b0da-46f6-9ced-1fee47b8229b.png">
<img width="117" alt="Screenshot 2021-08-03 at 16 34 34" src="https://user-images.githubusercontent.com/29925961/127993541-5f2c0dc6-9389-467c-90fb-628f5c2ed570.png">

**Comment by helenvarley** [comment]
thank you :)
