### ISSUE TITLE
Drawing tool : scale box

### ISSUE THREAD

**Issue by elisadcg** [upstage-org/mobilise#504]
it seem that the rescale is not working as a drawing. I suggest to not let it appear when it's a drawing object.

![Screenshot_20210802_081642](https://user-images.githubusercontent.com/7611913/127812815-1dc1150e-5315-4712-93f8-7c3a41c0fe89.png)

**Comment by elisadcg** [comment]
well now it's work in my side.... i don't know what happen

**Comment by vickis** [comment]
This happens sone times what is required is careful selection and using a
corner handle to properly achieve
When not carefully selected rescale can act like a move command but it just
moves the rescale selection box
I suggest keep testing this as changes are made to the drawing tool :)
