### ISSUE TITLE
drawing tool : remove permanently from stage

### ISSUE THREAD

**Issue by elisadcg** [upstage-org/mobilise#505]
Often you draw a bad drawing and you wanted to delete it permanently. I suggest to add in the contextual menu in the drawing object : delete permanently, which allows player to not see more the drawing object in the top overlay list.
![Screenshot_20210802_082216](https://user-images.githubusercontent.com/7611913/127813268-daf380c4-4044-4e9b-8676-638622b68d50.png)

**Comment by vickis** [comment]
Agree
Also useful would be to be able to right click and delete permanently from
the save drawings bar :)

**Comment by nguyenhongphat0** [comment]
Here you go 🙌 

<img width="464" alt="Screenshot 2021-08-03 at 23 51 47" src="https://user-images.githubusercontent.com/29925961/128057401-9ff393d3-18cf-49ee-b06c-764f4e70a2c2.png">
<img width="326" alt="Screenshot 2021-08-04 at 00 13 32" src="https://user-images.githubusercontent.com/29925961/128057823-9d324924-2de5-421d-bf4c-f85a58450364.png">

**Comment by vickis** [comment]
Super thanks Phat! :)

**Comment by helenvarley** [comment]
could this option also be added to the text tool? it would be useful to be able to remove text objects from the tool bar as well, if you have a lot & don't need them.
