### ISSUE TITLE
stage: chat font size (player)

### ISSUE THREAD

**Issue by helenvarley** [upstage-org/mobilise#51]
as a logged-in player on a stage, i expect to be able to adjust the size of an avatar's text in the chat window and corresponding speech bubbles - e.g. make it slightly larger or smaller than everyone else's text for particular effect.

**Comment by elisadcg** [comment]
![51-chat-font-size-02](https://user-images.githubusercontent.com/7611913/97151085-516f7600-176f-11eb-8c98-51db93fd30ee.png)

A dedicated button to upscale font or downscale font upstair the chat (1) or downstair the logo upstage (2)...

**Comment by helenvarley** [comment]
as discussed in the meeting, this should be underneath the chat input field.

**Comment by vickis** [comment]
agree tools placed close to the input field they are actioning is most
useful :)

**Comment by elisadcg** [comment]
So underneath the chat, i think it could be better upstar the chat field.
![issue51-02](https://user-images.githubusercontent.com/7611913/98099385-c89fbb00-1e8f-11eb-8fa0-ec83b32f660f.png)

**Comment by helenvarley** [comment]
how would it look for audience? they don't have the different shout / think / whisper options 
(i don't think we should offer the audience options to colour their text, this could be distracting & conflict with the performance)

**Comment by elisadcg** [comment]
Yes i was thinking the same, and for audience maybe we can let them to adjust the font size, and that's all ?

**Comment by nguyenhongphat0** [comment]
We can use the Ctrl + and Ctrl - (zoom) to change the font size

**Comment by helenvarley** [comment]
but this doesn't change only the font size (at least not for me) - it also increases the area of the chat window, the tool bars, and the "live" indicator and player/audience counter. we need to be able to increase just the font size within the chat window (and the speech bubbles - altho maybe this needs to be separate?). this is quite important, especially when UpStage is projected in a physical venue for a proximal audience who might be some distance away from the screen.

**Comment by helenvarley** [comment]
can this be prioritised? i am going to go blind trying to read the chat ... :laughing: 
we need a tool to increase the font size in just the chat, and in just the speech bubble (separately - as you may want the chat window text to be bigger than the speech bubbles).
it seems logical to me that this tool should be in the parameters of the chat window setting, where you can also adjust the opacity, but it would be nice to have a simple + & - kind of tool for just the chat window font size somewhere very easy to find, e.g. just above the input field, next to the emoticons (but in some way differentiated so that people don't think they are adding emoticons or putting a + on as a reaction).

**Comment by nguyenhongphat0** [comment]
Yes you can priotise any issue by put it on the top of the TODO list: https://github.com/upstage-org/mobilise/projects/1. I will resolves one by one from the top 🐝

**Comment by nguyenhongphat0** [comment]
Done 🎉 
<img width="1318" alt="Screenshot 2021-06-12 at 22 40 07" src="https://user-images.githubusercontent.com/29925961/121781490-39017e00-cbcf-11eb-894b-43e7ac3d2ea3.png">
