### ISSUE TITLE
stage: chat font size (audience)

### ISSUE THREAD

**Issue by helenvarley** [upstage-org/mobilise#52]
as an audience member on a stage, i expect to be able to adjust the size of the font in the chat window.

this is especially important for accessibility for visually impaired people, and in situations where UpStage is being projected in a space for a gathered audience.

it should be simple and intuitive to do it.

**Comment by elisadcg** [comment]
Does we allow Ctrl + / Ctrl - of the navigator to scale the font of the chat ?
Or do we let access a parameter above the chat to the audience member scale the font size ? (1)
Or do we let access a parameter on the left side of the screen the chat to the aucience member scale the font size (2) ?
![Uploading chat-font-size-01.png…]()

**Comment by helenvarley** [comment]
@elisadcg the image hasn't uploaded properly, i can't see it ...

**Comment by vickis** [comment]
I think if we make the chat size a scale we again diminish screen
realestate
Having it be a code control which is common across most software works for
me :)

**Comment by helenvarley** [comment]
could the chat text size be something that is also set in the menu where audience can change nickname? it feels like this would be the place for audience to be able to adjust any things that they are able to.

**Comment by helenvarley** [comment]
can the option to change font size be in the pop-up window for the chat box settings?
(there are probably other things that would be good to include here too - different for player and audience of course)
![Screenshot at 2021-03-06 13-05-54](https://user-images.githubusercontent.com/3437324/110206244-d8023580-7e7c-11eb-9b32-d30d41f1ab46.png)

**Comment by elisadcg** [comment]
In the parameter of the chat it would be good to have the possibility to ajust the font-size.
![issue-52-chat-option](https://user-images.githubusercontent.com/7611913/110295059-f25d2000-7ff0-11eb-8086-8adc833c1229.png)

**Comment by helenvarley** [comment]
would a + & - be easier? as people may not know what the size is, & often it's a case of just wanting to make it a bit bigger for reading ... ? or to have both?

**Comment by elisadcg** [comment]
Like this ?
![issue-52-chat-option-2](https://user-images.githubusercontent.com/7611913/110297179-7adcc000-7ff3-11eb-9dfd-c5805eebf59f.png)

**Comment by helenvarley** [comment]
i'm sure we will think of quite a few parameters we could have here :)

**Comment by nguyenhongphat0** [comment]
`Does we allow Ctrl + / Ctrl - of the navigator to scale the font of the chat ?`

Yes we can now, since we have the relative position working.
<img width="500" alt="Screenshot 2021-03-08 at 19 20 47" src="https://user-images.githubusercontent.com/29925961/110320764-645e5500-8043-11eb-89d6-acd4d7bd5203.png">
<img width="500" alt="Screenshot 2021-03-08 at 19 21 10" src="https://user-images.githubusercontent.com/29925961/110320811-72ac7100-8043-11eb-82fb-096552173bc3.png">

**Comment by helenvarley** [comment]
awesome phat!
