### ISSUE TITLE
show multiframe av icon in stage management media list

### ISSUE THREAD

**Issue by helenvarley** [upstage-org/mobilise#524]
it would be helpful if, in the stage management media list, we could identify which avatars & props are multiframe ones. this is because often we have assigned both multiframe and the individual frames to a stage, for testing or by mistake, and need to easily remove them.

**Comment by nguyenhongphat0** [comment]
Here you go 👍

<img width="520" alt="Screenshot 2021-09-03 at 17 15 59" src="https://user-images.githubusercontent.com/29925961/131989952-6f1786c2-3017-4944-bb6e-8f2e03e7ffb4.png">

**Comment by vickis** [comment]
🙏
