### ISSUE TITLE
unable to access frame of media item i'm holding

### ISSUE THREAD

**Issue by helenvarley** [upstage-org/mobilise#526]
a number of times in the presentation today, i was unable to access the frame of the avatar i was holding, or the text object i was manipulating.
typically what would happen is that i would drag the av or text object onto the stage. the frame would be there and i could adjust it and put the lightbulb on, but when i put the lightbulb on the frame disappeared and i was unable to get it back. when the frame disappeared i would see the frame of another object that someone else was operating.
@vickis did this happen for you as well?

**Comment by vickis** [comment]
not exactly like that
i was mainly in drawing - but it did seem very easy as the cursor moved
across the stage to see or select others

**Comment by nguyenhongphat0** [comment]
This issue is the same cause with #527, it was because of the resizing frame changed to another object (not on purpose). I will close this one so that we can focus on the other issue 👌
