### ISSUE TITLE
media zoomed off stage

### ISSUE THREAD

**Issue by helenvarley** [upstage-org/mobilise#528]
several times during the presentation today, a media item that i was operating suddenly zoomed off the stage. this happened when i was trying to move an avatar or a text object. i would get the frame and either drag it a little bit in one direction, or move the frame handles to move it (often it was not possible to drag, particularly with text objects, so i adjusted the frame to move it). i would start to drag it, but suddenly the object would fly off in the direction i was dragging, but very fast and completely off the stage.
the media item would still show in the depth tool, but be off the side of the stage so inaccessible. i had to delete it from the depth tool and re-place on the stage.

@vickis did this also happen for you?

**Comment by vickis** [comment]
yes - it appeared that the object was finding the edge of the
stage and falling off it
- especially if it was outside of the parameter of the backdrop image

it seemed that very quick movement was confusing it (we had a busy stage
with 7 players and 37 audience :)

sometimes it appeared like it was sticky to the cursor (this sometimes
happens with the graphic tablet if the pen is too close to the surface as
you move back across the tablet...

**Comment by helenvarley** [comment]
there were only 6 players operating (sara was logged in, but just watched the performance) & eva said she would focus on the audio so 5 operating objects on the stage; there can often be 6 (or more) players, so we need to make sure that it isn't too confusing. seeing only the frames for the media you are operating will help (see #527).

**Comment by nguyenhongphat0** [comment]
This issue happens when an object is still "animating" and moved to a new position/reisizing. It got fixed 👌

**Comment by helenvarley** [comment]
ok - hard to test but hopefully it is fixed! :)
