### ISSUE TITLE
chat emojis - difficult to use

### ISSUE THREAD

**Issue by helenvarley** [upstage-org/mobilise#529]
the chat emojis are quite difficult to use in the heat of a performance, mainly because the pop-up of emoji options doesn't disappear after you've selected one. 
can the popup disappear after you select one emoji?

**Comment by nguyenhongphat0** [comment]
> holding shift or another key allows you to select multiples

Great idea Vicki, it is on dev-app1 now ☝️

**Comment by vickis** [comment]
Woop! :D

**Comment by helenvarley** [comment]
great :) 
just one thing: after clicking on the emoji, the pop-up window disappears, but my cursor is not in the text input field. i intuitively clicked enter to send the emoji, but found i had to click in the input field again first.
can it be that after you've selected the emoji and the pop-up disappears, you can either hit enter to send or carry on typing without having to move the cursor back to the input field and click again?

**Comment by nguyenhongphat0** [comment]
> can it be that after you've selected the emoji and the pop-up disappears, you can either hit enter to send or carry on typing without having to move the cursor back to the input field and click again?

Yes it can 😆 After you finish with the emoji picker, the cursor will be focused into your chatbox

**Comment by vickis** [comment]
Great :)
