### ISSUE TITLE
recording feature

### ISSUE THREAD

**Issue by helenvarley** [upstage-org/mobilise#53]
as a logged-in player, i expect to be able to record a performance either via a built-in tool or a feature that makes using a third-party tool extremely easy.

possible existing third party tool: such as https://webrecorder.io/

it could be either a screen recording (creates a large video file) or a "replay" system whereby the log messages are run again (small file, but probably wouldn't be able to include any live audio-visual stream content) - or could there be a combination of both?

it would be good to do some research & thinking around the options & what might be best to provide an easy way to record, archive & access material.

**Comment by helenvarley** [comment]
i think this issue has been partly resolved with the replay feature. there are still some issues:

- [ ] change menu wording to read "Recordings" (instead of "Records")
- [ ] what about live audio &/or video streams? do we have a solution for including them?
- [ ] the chat log is currently saved as one long unbroken text; it would be good to have this in separate files that correspond to the separate recording files
- [ ] does the recording happen automatically, & if so is there an option to NOT record? might be useful in some sensitive situations?
- [ ] how do we delete recordings?
- [ ] is it possible to export a recording out of UpStage, either to another UpStage instance or into some other format?

**Comment by vickis** [comment]
Seems if we automatically include audio &video these might very quickly
become a data heavy Archive so agree that to record should be a new
decision each time
Delete needs to be possible

If the recording is like a replay it would require an UpStage instance to
view (and would then also need to bundle all the stage objects I do’t see
this as viable

Recordings should just be a complete capture of what is seen and heard like
a screen recording

**Comment by helenvarley** [comment]
i've just been having a look at the recording of the works-in-progress, and
- i can hear avatar voices, but not audio (i haven't watched the whole thing, but i'm pretty sure there was audio in the part i did look at)
- i can see the frames around the media - usually one at a time has the frame, but nearly always there is a frame visible
- i'm playing it at 1x speed but it is going way faster than actual speed

**Comment by helenvarley** [comment]
more refinements for the replay feature: 

- [ ] there is a LOT of empty space. we need a way to minimise this, because scrolling through the emptiness of the recording it's actually very easy to miss the action, as this is such a small part of the whole record. could there be an indicator (colour perhaps, or marker?) on the time slider, so you know where the action is? and/or can there be a way to trim out the empty parts?
- [ ] i can imagine that i would sometimes want to make a screen recording from a replay. but this would have the replay tool visible in the bottom left corner. can the tool be hidden, or moved, when i want to make a screen recording? (this will be super useful for training videos, as you could make a screen recording in player view, then record the replay of what you did that shows the audience view)

**Comment by nguyenhongphat0** [comment]
> could there be an indicator (colour perhaps, or marker?) on the time slider, so you know where the action is?

Yes, there could be 👍 Look at these greens markers

<img width="1425" alt="Screenshot 2021-08-08 at 16 23 24" src="https://user-images.githubusercontent.com/29925961/128627346-0fc0edf5-001f-45f1-a5e2-16b2718f3c66.png">

> and/or can there be a way to trim out the empty parts?

I'm afraid trim out the empty parts won't work in the way we expects. I propose the 2 new forward/backward button (screenshot). Pressing the forward button will jump to the next "action" and skip all the blank if there is, so you won't have to worries about these empty parts anymore. I will work on the "clip replay" feature, which allow you to really trim the long auto-recorded replay into smaller separated parts. Let me know if this sound okay to you 👌

**Comment by nguyenhongphat0** [comment]
>  can the tool be hidden, or moved, when i want to make a screen recording?

Yes it can 😅 

<img width="1292" alt="Screenshot 2021-08-08 at 16 38 23" src="https://user-images.githubusercontent.com/29925961/128627708-5224bb82-2d6c-4394-a7ac-11004a9a5c07.png">

**Comment by helenvarley** [comment]
great! :)

**Comment by vickis** [comment]
nice work Phat :)
