### ISSUE TITLE
text tool: font dropdown menu not appearing in firefox on linux

### ISSUE THREAD

**Issue by helenvarley** [upstage-org/mobilise#530]
on dev-app, using firefox on linux, the dropdown font menu for the text tool is not displaying properly:
![Screenshot at 2021-08-25 21-47-57](https://user-images.githubusercontent.com/3437324/130769056-c2426440-3a0a-4a10-8cb2-1fdb719a6859.png)

on app1 it's also not displaying properly when i first click on it, but when i move my mouse down the menu does appear.
![Screenshot at 2021-08-25 21-52-11](https://user-images.githubusercontent.com/3437324/130769607-0cc3416e-53fd-478a-a771-88f75bb08c4b.png)

**Comment by nguyenhongphat0** [comment]
Sorry about this annoying issue 😅 I patched a hotix 👌 
<img width="772" alt="Screenshot 2021-08-31 at 21 43 31" src="https://user-images.githubusercontent.com/29925961/131523692-e358bd12-118b-4870-8b71-7089869247c9.png">

**Comment by vickis** [comment]
Awesome thanks Phat :)

**Comment by helenvarley** [comment]
great - tested on firefox & chromium on linux & it's working now :)

**Comment by helenvarley** [comment]
whoops wrong button :laughing:
