### ISSUE TITLE
deleting media doesn't work

### ISSUE THREAD

**Issue by helenvarley** [upstage-org/mobilise#531]
when i try to delete a media item, i go to https://app1.upstage.org.nz/V4.0/ui/backstage/media and find the item i want to delete. i click on the red trash icon at the right hand end of the media listing, & get the pop-up warning telling me there is no undo, it will be permanently deleted. i click "yes", i'm sure i want to delete it. the little circle goes round on the yes button, but the pop-up window doesn't disappear, nor does the media item i'm trying to delete.

i'm using firefox on linux, but this issue was first reported by one of the artists who is i think on a mac.

**Comment by nguyenhongphat0** [comment]
Can you try with a fresh reload (Ctrl+F5), Helen? This is my recording with Firefox on Mac, and it works fine:

https://user-images.githubusercontent.com/29925961/131214382-41d3eaf6-9218-4fef-b283-db5a31176d86.mov

If it's still doesn't work for you, please send me the name of the media you want to delete. Thank you!

**Comment by vickis** [comment]
I just went to try and test this but do not seems to be able to do anything
other than make a new stage...

**Comment by helenvarley** [comment]
i think i know what the problem is - i can delete media that i myself have uploaded, but not someone else's. however, eva-maria first raised the problem because she could not delete her avatar, & i have been trying to delete it for her.
players with admin status (like vicki & i) should be able to delete anyone's media.
i'll ask eva-maria to try again & see if it works for her.

**Comment by vickis** [comment]
i successfully removed one of the single avs of eva's
mac/chrome

**Comment by helenvarley** [comment]
eva's, or eva-maria's? (username egu) 
eva-maria is trying to delete the avs on the exercise bike. i still can't delete them ...

**Comment by vickis** [comment]
did you manage to - i cannot see them anymore ...

**Comment by vickis** [comment]
there is now only a backdrop and audio file by egu...

**Comment by helenvarley** [comment]
eva-maria wrote to me that she tried again & managed to delete :)
she also said that it she could not delete an image that is a grame of a multiframe av, until she had first deleted the multiframe av - which makes sense; & this might be why i was unable to delete it.
@nguyenhongphat0 - we need a message. if we are trying to delete a single image of a multiframe av/prop/backdrop, can there be a message that says: "This image cannot be deleted because it is part of a multiframe media item. You must either remove it from the multiframe, or delete the multiframe media item, if you want to delete this image."

**Comment by nguyenhongphat0** [comment]
> "This image cannot be deleted because it is part of a multiframe media item. You must either remove it from the multiframe, or delete the multiframe media item, if you want to delete this image."

Actually this was a bug happened with multi-frame media deletion and it got fixed. Media which is part of a multiframe media item can be deleted safely, and the parent media will notice of it 👌
