### ISSUE TITLE
text tool and object drawing - consistent functionality?

### ISSUE THREAD

**Issue by helenvarley** [upstage-org/mobilise#535]
both the text tool and the object drawing tool allow us to create and save an object that can then be manipulated on the stage.
on the object drawing, the tool opens at the create overlay, and once a drawing object is saved we have the option to delete it from the tool bar.
on the text tool, the tool opens with the tool bar, showing the "new" button and any saved text objects. it's not possible to delete saved text objects.
it would be great if both of these tools had the same functionality:

- clicking the icon in the left-hand tool bar opens the tool's tool bar, showing a "new" button and any saved objects
- clicking the "new" button opens the overlay to create a new object
- right-clicking on an object's icon in the tool bar gives the "delete permanently" option

**Comment by nguyenhongphat0** [comment]
Agree 🙌 

<img width="339" alt="Screenshot 2021-09-03 at 22 31 09" src="https://user-images.githubusercontent.com/29925961/132030713-d41ff122-19bb-4350-aa62-9855e47bdf13.png">

**Comment by vickis** [comment]
Super thanks :D

**Comment by helenvarley** [comment]
in testing this i have discovered a bug which i will make a new issue for.

**Comment by vickis** [comment]
:o
