### ISSUE TITLE
missing "new" button on media interface

### ISSUE THREAD

**Issue by helenvarley** [upstage-org/mobilise#540]
last night we discovered that some players had no "new" button on the media interface in the backstage. this meant that they could not upload media and could not create their own stream.

Manel was on Windows // Browser: Brave (Chrome) (the same is happening with Firefox)
Sara was on Mac // Browser: Firefox

We haven't seen this issue before, & Vicki & I are not experiencing it.

**Comment by vickis** [comment]
I went and checked Manel's profile (he had only guest access as there was
no email assigned
i have assigned email and sent a message asking him to check again

I am not sure why this would have affect Sara as she has player access
(same as Eva Maria) so should have been able to add media

**Comment by helenvarley** [comment]
interesting - i didn't even know there was a "guest" role ... what is that for? what permissions does it have?

**Comment by vickis** [comment]
guest is the default - they can do nothing but login and be on stage

**Comment by vickis** [comment]
as in they can see and navigate around backstage but not add anything :)

**Comment by nguyenhongphat0** [comment]
Really? 😆 It was you who was requesting the guess role, and want to create mass number of them. Here: https://github.com/upstage-org/mobilise/issues/2

**Comment by helenvarley** [comment]
> Really? laughing It was you who was requesting the guess role, and want to create mass number of them. Here: #2

you are totally correct, @nguyenhongphat0 - that bit fell out of my brain  :laughing: 

i think what we need is for the basic "player" role to be the default, rather than guest. "guest" is only used for workshops & walkthroughs, when we need people to have access to the on-stage player tools but not to be able to upload media.
if we are creating an account for a specific person then it would be because they are going to be a player & will need to upload.
it was also my mistake not to enter manel's email address.

but also as vicki said, sara also could not see the "new" button, and she has player status ...

**Comment by vickis** [comment]
correction Sara said last night that she could
she uploaded and deleted media successfully

**Comment by vickis** [comment]
This appears to be working for all :)
