### ISSUE TITLE
Assign custom curtain to stage

### ISSUE THREAD

**Issue by vickis** [upstage-org/mobilise#546]
I have made a curtain and can see it in curtain media 
can open edit and add permissions etc but am unable to assign to a stage? 

![image](https://user-images.githubusercontent.com/4249450/131588393-200058c0-bde5-4dfb-9952-2409f74c2836.png)

**Comment by helenvarley** [comment]
i can see your curtain, but i can't try to assign it or access the edit interface for it - presumably because the permissions are set to "use with acknowledgement".
(as an admin, can i not over-ride that?)

**Comment by vickis** [comment]
i have changed permissions - but that does not affect the ability to assign it 
as you can see the green curtain has no assign to stage either 

![image](https://user-images.githubusercontent.com/4249450/131589594-df910520-5e4f-466a-a925-a480876f5f40.png)

**Comment by vickis** [comment]
By default the custom curtain has been assigned to all stages... (

* Please add the function assign stage to curtain edit tool bar

:)

**Comment by helenvarley** [comment]
yes that makes sense. it's good to have the red & green curtains as defaults, but it would be good to be able to unassign them if they're not needed, & to have your own curtains for your own stage only.

**Comment by elisadcg** [comment]
On Backstage when we assign the new media as a curtain and allow it in a Stage, the curtain does'nt appear on the listed media...
It's probably more consistent to add the curtain on media list too

**Comment by vickis** [comment]
Agree - stage editor needs to be able to assign and un assign curtain
backstage :)

**Comment by helenvarley** [comment]
agree - it does show in the Media section as a media type, so it should also be in the Stage Management section. It should be in all lists of media type everywhere.

**Comment by vickis** [comment]
Woop! :)
