### ISSUE TITLE
audience reaction emojis - possible to hide and expose?

### ISSUE THREAD

**Issue by helenvarley** [upstage-org/mobilise#548]
one of the artists has asked if it's possible to hide the audience reaction emojis - the ones that appear on stage. this would be useful, as in some performances or at some times of a performance they might be distracting, especially if someone goes a bit crazy with them.
could this be another option in the on-stage settings? next to hiding or exposing the chat?

**Comment by nguyenhongphat0** [comment]
> could this be another option in the on-stage settings? next to hiding or exposing the chat?

Yes it could 😆 Do you think we need another icon for it?

<img width="744" alt="Screenshot 2021-09-01 at 22 20 30" src="https://user-images.githubusercontent.com/29925961/131698522-25d77d11-3207-4028-8bf0-a395981346de.png">
<img width="738" alt="Screenshot 2021-09-01 at 22 20 12" src="https://user-images.githubusercontent.com/29925961/131698547-09d6591d-93d7-41ce-afd1-11d4200fa91a.png">

**Comment by vickis** [comment]
Great :)

**Comment by helenvarley** [comment]
wow great! & yes we do need another icon ... @riadsalameh ? :)

**Comment by nguyenhongphat0** [comment]
It would take you some more clicks to achieve the same thing. Besides, people sometimes don't know existence of features that was inside the context menu, like the multiframe backdrop 😅

**Comment by vickis** [comment]
ha ha you're right Phat :D
so many exciting things!

**Comment by helenvarley** [comment]
> It would take you some more clicks to achieve the same thing. Besides, people sometimes don't know existence of features that was inside the context menu, like the multiframe backdrop sweat_smile

very true! :laughing:
