### ISSUE TITLE
stage: flip / rotate avatars

### ISSUE THREAD

**Issue by helenvarley** [upstage-org/mobilise#56]
as a logged-in player holding an avatar on a stage, i expect to be able to flip the avatar (horizontally and vertically) and rotate it.

currently on UpStage v3 this is done using a right-click menu. this is neither intuitive or easy to do quickly.

**Comment by riadsalameh** [comment]
For the rotation and scaling, I thought it would be better to have it as form of a box where you can simply modify it. Just like the animation and new wireframes that Elissa did. While in the action menu, instead of having the fade in/Fade out option, it could be played on more with opacity maybe, that way artists will have more control over the way they want their avatars to face and their timing.

**Comment by elisadcg** [comment]
I have imagine a palette upstar the avatar with a suboption Moove. I have put a slider for opacity as Riad suggest.
For the revelation of this sub palette we have 3 choices :
- it's appear always on top of the avatar (1a)
- it's appear on right click of the avatar (1b)
- it's appear on a clic on the left (palette option) (1c)
![avatar-moove-choice01](https://user-images.githubusercontent.com/7611913/95992466-44c55680-0e2e-11eb-9beb-eb952433c68f.png)

**Comment by vickis** [comment]
Agree 1b :)

**Comment by elisadcg** [comment]
![avatar-moove-choice02](https://user-images.githubusercontent.com/7611913/97149441-0ce2db00-176d-11eb-90b8-876a9cc550f2.png)

**Comment by vickis** [comment]
superb work - looking really great and useful  :)

**Comment by helenvarley** [comment]
we can rotate, but we can't flip. is a horizontal/vertical flip possible to have? it can be really useful for making an avatar look in one direction or another.

**Comment by vickis** [comment]
Tis could be good yes (although achievable with multi frame SV :)

**Comment by helenvarley** [comment]
true, but that requires an additional graphic and if there are several frames in a multiframe av, it's not very fast to switch them. if there was a horizontal flip option in the context menu this would mean one click & not having to look through the little thumbnails to find the right one. & less media on the server.

**Comment by helenvarley** [comment]
great!

**Comment by vickis** [comment]
wahoo! :)
