### ISSUE TITLE
logged out and showing as guest but still see tools

### ISSUE THREAD

**Issue by helenvarley** [upstage-org/mobilise#560]
i logged out (to test clickable links as audience) and entered the demo stage. i didn't enter a nickname, just clicked to enter the stage, and got the welcome message saying that my username is guest. however in the counter, i am showing as an audience member called helen, and i can see the player tools. when i click on the sign-post image, the link doesn't work. and when i click on the crinoline image, i see the green frame.
this was using chromium on linux.

**Comment by vickis** [comment]
did you shift reload the stage?
could have been a caching issue  :)

**Comment by nguyenhongphat0** [comment]
I was able to re-produce this issue and fixed 👌, thank you very much for reporting @helenvarley, @vickis  🙏

**Comment by vickis** [comment]
Woop :)
