### ISSUE TITLE
admin powers

### ISSUE THREAD

**Issue by helenvarley** [upstage-org/mobilise#562]
how much power do admins currently have, and is this enough?
i wanted to look at InterAkt's stage as manel has some questions about the backdrops, but because it is an upcoming stage, i'm not able to enter it even though i had admin status.
in the backstage, i can enter the stage management interface for this stage & edit it, even though i don't have player or edit access on this stage.

**Comment by nguyenhongphat0** [comment]
Well admins have full powers in the Backstage, which means they can view/edit and delete any stages/media that they want to. They can also grant admin role to others players, and active/deactivate/delete other users/admins. But on the stages, only the players/owner of the stage can perform. So if you are an admin, but only have audience permission to the stage, you can only watch it

**Comment by helenvarley** [comment]
ok, maybe that's best :)

**Comment by vickis** [comment]
Yes I think that’s right :)
If you need to do something on Mandela’s  stage you could be assigned  as
player on that stage right ?

 each should have control of permissions on their own stage and media etc

**Comment by helenvarley** [comment]
yes - as an admin i was able to give myself player access to the stage. i wanted to do this so that i could see if he'd managed to assign the backdrops, as he wrote that he was having difficulty with this. i will leave myself as a player for the time being as they may need other help.
