### ISSUE TITLE
lightbulb button not working properly 

### ISSUE THREAD

**Issue by helenvarley** [upstage-org/mobilise#565]
i am having trouble with the lightbulb button on dev-app. when i drag a media item onto the stage, i cannot turn the lightbulb on. there were some media items on the stage with the lightbulb turned on. when i turn it off, i'm unable to turn it back on again.

**Comment by nguyenhongphat0** [comment]
I just tested on dev-app1, it is working for me 🤔 Which stage are you using, Helen?

**Comment by vickis** [comment]
yes working for me too :)
demo stage dev1 - chrome / mac OS

**Comment by helenvarley** [comment]
aahh ... it's the firefox websocket thing. i got my new laptop when i got back to munich & have been setting it up this week. everything just worked fine in firefox and i forgot about the websocket thing ... it's a bit of a trick, as we can enter stages & do most things, so easy to forget about it.
is there a way that we can solve this? a lot of people use firefox, so we either need to have some sort of warning popup to alert them to the need to change the websickets thingy, or else have some solution that is automatic ...

**Comment by nguyenhongphat0** [comment]
> is there a way that we can solve this? a lot of people use firefox, so we either need to have some sort of warning popup to alert them to the need to change the websickets thingy, or else have some solution that is automatic ...

Well we already have that (the bouncing Firefox icon) 😅 In the past it was only shown when the status is CONNECTING, I made it visible when the status is OFFLINE as well 👌 

<img width="258" alt="Screenshot 2021-09-19 at 16 59 27" src="https://user-images.githubusercontent.com/29925961/133923335-adaa9a0b-3011-47a5-9550-95d0e26ba11d.png">
<img width="1389" alt="Screenshot 2021-09-19 at 16 59 45" src="https://user-images.githubusercontent.com/29925961/133923340-8ff7594f-3952-4058-9e99-9638e20fa17d.png">

**Comment by helenvarley** [comment]
is that on dev-app? i just tried changing the websockets setting back to true, & now when i enter the stage i see for about half a second, the "connecting" with the firefox icon beside it, and then it goes to "offline" - without any firefox icon.

**Comment by helenvarley** [comment]
do audience members need to know about this, or does it only affect players? because if it also affects audience, then i think we need something more obvious. but if it's just players then it's something that can be explained in workshops and in the manual.

**Comment by nguyenhongphat0** [comment]
It is on dev-app1 now, @helenvarley. Now when it goes to "offline", the icon would still be there.

All Firefox users has to do this themselves, no matter if they are audience or players. Sorry about that, but I cannot come up with another solution at the moment. Maybe in the future Firefox or Mosquito will resolve this 😅

**Comment by helenvarley** [comment]
i set the config back to the default, so now when i enter the stage (either as logged in player or as audience) the stage shows as offline, but there is no firefox icon next to the offline status. i have no prompt to find out how to fix the problem.
![Screenshot from 2021-09-19 18-13-22](https://user-images.githubusercontent.com/3437324/133934797-c20a4935-4f37-4015-ac45-6baeabdbbdb2.png)
.

**Comment by helenvarley** [comment]
interesting - i changed the websockets setting and then saw what i'd typed when i was "offline" now appeared in the chat ... does that mean that others could see what i was typing at the time?

**Comment by nguyenhongphat0** [comment]
It looks like caching issue, Helen 🤔 Can you do a fresh reload and check again?
<img width="233" alt="Screenshot 2021-09-20 at 20 53 12" src="https://user-images.githubusercontent.com/29925961/134014200-cb6d729d-d08f-43fd-b51d-5335464729f8.png">

**Comment by nguyenhongphat0** [comment]
> interesting - i changed the websockets setting and then saw what i'd typed when i was "offline" now appeared in the chat ... does that mean that others could see what i was typing at the time?

Nah... it was your messages get queued while you're being offline, and when you update the settings and your connection is establish, all the queues messages are sent, that why you see them appeared 😅

**Comment by helenvarley** [comment]
does it mean that everyone would see them, once i'm online?

**Comment by helenvarley** [comment]
> It looks like caching issue, Helen thinking Can you do a fresh reload and check again?
> <img alt="Screenshot 2021-09-20 at 20 53 12" width="233" src="https://user-images.githubusercontent.com/29925961/134014200-cb6d729d-d08f-43fd-b51d-5335464729f8.png">

ok, now i see it. BUT i think this is not obvious enough for audience members who have never been in UpStage before. it would not make me think that i need to do something there, especially as i can see everything on the stage - i would be waiting for something to happen. could it not be that instead of the stage loading, it just comes up with the instructions of how to fix the problem?
i think it needs to be very very obvious.

**Comment by helenvarley** [comment]
great! thank you - it's impossible to miss now :+1: 
but one more thing ... since it opens immediately, we need to adjust the first line of text (the person hasn't got stuck on connecting as they haven't yet reached the stage). could that first sentence be changed to:
"A Firefox setting needs to be changed to allow you to access UpStage on Firefox."

when i go to about:config, i get a "Proceed with caution" message and have to click "Accept the risk and continue". i gues not everyoe sees it, as i can turn off this notification. but many audience members will still see it, and might be nervous to continue. can there be an additional step that shows this screen and says:
"Click to continue. Don't worry, this is not going to cause any problems!"
![Screenshot from 2021-09-21 15-26-43](https://user-images.githubusercontent.com/3437324/134179327-730bd374-9cb3-4b86-9c5c-61e55fa93973.png)

**Comment by helenvarley** [comment]
great solution :+1:

**Comment by vickis** [comment]
agree!
we should not be saying 'this will not cause problems' as we have no
control over what people do beyond what is suggested

nice work :D

**Comment by helenvarley** [comment]
> we should not be saying 'this will not cause problems' as we have no control over what people do beyond what is suggested

true ... the intention is to reassure people who might not want to do anything that carries possible risk. how about:
"Click to continue. Don't worry, the setting change needed for UpStage to work will not impact on performance or security or Firefox."

**Comment by helenvarley** [comment]
i'm going to close this issue as it was originally for a different bug which wasn't actually a bug, & all that remains to be done is to change that line of text, & that should be a separate issue. i'll make it :)
