### ISSUE TITLE
Drawing not responding as expected when using Tablet & Pen 

### ISSUE THREAD

**Issue by vickis** [upstage-org/mobilise#573]
This is one of the artist's issues (i cannot replicate) 

When using a graphics tablet the drawing is not following properly the action of the stylus pen 

- the pen can create dots but not lines  (as it was being demonstrated the screen appeared to flash briefly when trying to perform actions
- when right click is activated lines can be drawn (but the pen must be engaged for right click to activate)

PC computer on Bravo.com, also happening in chrome - not tested yet on firefox

https://dev-app1.upstage.org.nz/V4.0/ui/live/demo
CTL 480

Tablet works fine in graphic applications, and when tested on the whiteboard in BBB

**Comment by elisadcg** [comment]
Drawing tool working fine : drawing tool or live drawing with my tablet (basic wacom).

**Comment by helenvarley** [comment]
manel found the solution: https://support.wacom.com/hc/en-us/articles/1500006273281-Why-is-Google-Chrome-not-accepting-clicks-or-is-lagging-
he had to go to the properties of the tablet and add Chrome / Brave to application and un-check the option "use windows ink.".

i will add this to the user manual.

**Comment by vickis** [comment]
Just to note here also that Vu suggested there could also be an issue with
libraries - which he was looking into
