### ISSUE TITLE
curtain action and speed

### ISSUE THREAD

**Issue by helenvarley** [upstage-org/mobilise#574]
for my test stage, i set the curtain to fade in and out, and set the speed to slow. i saved the settings, and went to the stage to see what happened.
the curtain fades in and out, but very fast.
i used the back button to return to the stage management, and saw that the curtain was set to drop down and lift up, and the speed was set to as fast as it could be.
i reset it to fade, and slow, saved it, and entered the stage. 
again, the curtain faded in and out, but very fast.
i went back to the foyer page, then to backstage and then to the stage management for my stage (rather than use the back button in the browser). again, the curtain settings are showing drop down rather than fade, and fast.
i entered the stage without changing the settings. the curtain is still fading in and out (contrary to what stage management is showing) and fast.
it seems that the slider for the speed of the curtain is not working at all, & there is something wrong also with the curtain animation setting.

**Comment by helenvarley** [comment]
also, when i save the customisation settings, the message reads "Layout settings saved" - but this section is now called Customisation, so it would be better if the save message said "Customisation saved"
![Screenshot from 2021-09-22 15:56:42](https://user-images.githubusercontent.com/3437324/134358552-52a3ed3f-ea66-4375-ad7b-6a5ac132e7dd.png)
s

**Comment by helenvarley** [comment]
this seems to be working better, however the difference between slow and fast is minimal. slow is still very fast! & the slider is so big, it implies that there is a lot of range. but even when it is as slow as it can be, it is still less than a second.
can the slow end be really slow, like 5 seconds?

**Comment by nguyenhongphat0** [comment]
Yes, the lowest transition duration is now 5s 👌
