### ISSUE TITLE
Firefox settings instructions

### ISSUE THREAD

**Issue by helenvarley** [upstage-org/mobilise#575]
this is a new issue to separate this issue out from an unrelated one. 
in the pop-up window that appears for Firefox users who need to change their websockets setting, could the line about the warning (that Firefox might throw up when users go to about:config) please read:
"Click to continue. Don't worry, the setting change needed for UpStage to work will not impact on performance or security or Firefox."

**Comment by vickis** [comment]
Should this read ‘for Firefox’ not 'or Firefox' ?

**Comment by helenvarley** [comment]
good spotting! actually it should be "of Firefox":
"Click to continue. Don't worry, the setting change needed for UpStage to work will not impact on performance or security of Firefox."

**Comment by nguyenhongphat0** [comment]
Here you go 🙌 

<img width="852" alt="Screenshot 2021-09-25 at 17 15 23" src="https://user-images.githubusercontent.com/29925961/134767821-e8f0a9a7-aee5-4ac4-84da-5658c21a1090.png">
