### ISSUE TITLE
chat window: after minimising, opens at oldest chat, not newest

### ISSUE THREAD

**Issue by helenvarley** [upstage-org/mobilise#577]
if i minimise the chat window and then re-maximise it, it displays the very beginning of the chat (oldest). normally i want it to reopen with the most recent chat showing.
when i open the player chat, it scrolls quickly down so that i am then seeing the most recent player chat. could the public chat work like this too?

**Comment by vickis** [comment]
Agree!
Both Chat widows refer to time stamp and by default always display the most
recent message

perhaps also If user is scrolling back through chat messages window
indicates that new messages have been submitted
on the old UpStage this was indicated by a change in the chat window colour
:)
