### ISSUE TITLE
option to have fade transition for multiframe media and backdrops?

### ISSUE THREAD

**Issue by helenvarley** [upstage-org/mobilise#578]
the artists have asked if it is possible to make multiframe objects (avatars, props, backdrops) transition from frame to frame with a fade rather than just switching to the next image?
also could there be an option for backdrops to transition with a fade? (similar to how the curtain can be set to fade)

**Comment by helenvarley** [comment]
awaesome that you are looking at this! is it on dev-app yet? how does it work?

**Comment by nguyenhongphat0** [comment]
Yes it is on dev-app1 now, and it works just like how multi-frame avatar worked in the past, but with fade animation. You can go to demo stage to try 👌

**Comment by helenvarley** [comment]
great - is there any possiblity to control the speed of animation for backdrops?

**Comment by nguyenhongphat0** [comment]
There is a slider below the multiframe backdrop, you can use it to control the animation speed

**Comment by helenvarley** [comment]
ah! ok. i see that on one multiframe backdrop but not on another. it's very tiny, & also the slowest speed is still really fast. can the slowest speed be similar to the slowest speed for the curtain fade?
![Screenshot from 2021-09-26 14:58:01](https://user-images.githubusercontent.com/3437324/134809093-271b3fbc-1e14-4d2a-9d69-19d495f88b16.png)
![Screenshot from 2021-09-26 14:57:48](https://user-images.githubusercontent.com/3437324/134809094-6c33b2f9-3b5b-4f48-a356-ba11cb99c04d.png)

**Comment by vickis** [comment]
Great phat - slowest speed on curtain is 5s so that would’ve good for
backdrop transistion also :)

**Comment by helenvarley** [comment]
this is great! :)
