### ISSUE TITLE
props

### ISSUE THREAD

**Issue by helenvarley** [upstage-org/mobilise#58]
as a logged-in player on a stage, i expect to be able to place props on the stage, move them around and remove them.

props can be:
- placed on stage & left there (independently of an avatar)
- moved on the stage (independently of an avatar)
- held & carried by an avatar (i.e. it moves along when you move the avatar)
- passed from one avatar to another (which we can currently do)
- animated
- flipped or rotated
- scaled
    
avatars can go in front of or behind props

some more discussion about what differentiates a prop from an avatar would be helpful.

**Comment by paul-rohrlach** [comment]
@helenvarley can you please provide some example backdrop assets?

**Comment by helenvarley** [comment]
do you mean backdrops or props? this issue is about props ... ??

**Comment by paul-rohrlach** [comment]
Yes. Yes I do 🤦‍♂️

**Comment by helenvarley** [comment]
that was not a yes/no question, it's either or :D 
we have all kinds of different props. they are basically just a graphic object - can be an animated gif, or a jpg or png - usually png in order to have transparency. i'll upload some examples here.

**Comment by helenvarley** [comment]
here are 2 that were specifically made as props - the apartment building so that it was in front of the avatars that appeared in the windows; & the mask was "worn" by an avatar. note that for the mask prop, the dimensions of the image are much bigger than the image of the mask, & it's positioned towards the bottom right; this is because (currently) a prop is "held" by an avatar to the upper left of the avatar image. so if you want a prop that is an additional thing for an avatar - such as a mask - it needs to be quite precisely positioned.
in fact, an easier solution is to make a multi-frame avatar that has the "prop" already added to it in another frame. so in many ways, props are not necessary, or should function differently than they currently do. this is something we need to discuss further ...
![apartment_block_prop_800](https://user-images.githubusercontent.com/3437324/94314678-5202ca00-ff81-11ea-8751-75f07d87b636.png)
![mask_prop_lighter](https://user-images.githubusercontent.com/3437324/94314689-5af39b80-ff81-11ea-870a-733423ad510b.png)

**Comment by paul-rohrlach** [comment]
Right haha, sorry.

I meant props (given that this issue is about props)

**Comment by vickis** [comment]
Props are always sitting on the very front layer
it is useful to create the device of depth within the way layers
occurred in UpStage (z-index)

eg the apartment building in the Juex de Massacre
or the forest in Babayaga

it is possible to create a 'prop' that an avatar is 'wearing' by creating
one still of an animated avatar
but the great thing about props sitting in that 'front' layer is that
avatars can move around behind them (baba yaga)
or used beautifully in (erm one of florian, gabi & petyr show's ) where the
avatar appeared to enter and exit a hallway through different doors

i think they are a useful device and would like to see them (or a similar
function0 in the new version :)

I guess an alternative might be (to make it either or... ;)
if there were x number of layers that the avatars operate on then the
backdrop would by default be on the most behind and 'props' could have a z
index assigned (that would be useful :)

**Comment by helenvarley** [comment]
one issue is that currently props have to be "held" by an avatar. i don't think this is necessary - it should be possible to place a prop on the stage independently of an avatar, & have it just sit there until it's removed. but this could also be done with an avatar.

what's the difference then between a prop & an avatar?
- a prop doesn't have a voice
- a prop can't be "held" by a player & moved around in the same way (but if it can be moved, then in what way?)
- currently, props sit on a front layer, always in front of avatars - but maybe it's useful to be able to move the props to difference layers as we can with avatars?
- props appear in a separate list to avatars, so on a stage that has a lot of media it can make things easier to find if some are props & some avatars

what else differentiates props from avatars, or what could be the different uses?

**Comment by elisadcg** [comment]
About props associated to avatar, how do you prefer we call it ?
Since the avatar palette (1), or since the left bar (2) ?
![Uploading props-linked-avatar-call01.png…]()

**Comment by helenvarley** [comment]
i wonder if it makes sense to go with "costumes" and "props"? 

a "costume" would be something that an avatar "wears" - could be a coat, hat, bag, placcard, anything really, that is attached to the avatar, moves with the avatar, etc. these would be accessible from the avatar palette.

a "prop" would be an independent object, so it would have its own palette, accessible from the left-hand bar, & it would be something that becomes part of the scenery. ideally moveable on layers and in position. i'm also remembering how props functioned in The Palace - one prop icon could be placed multiple times on the stage, so for example if there is one flower in the props gallery, you could click to select it, place it on the stage, then click it again and place another, etc, to have a bunch of identical flowers. they could be moved around on the stage by click & drag, & right now i can't remember how they were taken off the stage (right click menu? @vickis can you remember?)

**Comment by helenvarley** [comment]
@elisadcg this image has not uploaded properly, can you do it again?

**Comment by riadsalameh** [comment]
I am updating the terminology and I am not sure what we agreed on costume/costume prop that we can attach to regular props?? Should I add it to the Maybe/Nice to have Terms??

**Comment by helenvarley** [comment]
yes - at the moment we only have one type of prop; at one point it was possible to attach a prop to an avatar, but this turned out to be problematic so currently we don't have the costume-prop idea. so yes, file it in "nice to have" for the time being :)

**Comment by helenvarley** [comment]
@nguyenhongphat0 today in rehearsal i saw that, whenever an avatar speaks, it comes in front of the prop. we want to see the avatar's speech bubble in front of the prop if possible, but the avatar itself should not move in front of the prop. this is quite important! for example with the building prop above, the avatars appear in the windows and speak. this doesn't work if, every time an avatar speaks, it is suddenly in front of the prop, instead of only visible through the window.

**Comment by helenvarley** [comment]
and: when we have our avatars behind the prop, & see the red carrot indicating the avatar we are holding, we cannot move our avatar or access the context menu for the avatar. if we try to move our avatars, we just move the prop, & if we right-click we get the context menu of the prop.
we need to be able to move and access the context menu of the avatar we are holding, even if it's behind a prop.

**Comment by nguyenhongphat0** [comment]
Okay to sum up, we have:
- Depth tools, which show us all objects on stages sorted by z-index. We can use the Depth tool to bring an object to front of another one (previously we can only "bring to front most" and "send to back"). We can drag an object on the depth tool to a new position, so it could be easier to move an avatar that is behinds a building, for example

<img width="1327" alt="Screenshot 2021-05-28 at 13 10 41" src="https://user-images.githubusercontent.com/29925961/119938135-20ca1600-bfb6-11eb-822f-42438458529a.png">

- When avatar speak, it won't automatically bring to front anymore

Let me know what else should be done to close this issue 💪

**Comment by vickis** [comment]
This is great Phat!! :D

**Comment by helenvarley** [comment]
yay! :)
before closing this issue (which really is several issues together ... ) there are of course a couple of other things: i don't see a slider on the prop, but when i right click there are the slider options, & on R2D2 the props have the slider ...

& there is the question of the "costume prop", that is a way to add a prop to an avatar, so that it moves around with the avatar. for example, an avatar puts on a hat prop and when the avatar moves, the hat goes with it.
our work around for now is to make multiframe avatars; but this is only good when we know beforehand what we want. it would be great if, spontaneously during the performance, an avatar could add a prop.

should we have a separate issue for the costume prop function?

**Comment by nguyenhongphat0** [comment]
> i don't see a slider on the prop

Sorry, I brought the slider back on non-avatar objects 😅

**Comment by nguyenhongphat0** [comment]
> should we have a separate issue for the costume prop function?

Yes let's close this issue and create a separated issue for costume. And set a priorities for it as well!
