### ISSUE TITLE
minimise button on player chat doesn't always work

### ISSUE THREAD

**Issue by helenvarley** [upstage-org/mobilise#584]
the minimise button on the player chat window does not always work. clicking on the star and adjusting the frame size sometimes makes it work.

![minimise_player_chat](https://user-images.githubusercontent.com/3437324/134803270-236366fc-6f6b-400a-96d3-154310833ee5.gif)

**Comment by nguyenhongphat0** [comment]
Sorry for the issue, it got fixed on dev-app1 😅

**Comment by vickis** [comment]
Super :)
