### ISSUE TITLE
statistics

### ISSUE THREAD

**Issue by helenvarley** [upstage-org/mobilise#59]
as a logged-in player, i expect to be able to see real-time running statistics in the workshop interface.

statistics shown should include:
- Number of connected players across all stages
- Number of connected audience users across all stages
- Number of stages currently in use (IE: current performances / rehearsals / workshops)

would other statistics be useful, e.g. cumulative stats, server performance, recent logins?

can audience / non-logged-in anyone also see some or all stats?

**Comment by elisadcg** [comment]
I undertand that this statistic have to be visible during the show ?
![view-statistic01](https://user-images.githubusercontent.com/7611913/95978724-d88d2780-0e1a-11eb-9edc-8f6fe484ddc1.png)
Do you think it's a good idea to put this information in the left-top palette ?

**Comment by helenvarley** [comment]
actually this issue is specifically for the display of statistics in the workshop interface rather than on stage. there is a separate issue for that, #29.
can you repost on #29?

**Comment by helenvarley** [comment]
the statistics are now displayed in the stages list Backstage
