### ISSUE TITLE
Authentication and Authorization System

### ISSUE THREAD

**Issue by paul-rohrlach** [upstage-org/mobilise#62]
We need a system for authenticating users and keeping track of what they are authorized to access.

Ideally, this system will allow for traditional username/password authentication at first with other options down the road.

**Comment by paul-rohrlach** [comment]
@gloriajw can you perhaps summarize what you have in mind?

**Comment by nguyenhongphat0** [comment]
In my opinion we have a complete Authentication and Authorization System:
- Login / Logout
- Register
- Registration Approval
- Profile Management
- Reset Password
- Delete User
- Change Role/Permission

I'll close this issue. If we need another enhancement on the Authentication and Authorization System, let's open another issue for it

**Comment by vickis** [comment]
woop! :D
