### ISSUE TITLE
publish changes to avatar or scene 

### ISSUE THREAD

**Issue by helenvarley** [upstage-org/mobilise#63]
as an artist, i want to have the option to make changes to an avatar or a scene visible to the audience during the change, or only published once the change has been made.
for example: i might want the audience to see an avatar or backdrop fade in & out; so i want it to be published while happening. or, i might want to make changes to an avatar such as adding a prop, and then have it appear on stage like that - so i make the changes and then publish it.

**Comment by elisadcg** [comment]
I imagine the same icon to publish after change the change on avatar  OR during the change of avatar.
![publish-change-avatar01](https://user-images.githubusercontent.com/7611913/95976236-7ed72e00-0e17-11eb-99e3-02ff44eb1666.png)

I imagine the same icon to publish after change the change on scene  OR during the change of the scene.

![publish-change-scene01](https://user-images.githubusercontent.com/7611913/95976255-83034b80-0e17-11eb-8d8b-81af3cc60cb2.png)

**Comment by helenvarley** [comment]
it looks good, elisa, & makes sense to have a consistent method of doing this, whether you are changing an avatar or a backdrop or anything else.

am i understanding it right, that it could function like this:
- off: audience does not see the changes
- on: audience sees the changes as they happen
- clicking "on" after making the changes: audience sees the result of the changes

so, if i scale an avatar while it's on, the audience sees it scaling; and if i scale while it's off, then when i finish scaling i click on, the audience effectively sees a jump, from the original state to the final state after the changes are made.

should the default state be on or off? will artists more often want changes to be seen or not?

**Comment by vickis** [comment]
Agree great idea for consistency :)

**Comment by riadsalameh** [comment]
I was thinking that maybe at the bottom of the platform there could be the "stages" and there are two options "Online" and "Offline". It is simply activated by clicking on it and it changed the color of the stage from "active" to "inactive" similar to Isadora. That way artists can choose if they want the audience to see the actions and changes while they are doing it or after

<img width="306" alt="Screen Shot 2020-10-19 at 12 40 01 PM" src="https://user-images.githubusercontent.com/71765608/96440619-86784780-1208-11eb-8c23-965d1ba0c991.png">

**Comment by helenvarley** [comment]
sounds like a good idea, altho "online / offline" might be a bit confusing, as presumably the stage is still active / online for everyone else who is on it, players & audience, apart from the player who has set it to offline to prepare something, is that right?
what about using "wings" from theatre terminology? if you click on "wings" then it's as if you (& only you) have stepped into the wings to prepare something; there could be a colour change over the stage to reflect this for you.
or words like "prepare" & "ready"?

**Comment by vickis** [comment]
That sounds like a great idea and useful between significant changes
It also sounds like a more useful tool for significant scene changes

How would this work for example where multiple artists are changing
different elements

For example I am drawing, mem is musing some audio and Helen is setting the
table
Avatars of  the mad hatter and the Cheshire Cat are moving towards the cake


When I click online and the information is transferred to the active stage
I imagine it checks for difference then overwrites so how would we stop
overwriting changes others had made

For example Helen table of delicious treats goes back to being the empty
plates that is the information the comes with the colourful smoke and the
caterpillar I have drawn

I guess what would be required to answer my question is check
In check out (liking laters to others

But I am used to the collaborative space being far faster more fluid and
dynamic (as in the others artists and the audience watch the changes at the
same time

It would good to explore how layers are activated or not and how like with
the discussion about avatars etc the changes are visible as they occur -
this is what differentiates the liveliness sometimes for audiences

**Comment by elisadcg** [comment]
Question to be answer :
- the "ready" button : is on the palette itself or at the bottom of the stage to direct and unique access ?
- name of this button ?
- state of this button : default on or default off ?

**Comment by helenvarley** [comment]
& another question is does this button function with just the changes that one player has made, or how is it managed when more than one player is making changes at the same time?

**Comment by elisadcg** [comment]
you mean 2 player artist tweak the same avatar the same moment ???? how awful idea ! Do you think it's useful for you ?

**Comment by helenvarley** [comment]
no! :D only one player can hold and manipulate an avatar! i mean if several players are making changes to different things, as in vicki's example above - if one person is making a drawing or changing the scene, and another changes their avatar & clicks publish/online/ready/whatever we call it - does this only publish the changes that one player has made? could it happen that one player publishes something that over-rides something someone else is preparing? this is probably a question for the developers ...

**Comment by vickis** [comment]
definitely a good question for the developers
if several connected players are all making changes to the stage they have
in front of them
then a kind of check in or out might be required

like a locking layers for edit
the issue i imagine can be described when several people are making changes
to a live document

if drawing, sound, props, backdrops are all on different layers as previous
it may not be such an issue 'but if multiple people are interacting how
does UpStage then differentiate priority

**Comment by elisadcg** [comment]
So about the ready button : localisated on the palette upstair the avatar or on the side with the other panel-action ?
![issue63](https://user-images.githubusercontent.com/7611913/97990670-9a16d700-1de0-11eb-9ffd-252cb06e8e46.png)

**Comment by helenvarley** [comment]
probably it should be on the avatar palette, since this will involve less movement of the cursor and therefore be faster.

however, for publishing changes to a stage, where would the publish button be? would it need to be in the side bar? & if it was in the side bar for publishing the stage, would it then be consistent & intuitive to have it the same for all changes?

**Comment by elisadcg** [comment]
Yes it's a good point helen. If we delocalisate the ready-to-publis button in the sidebar, artist can forget to switch when they want, that's why i put this button in each actions !

**Comment by vickis** [comment]
sounds sensible! :)

**Comment by elisadcg** [comment]
probably a test session would be wonderful to adjust this point.

**Comment by helenvarley** [comment]
this issue has been resolved with #160 hasn't it? i will close it ...
