### ISSUE TITLE
Basic Stage

### ISSUE THREAD

**Issue by paul-rohrlach** [upstage-org/mobilise#65]
Create a basic stage based on CSS3 with the intention of utilizing it with [anime.js](https://animejs.com/)

**Comment by paul-rohrlach** [comment]
@gloriajw please add context here.

**Comment by paul-rohrlach** [comment]
@petyrv if you could get started with this and I'll jump in as soon as I've finished admin stuff / my work on #61

**Comment by paul-rohrlach** [comment]
Because @petyrv and @elisadcg are at roughly the same understanding of git.  It would be good if you could work together to learn the basics of pull/push, commit, branching and pull requests.

Then, if you could work together on getting this issue done?

To reiterate what we talked about:  This issue simply calls for turning the wireframes of the stage into an HTML/CSS skeleton.  It doesn't need any JS at this stage and none of the buttons need to "do" anything.  We just want to see the wireframes in HTML/CSS form.

**Comment by elisadcg** [comment]
yeah :) yes
