### ISSUE TITLE
set media copyright 

### ISSUE THREAD

**Issue by vickis** [upstage-org/mobilise#7]
as a user when creating or uploading media items i have the ability to determine the copyright permissions and use categories referencing Creative Commons 
a drop down or similar should display options something like:
copyright free (can be used by other players in any way without need for permission)
use with permission (other players must ask the owner for permission if they want to use the media item)
use with acknowledgement (other players can use the media item as long as the owner is acknowledged)
not shared (nobody except the owner can user the media item; that is, only the owner can assign it to stages - if it is assigned to a stage then it would be available for players who have access to that stage).

**Comment by helenvarley** [comment]
can we get the media permissions implemented for the next release?

**Comment by nguyenhongphat0** [comment]
Working on it 👌

**Comment by nguyenhongphat0** [comment]
Let me know if this UI look good to you
<img width="1440" alt="Screenshot 2021-07-25 at 19 32 00" src="https://user-images.githubusercontent.com/29925961/126899167-c9896061-e5db-4bf9-a2cc-b86fffaa446c.png">

I have a question: What is the real different between "use with permission" and "use with acknowledgement"? 🤔

**Comment by vickis** [comment]
Looks good Phat
The difference is in the explanation
Acknowledge means you don’t have ask but must indicate where media
originated

Permission means you need to ask before using (and then would likely also
have to acknowledge source

Essentially you are saying the media was created by someone else :)

**Comment by helenvarley** [comment]
yes generally looks good, altho it's quite a lot of text to read in a dropdown menu. would it be better to just use the bolded text, & leave the longer explanation to the manual? you only need to know the explanation once, not every time you set it.

the order should be:
- Copyright free
- Use with acknowledgement
- Use with permission
- Not shared

what happens in the "use with permission" situation? if a media item is set to "use with permission" and i want to use it, i can see who the owner is, but how do i request permission? and how does the owner grant me access to that media item?

**Comment by nguyenhongphat0** [comment]
> what happens in the "use with permission" situation? if a media item is set to "use with permission" and i want to use it, i can see who the owner is, but how do i request permission? and how does the owner grant me access to that media item?

Yes this is what I'm concern. At the moment if media copy right is set to either "Use with acknowledgement" and "Use with permission", a list of players will be shown so that you can decide who will got read and write access (just like how stage permission works). So I suppose you don't have to "request permission", you are "granted permission" by the media owner. But it just make "Use with acknowledgement" and "Use with permission" the same. Is this fine? 🤔

**Comment by helenvarley** [comment]
well they aren't the same. use with acknowledgement means that the media is available for everyone to use, but they should acknowledge whose media it is. use with permission means that they can't use the media at all unless the owner grants permission. so there has to be a way that players can give individual players access to a media item.
if we can't do that, or if it's something we need to leave for now & work out later, then we should not list "use with permission" as an option, only the other 3.

**Comment by nguyenhongphat0** [comment]
> so there has to be a way that players can give individual players access to a media item

We already have that. It is the 3 columns above

> media is available for everyone to use, but they should acknowledge whose media it is

I can made it available for everyone 👌, but how can I make them "acknowledge"? 🤔

**Comment by elisadcg** [comment]
For the explaination around the drop down menu option, i suggest to put a little icon (?) after the option 'Use with permission' (?). And when the user hover the (?), the text appear (example : you need to ask before using). Or display this information when this option is selected on the right.

**Comment by vickis** [comment]
If restricting use is going to be difficult then we should operate under
the previous tryst model
Eg the item has an explanation regarding the artist wishes to be able to
grant permission ...

If anyone has something they feel they must control use of then perhaps
they need to remove the original item after they are done

Also permissions options could have a full explanation in the manual ::)

**Comment by helenvarley** [comment]
i just tried the giving permission, & gave vicki permission to use & edit my stream. it looks like it's worked & isn't difficult.
agree full explanation of permissions in manual, & elisa's suggestion of the question mark icon with roll-over explanation is good. once people have used it a few times they will know what it means.

**Comment by helenvarley** [comment]
as for forcing people to acknowledge - i don't think we can; we have to leave it to trust. but if people are concerned & want to ensure acknowledgement, then they can use the "use with permission" setting, so that others have to ask first & then they know who might be using it & can specify how they want it acknowledged.

**Comment by nguyenhongphat0** [comment]
> For the explaination around the drop down menu option, i suggest to put a little icon (?) after the option 'Use with permission' (?). And when the user hover the (?), the text appear

We got it 🙌 
<img width="653" alt="Screenshot 2021-07-28 at 10 35 26" src="https://user-images.githubusercontent.com/29925961/127259567-aa2dc45a-eee8-4b61-94cf-1838f78cad0b.png">

**Comment by helenvarley** [comment]
i'm trying to change the copyright for media that i uploaded previously, but there is only "Copyright free" in the dropdown ...

**Comment by nguyenhongphat0** [comment]
Sorry I didn't notice that 😅 It got fixed!
<img width="1127" alt="Screenshot 2021-08-02 at 23 38 15" src="https://user-images.githubusercontent.com/29925961/127895068-cb4f4599-6054-4051-b64d-9a73b4e7c5d5.png">

**Comment by vickis** [comment]
:)

**Comment by helenvarley** [comment]
works now!
