### ISSUE TITLE
layout of user list interface

### ISSUE THREAD

**Issue by vickis** [upstage-org/mobilise#8]
As a logged in player (or only admin?) I want to see an alphabetical list of all users with information including username, permission/rights, date account was created, date of last log in, and possibly other information. This should be in a table that can be sorted by all columns (e.g. I can easily see which players have not logged in for years) and should also be searchable.

**Comment by helenvarley** [comment]
there probably needs to be 2 displays of this list: one for all logged in players, as it can be useful for them to see some info about other players; & the other for admins, that includes info such as email addresses which should not be visible to everyone.

**Comment by helenvarley** [comment]
this has been achieved in the Admin section of the Dashboard.
