### ISSUE TITLE
audience reaction

### ISSUE THREAD

**Issue by helenvarley** [upstage-org/mobilise#80]
we've talked before about having an applause button or similar for the audience. last night i watched a performance which was a live stream of a recorded performance, with a live chat alongside it for the audience (& a discussion afterwards, streaming zoom). i think the stream interface was a custom built one, it didn't have any branding other than La Mama Theatre which was hosting the event. As audience, we had the option to use 4 emojis (applause, hands waving, hearts, laughing) as our reactions, which showed up along the bottom of the stream window when clicked. They were a bit animated, fading in & out & maybe bouncing a little. There were times when there were just a few visible, and sometimes eg the end or particular moments, the strip at the bottom was crowded with the emojis. i took some screenshots to show how it worked. 

if we had something like this in UpStage, it should be an option that players can select to have displayed or not (for some performances you would not want emojis showing up - potentially they can be very distracting); maybe it would also be possible to select what emojis you wanted to be offered to the audience, or to upload your own?

here are the screenshots:
![Screenshot at 2020-11-21 02-28-52_crop](https://user-images.githubusercontent.com/3437324/99880585-a5596780-2c14-11eb-97a0-fa6f38cedb9f.png)
![Screenshot at 2020-11-21 02-31-07_crop](https://user-images.githubusercontent.com/3437324/99880587-a7bbc180-2c14-11eb-8521-c21e6a857d2d.png)
![Screenshot at 2020-11-21 02-29-09_crop](https://user-images.githubusercontent.com/3437324/99880590-a8ecee80-2c14-11eb-93df-243d7475f072.png)

**Comment by vickis** [comment]
This looks great
the audience count and live button also right by the chat input (as a
reminder of being in an online environment with many others :)

its slightly like the live streams on FB where the emojis fly up as they
are added
good that it's just expressive responses and alongside are the comments
much like a proximal audience reacting

yay
clapping hands emoji, celebration emoji, hearts emoji, broad grin emoji :D
