### ISSUE TITLE
Application Protocol

### ISSUE THREAD

**Issue by paul-rohrlach** [upstage-org/mobilise#82]
This issue calls for the prototyping of an application specific "UpStage" protocol built on top of MQTT which defines the way in which performance state and changes will be communicated between the client and server applications.

The scope of this issue includes a mostly feature-complete draft of the protocol and a basic example implementation.  

This needs to be time-boxed carefully such that we don't spend too long going down rabbit holes.  Therefore, I suggest we make a final decision on direction during the dev meeting scheduled for November 26th.

@helenvarley can you please ensure this is on the agenda?

**Comment by helenvarley** [comment]
done :) https://openproject.techcultivation.org/meetings/18
